### ISSUE TITLE
StepVerifier.withVirtualTime(...) possible race condition

### ISSUE THREAD

**Issue by Jamalarm** [reactor/reactor-core#1098]
Hi Guys,

This behaviour is stumping me a bit, I don't know exactly what's causing it. I will give as much info as I can, shout if you need more from me.

### Expected behavior
Running multiple Spock tests very quickly using virtual time via `StepVerifier.withVirtualTime(...)` should complete without error. Example test:

```
def 'Emails are retried until the first successful attempt'() {
        given:
            emailSender.willFailTimes(failureCount)
    
        expect:
            StepVerifier.withVirtualTime({onEmailDispatcher()})
                .thenAwait(Duration.ofSeconds(30))
                .verifyComplete()
    
        and:
            emailSender.sentEmails.size() == 1
        
        where:
            failureCount << [1, 2, 3, 4, 5]
}
```

### Actual behavior
The above test runs fine on our CI, and on my Macbook, but on my Windows 10 PC (which is much faster) the gradle build fails with the following error:

```
Caused by: java.lang.IllegalStateException: VirtualTimeScheduler is shutdown
	at reactor.test.scheduler.VirtualTimeScheduler.createWorker(VirtualTimeScheduler.java:227)
	at reactor.test.scheduler.VirtualTimeScheduler.createWorker(VirtualTimeScheduler.java:44)
	at reactor.core.scheduler.Schedulers$CachedScheduler.createWorker(Schedulers.java:623)
	at reactor.core.publisher.MonoSubscribeOn.subscribe(MonoSubscribeOn.java:48)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3077)
	at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:123)
	at reactor.test.scheduler.VirtualTimeScheduler.advanceTime(VirtualTimeScheduler.java:300)
	at reactor.test.scheduler.VirtualTimeScheduler.advanceTimeBy(VirtualTimeScheduler.java:209)
	at reactor.test.DefaultStepVerifierBuilder.virtualOrRealWait(DefaultStepVerifierBuilder.java:2070)
	at reactor.test.DefaultStepVerifierBuilder$WaitEvent.run(DefaultStepVerifierBuilder.java:2116)
	at reactor.test.DefaultStepVerifierBuilder$DefaultVerifySubscriber.waitTaskEvent(DefaultStepVerifierBuilder.java:1484)
	at reactor.test.DefaultStepVerifierBuilder$DefaultVerifySubscriber.pollTaskEventOrComplete(DefaultStepVerifierBuilder.java:1504)
	at reactor.test.DefaultStepVerifierBuilder$DefaultVerifySubscriber.verify(DefaultStepVerifierBuilder.java:1100)
	at reactor.test.DefaultStepVerifierBuilder$DefaultStepVerifier.verify(DefaultStepVerifierBuilder.java:723)
	at reactor.test.DefaultStepVerifierBuilder$DefaultStepVerifier.verify(DefaultStepVerifierBuilder.java:695)
	at reactor.test.DefaultStepVerifierBuilder.verifyComplete(DefaultStepVerifierBuilder.java:564)
	... 1 more
```

Adding the following post-test delay fixes the issue:
```
    @After
    public void slightDelay() {
        sleep 100
    }
```

### Steps to reproduce
I'm honestly not sure at this point how to reliably write a test to reproduce this. It seems to be at least partially hardware dependent.

### Reactor Core version
`3.1.4.RELEASE`

### JVM version (e.g. `java -version`)
```
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
```

**Comment by simonbasle** [comment]
Parallel test execution when at least one test uses `StepVerifier.withVirtualTime` is not supported, as it uses a global hook to replace Reactor default `Schedulers` process-wide.

Are your Spock tests configured to run in parallel? (or maybe that's the default?)
Forking JVMs for parallel tests, if that's an option, would work.

**Comment by Jamalarm** [comment]
Hi Simon,

Thanks for the quick response!

I don't believe parallel execution is the culprit here. Gradle does not support same-JVM parallel execution as far as I can see, and the only discussion I could find about native Spock parallelisation seemed to go quiet over a year ago.

**Comment by simonbasle** [comment]
pending confirmation of resolution by #1104

**Comment by Jamalarm** [comment]
Hi Simon,

Bizarrely I stopped seeing the issue after reordering some tests (concurrency issues...yay...). So I'm not 100% sure I can say if the issue is fixed at this point, it might just be hiding. I'm happy to upgrade my build to use a newer version and check the tests are all good if you give me a specific version number though?

Tom

**Comment by simonbasle** [comment]
@Jamalarm closing this, please feel free to comment/reopen if you see the issue again in milestone `3.2.0.M2` or above!

**Comment by hisener** [comment]
> Parallel test execution when at least one test uses StepVerifier.withVirtualTime is not supported, as it uses a global hook to replace Reactor default Schedulers process-wide.

@simonbasle Is this statement still valid? I am having an issue most probably because of that: https://stackoverflow.com/questions/57509263/using-stepverifier-in-a-parallel-testing-environment

**Comment by srnagar** [comment]
@simonbasle I am noticing this issue as well when one of the tests is using `withVirtualTime`.  Tests that are not using `withVirtualTime` hang when the tests are run in parallel. Works without any issue if the tests run sequentially. If I disable the test that uses `withVirtualTime`, all other tests run successfully in parallel.

We are using the following versions:

```xml
    <dependency>
      <groupId>io.projectreactor</groupId>
      <artifactId>reactor-core</artifactId>
      <version>3.3.11.RELEASE</version>
    </dependency>
    <dependency>
      <groupId>io.projectreactor</groupId>
      <artifactId>reactor-test</artifactId>
      <version>3.3.11.RELEASE</version>
      <scope>test</scope>
    </dependency>
```
