### ISSUE TITLE
StepVerifier missing exception while Mono zipWith another one

### ISSUE THREAD

**Issue by onionf91** [reactor/reactor-core#1117]
With the following code:

```groovy
@IgnoreRest
def "foo test."() {
    given:
    def a = Mono.empty()
    def b = Mono.error(new RuntimeException())
    def source = a.zipWith b then()

    expect:
    StepVerifier.create source verifyError RuntimeException
}
```

### Expected behavior

Test pass

### Actual behavior

Test fail with following message

```
Condition failed with Exception:

StepVerifier.create source verifyError RuntimeException
             |      |      |
             |      |      java.lang.AssertionError: expectation "expectError(Class)" failed (expected: onError(RuntimeException); actual: onComplete())
             |      MonoIgnorePublisher
             <reactor.test.DefaultStepVerifierBuilder@2fc7fa6e script=[defaultOnSubscribe_SignalEvent, expectError(Class)_SignalEvent] initialRequest=9223372036854775807 vtsLookup=null sourceSupplier=reactor.test.StepVerifier$$Lambda$192/1164616817@2af9a5ef options=reactor.test.StepVerifierOptions@34f23816 hangCheckRequested=9223372036854775807 requestedFusionMode=-1 expectedFusionMode=-1>


	at io.beecrazy.artemis.rithmic.impl.service.trade.RithmicTradeServiceSpec.foo test.(RithmicTradeServiceSpec.groovy:147)
Caused by: java.lang.AssertionError: expectation "expectError(Class)" failed (expected: onError(RuntimeException); actual: onComplete())
	at reactor.test.DefaultStepVerifierBuilder.failPrefix(DefaultStepVerifierBuilder.java:2227)
	at reactor.test.DefaultStepVerifierBuilder.fail(DefaultStepVerifierBuilder.java:2223)
	at reactor.test.DefaultStepVerifierBuilder.lambda$expectError$6(DefaultStepVerifierBuilder.java:273)
	at reactor.test.DefaultStepVerifierBuilder$SignalEvent.test(DefaultStepVerifierBuilder.java:1965)
	at reactor.test.DefaultStepVerifierBuilder$DefaultVerifySubscriber.onSignal(DefaultStepVerifierBuilder.java:1320)
	at reactor.test.DefaultStepVerifierBuilder$DefaultVerifySubscriber.onExpectation(DefaultStepVerifierBuilder.java:1265)
	at reactor.test.DefaultStepVerifierBuilder$DefaultVerifySubscriber.onComplete(DefaultStepVerifierBuilder.java:923)
	at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onComplete(MonoIgnoreElements.java:80)
	at reactor.core.publisher.MonoZip$ZipInner.onComplete(MonoZip.java:352)
	at reactor.core.publisher.Operators.complete(Operators.java:125)
	at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:45)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3080)
	at reactor.core.publisher.MonoZip.subscribe(MonoZip.java:128)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3080)
	at reactor.core.publisher.MonoIgnorePublisher.subscribe(MonoIgnorePublisher.java:41)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3080)
	at reactor.test.DefaultStepVerifierBuilder$DefaultStepVerifier.verify(DefaultStepVerifierBuilder.java:722)
	at reactor.test.DefaultStepVerifierBuilder$DefaultStepVerifier.verify(DefaultStepVerifierBuilder.java:695)
	at reactor.test.DefaultStepVerifierBuilder.verifyError(DefaultStepVerifierBuilder.java:544)
	... 1 more
```

### Reactor Core version

`Bismuth-SR7(3.1.5.RELEASE)` and `Bismuth-SR6(3.1.4.RELEASE)`

Before `Bismuth-SR5(3.1.3.RELEASE)`, it work fine.

### JVM version (e.g. `java -version`)

openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-b12)
OpenJDK 64-Bit Server VM (build 25.162-b12, mixed mode)

### Comment

If change order of Monos, this test case will be passed.

```groovy
@IgnoreRest
def "foo test."() {
    given:
    def a = Mono.error(new RuntimeException())
    def b = Mono.empty()
    def source = a.zipWith b then()

    expect:
    StepVerifier.create source verifyError RuntimeException
}
```

**Comment by simonbasle** [comment]
That is expected and normal behavior: `A.zipWith(B)` subscribes to the sources in order, A first then B. `zip` also stops as soon as the first source completes. Since A is empty, it stops immediately, before even subscribing to B.

When you reverse the order, it subscribes to B first, sees the error and propagate that (not subscribing to A).

Use `when(A, B)` to actually wait for the completion of both sources, allowing to see the error in all cases.

**Comment by onionf91** [comment]
Okay, thank you for your clarification. According to document, zip and zipWith will combine given monos into new mono. But error or empty completion of any source will cause other sources to be cancelled. So I can't use `Mono.empty`, may use `Mono.just(new Void())` instead.

**Comment by simonbasle** [comment]
that's not possible (`Void` is by definition not instantiable). Use `when` instead of `zip`. Especially since I see you chain `then()` after your zip...

**Comment by onionf91** [comment]
Can I use `Mono.just(new Object()) instead? If I want both of a and b are concurrent sequence, should I use `when` instead `zip`?

**Comment by simonbasle** [comment]
if your monos can be empty (or you don't care about the values) you have 2 options:

 - you want parallel execution, of both monos: `when(A, B)`
```
 A----v
      |-->
 B----^
```
 - you want sequential execution: `A.then(B)`
```
 A---->B---->
```

`zip` is simply not a good option IMHO.
