### ISSUE TITLE
 Log4J2 fails when reactor logs its objects

### ISSUE THREAD

**Issue by teoincontatto** [reactor/reactor-core#1515]
I'm using `log4j-core:2.11.1` with `slf4j-over-log4j2` and `reactor-core:3.2.5.RELEASE`:

```
2019-02-06 15:14:45,881 main WARN org.apache.logging.slf4j.Log4jLogger caught java.lang.UnsupportedOperationException logging ReusableParameterizedMessage: | {}({}) java.lang.UnsupportedOperationException: Although QueueSubscription extends Queue it is purely internal and only guarantees support for poll/clear/size/isEmpty. Instances shouldn't be used/exposed as Queue outside of Reactor operators.
	at reactor.core.Fuseable$QueueSubscription.iterator(Fuseable.java:145)
	at org.apache.logging.log4j.message.ParameterFormatter.appendCollection(ParameterFormatter.java:592)
	at org.apache.logging.log4j.message.ParameterFormatter.appendPotentiallyRecursiveValue(ParameterFormatter.java:500)
	at org.apache.logging.log4j.message.ParameterFormatter.recursiveDeepToString(ParameterFormatter.java:456)
	at org.apache.logging.log4j.message.ParameterFormatter.formatMessage2(ParameterFormatter.java:189)
	at org.apache.logging.log4j.message.ReusableParameterizedMessage.formatTo(ReusableParameterizedMessage.java:325)
	at org.apache.logging.log4j.core.impl.MutableLogEvent.setMessage(MutableLogEvent.java:213)
	at org.apache.logging.log4j.core.impl.ReusableLogEventFactory.createEvent(ReusableLogEventFactory.java:80)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:404)
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63)
	at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146)
	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2170)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2125)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2108)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2013)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1882)
	at org.apache.logging.slf4j.Log4jLogger.info(Log4jLogger.java:194)
	at reactor.util.Loggers$Slf4JLogger.info(Loggers.java:255)
	at reactor.core.publisher.SignalLogger.log(SignalLogger.java:186)
	at reactor.core.publisher.SignalLogger.safeLog(SignalLogger.java:205)
	at reactor.core.publisher.SignalLogger.lambda$onNextCall$2(SignalLogger.java:264)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:190)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:353)
	at reactor.core.publisher.FluxWindowPredicate$WindowPredicateMain.drainLoop(FluxWindowPredicate.java:443)
	at reactor.core.publisher.FluxWindowPredicate$WindowPredicateMain.drain(FluxWindowPredicate.java:379)
	at reactor.core.publisher.FluxWindowPredicate$WindowPredicateMain.onNext(FluxWindowPredicate.java:224)
	at reactor.core.publisher.UnicastProcessor.drainRegular(UnicastProcessor.java:240)
	at reactor.core.publisher.UnicastProcessor.drain(UnicastProcessor.java:312)
	at reactor.core.publisher.UnicastProcessor.onNext(UnicastProcessor.java:386)
	at reactor.core.publisher.FluxWindowBoundary$WindowBoundaryMain.drain(FluxWindowBoundary.java:309)
	at reactor.core.publisher.FluxWindowBoundary$WindowBoundaryMain.onNext(FluxWindowBoundary.java:177)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:353)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:353)
	at reactor.core.publisher.FluxZip$ZipCoordinator.drain(FluxZip.java:735)
	at reactor.core.publisher.FluxZip$ZipInner.onNext(FluxZip.java:894)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:353)
	at reactor.core.publisher.FluxIndexFuseable$IndexFuseableSubscriber.onNext(FluxIndexFuseable.java:137)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:353)
	at reactor.core.publisher.FluxIndexFuseable$IndexFuseableSubscriber.onNext(FluxIndexFuseable.java:137)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:353)
	at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onNext(FluxConcatArray.java:176)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:353)
	at reactor.core.publisher.FluxJust$WeakScalarSubscription.request(FluxJust.java:99)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.request(FluxOnAssembly.java:438)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:1878)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:1752)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onSubscribe(FluxOnAssembly.java:422)
	at reactor.core.publisher.FluxJust.subscribe(FluxJust.java:70)
	at reactor.core.publisher.FluxOnAssembly.subscribe(FluxOnAssembly.java:116)
	at reactor.core.publisher.FluxCallableOnAssembly.subscribe(FluxCallableOnAssembly.java:51)
	at reactor.core.publisher.Flux.subscribe(Flux.java:7743)
	at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onComplete(FluxConcatArray.java:207)
	at reactor.core.publisher.FluxConcatArray.subscribe(FluxConcatArray.java:80)
	at reactor.core.publisher.FluxOnAssembly.subscribe(FluxOnAssembly.java:132)
	at reactor.core.publisher.FluxIndexFuseable.subscribe(FluxIndexFuseable.java:73)
	at reactor.core.publisher.FluxOnAssembly.subscribe(FluxOnAssembly.java:132)
	at reactor.core.publisher.FluxIndexFuseable.subscribe(FluxIndexFuseable.java:73)
	at reactor.core.publisher.FluxOnAssembly.subscribe(FluxOnAssembly.java:132)
	at reactor.core.publisher.Flux.subscribe(Flux.java:7743)
	at reactor.core.publisher.FluxZip$ZipCoordinator.subscribe(FluxZip.java:579)
	at reactor.core.publisher.FluxZip.handleBoth(FluxZip.java:326)
	at reactor.core.publisher.FluxZip.handleArrayMode(FluxZip.java:267)
	at reactor.core.publisher.FluxZip.subscribe(FluxZip.java:136)
	at reactor.core.publisher.FluxOnAssembly.subscribe(FluxOnAssembly.java:132)
	at reactor.core.publisher.FluxMapFuseable.subscribe(FluxMapFuseable.java:63)
	at reactor.core.publisher.FluxOnAssembly.subscribe(FluxOnAssembly.java:132)
	at reactor.core.publisher.FluxWindowBoundary.subscribe(FluxWindowBoundary.java:73)
	at reactor.core.publisher.FluxOnAssembly.subscribe(FluxOnAssembly.java:132)
	at reactor.core.publisher.FluxMapFuseable.subscribe(FluxMapFuseable.java:63)
	at reactor.core.publisher.FluxOnAssembly.subscribe(FluxOnAssembly.java:132)
	at reactor.core.publisher.Flux.subscribe(Flux.java:7743)
	at reactor.core.publisher.FluxMergeSequential.subscribe(FluxMergeSequential.java:99)
	at reactor.core.publisher.FluxOnAssembly.subscribe(FluxOnAssembly.java:132)
	at reactor.core.publisher.FluxMapFuseable.subscribe(FluxMapFuseable.java:63)
	at reactor.core.publisher.FluxOnAssembly.subscribe(FluxOnAssembly.java:132)
	at reactor.core.publisher.Flux.subscribe(Flux.java:7743)
	at reactor.core.publisher.FluxMergeSequential.subscribe(FluxMergeSequential.java:99)
	at reactor.core.publisher.FluxOnAssembly.subscribe(FluxOnAssembly.java:132)
	at reactor.core.publisher.FluxMapFuseable.subscribe(FluxMapFuseable.java:63)
	at reactor.core.publisher.FluxOnAssembly.subscribe(FluxOnAssembly.java:132)
	at reactor.core.publisher.FluxMapFuseable.subscribe(FluxMapFuseable.java:63)
	at reactor.core.publisher.FluxOnAssembly.subscribe(FluxOnAssembly.java:132)
	at reactor.core.publisher.FluxConcatMap.subscribe(FluxConcatMap.java:121)
	at reactor.core.publisher.FluxOnAssembly.subscribe(FluxOnAssembly.java:132)
	at reactor.core.publisher.FluxLogFuseable.subscribe(FluxLogFuseable.java:53)
	at reactor.core.publisher.FluxOnAssembly.subscribe(FluxOnAssembly.java:132)
	at reactor.core.publisher.Flux.subscribe(Flux.java:7743)
	at reactor.test.DefaultStepVerifierBuilder$DefaultStepVerifier.verify(DefaultStepVerifierBuilder.java:801)
	at reactor.test.DefaultStepVerifierBuilder$DefaultStepVerifier.verify(DefaultStepVerifierBuilder.java:772)
	at xxx.xxx (obfuscated)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:532)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:171)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:167)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:114)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:59)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:108)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
```

This is similar to the behaviour solved in #262 but has come back due to [log4j2 suppressing all exceptions](https://github.com/apache/logging-log4j2/commit/218117a910995918b75ba718076e4b08862245a9) and `SignalLogger` does not receive the `UnsupportedOperationException` thrown by `Fuseable`.

**Comment by bsideup** [comment]
Hi @teoincontatto,

Thanks for reporting!
Do you think you can provide a simple example reproduce it?

**Comment by simonbasle** [comment]
🤦‍♂️The good thing with UOE detection in `SignalLogger#safeLog` was that it covered all bases for classes that are not really compatible with "deep logging" (they look like `Queues` but don't implement the whole API for performance reasons, especially `iterator()`).

That is... until **all** exceptions are swallowed by a concrete logger 😢

I opened a PR to eagerly detect the current culprit (`QueueSubscription`) and pass it to the concrete logger as a `String`, but that means we'll have to be reactive instead of proactive from now on (finding new problematic cases and fixing as we encounter them vs relying on the UOE).

**Comment by simonbasle** [comment]
@teoincontatto please still provide a reproducing snippet here nonetheless.
See if the second part of that message helps you (this is the one you should have seen in logs):
```
UnsupportedOperationException has been raised by the logging framework,
does your log() placement make sense?
eg. 'window(2).log()' instead of 'window(2).flatMap(w -> w.log())'
```

**Comment by teoincontatto** [comment]
This test actually throws the exception:

```
  @Test
  public void test() throws Exception {
    Flux.just(0, 1, 2, 3)
      .window(1)
      .log()
      .subscribe();
  }
```

I've used following pom dependencies:
```
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-slf4j-impl</artifactId>
      <version>2.11.1</version>
    </dependency>
    <dependency>
      <groupId>io.projectreactor</groupId>
      <artifactId>reactor-core</artifactId>
      <version>3.2.5.RELEASE</version>
    </dependency>
```
