### ISSUE TITLE
NullPointerException at SendManyInner.cleanup Followed by Memory Corruption

### ISSUE THREAD

**Issue by ahmedyarub** [reactor/reactor-core#1808]
### Expected behavior
Requests forwarded as-is

### Actual behavior
A task raised an exception. Task: reactor.netty.channel.MonoSendMany$SendManyInner@4ead12f

Stacktrace:
j.l.NullPointerException: null
	at r.n.c.MonoSendMany$SendManyInner.cleanup(MonoSendMany.java:338)
	at r.n.c.MonoSendMany$SendManyInner.run(MonoSendMany.java:322)
	at i.n.u.c.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at i.n.u.c.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405)
	at i.n.c.e.EpollEventLoop.run(EpollEventLoop.java:338)
	at i.n.u.c.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
	at i.n.u.i.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)

Then we would randomly start having memory corruption issues. These are observed by the endpoints where they get mixed-up HTTP methods, URLs, and path variables. For example:
URL: /service/1/transaction/2
HTTP Method: instead of PUT, we get something like /service/5/transaction/6PUT (a method concatenated with a URL from a previous request). This did not happen in previous versions with Spring Boot 2.1.5 and Greenwich.SR1. We still have these versions in production and they don't have any issues.

### Steps to reproduce
Using Spring Cloud Gateway with Greenwich.SR2, Spring Boot 2.1.6 and JDK 11, the application starts and passes all the unit tests. After 8-12 hours we start getting the task errors every couple of hours and randomly (but with very high frequency) corrupted packets.

### Reactor Core version
3.2.10

### JVM version (e.g. `java -version`)
OpenJDK 11.0.3

**Comment by smaldini** [comment]
This is a reactor-netty issue please consider opening it here https://github.com/reactor/reactor-netty
