### ISSUE TITLE
FluxIndexFuseable calls toString() on every element

### ISSUE THREAD

**Issue by dittos** [reactor/reactor-core#1938]
## Steps to Reproduce

`toString()` should not be called on element when using `index` operator.

To demonstrate the behavior I defined a class that throws on `toString()`.

```java
import reactor.core.publisher.Flux;

public class FluxIndexTest {
	public static void main(String[] args) {
		Flux.just(new ThrowsOnToString())
				.index()
				.blockFirst();
	}

	static class ThrowsOnToString {
		@Override
		public String toString() {
			throw new RuntimeException("should not call");
		}
	}
}
```

Running the code throws because `toString()` is called unnecessarily.

```
Exception in thread "main" java.lang.RuntimeException: should not call
	at FluxIndexTest$ThrowsOnToString.toString(FluxIndexTest.java:14)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at reactor.core.publisher.FluxIndexFuseable$IndexFuseableSubscriber.onNext(FluxIndexFuseable.java:133)
	at reactor.core.publisher.FluxJust$WeakScalarSubscription.request(FluxJust.java:99)
	at reactor.core.publisher.FluxIndexFuseable$IndexFuseableSubscriber.request(FluxIndexFuseable.java:174)
	at reactor.core.publisher.BlockingSingleSubscriber.onSubscribe(BlockingSingleSubscriber.java:49)
	at reactor.core.publisher.FluxIndexFuseable$IndexFuseableSubscriber.onSubscribe(FluxIndexFuseable.java:101)
	at reactor.core.publisher.FluxJust.subscribe(FluxJust.java:70)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8134)
	at reactor.core.publisher.Flux.blockFirst(Flux.java:2437)
	at FluxIndexTest.main(FluxIndexTest.java:8)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:93)
		at reactor.core.publisher.Flux.blockFirst(Flux.java:2438)
		... 1 more
```

Does not throw when no fusion.

```java
		Flux.just(new ThrowsOnToString())
				.flatMap(Flux::just)
				.index()
				.blockFirst();
```

## Possible Solution

Generate error message only when `null` is returned from index mapper. (fixed in #1456 but not on fused version)

https://github.com/reactor/reactor-core/blob/628258f644bdddd095e72d1fc81c5d6ac0e3fa12/reactor-core/src/main/java/reactor/core/publisher/FluxIndexFuseable.java#L111-L113

## Your Environment

* Reactor version(s) used: 3.3.0

**Comment by simonbasle** [comment]
looks like the same fix as in #1456 indeed needs to be applied to the fuseable version. The `NullSafeIndexMapper` inner class in `FluxIndex` can be made package private and reused. @dittos would you like to submit a PR?

**Comment by simonbasle** [comment]
on a side note, I assume you only used the `throwing inside toString()` pattern as a way of demonstrating the issue quickly, but that you know it is a very bad idea on any real codebase. I'm pointing that fact out anyway for future visitors 😉 (as there is a lot of code out there that works on the assumption that `toString` is safe to call, including pretty much all logging libraries)

**Comment by dittos** [comment]
OK I'll submit a PR.
