### ISSUE TITLE
Synchronization issue in FluxSwitchMap

### ISSUE THREAD

**Issue by Kindrat** [reactor/reactor-core#1997]
We have a pretty complex pipeline including `Flux.switchMap`. Under high load it is trowing following NPE:

```java
java.lang.NullPointerException: null
	at reactor.core.publisher.FluxSwitchMap$SwitchMapInner.deactivate(FluxSwitchMap.java:518) ~[reactor-core-3.2.8.RELEASE.jar!/:3.2.8.RELEASE]
	at reactor.core.publisher.FluxSwitchMap$SwitchMapMain.onNext(FluxSwitchMap.java:208) ~[reactor-core-3.2.8.RELEASE.jar!/:3.2.8.RELEASE]
	at reactor.core.publisher.FluxFilter$FilterSubscriber.onNext(FluxFilter.java:107) ~[reactor-core-3.2.8.RELEASE.jar!/:3.2.8.RELEASE]
	at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onNext(FluxConcatArray.java:176) ~[reactor-core-3.2.8.RELEASE.jar!/:3.2.8.RELEASE]
	at reactor.core.publisher.FluxFilter$FilterSubscriber.onNext(FluxFilter.java:107) ~[reactor-core-3.2.8.RELEASE.jar!/:3.2.8.RELEASE]
	at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:422) ~[reactor-core-3.2.8.RELEASE.jar!/:3.2.8.RELEASE]
	at reactor.core.publisher.EmitterProcessor$EmitterInner.drainParent(EmitterProcessor.java:569) ~[reactor-core-3.2.8.RELEASE.jar!/:3.2.8.RELEASE]
	at reactor.core.publisher.FluxPublish$PubSubInner.request(FluxPublish.java:567) ~[reactor-core-3.2.8.RELEASE.jar!/:3.2.8.RELEASE]
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:388) ~[reactor-core-3.2.8.RELEASE.jar!/:3.2.8.RELEASE]
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.innerComplete(FluxConcatMap.java:289) ~[reactor-core-3.2.8.RELEASE.jar!/:3.2.8.RELEASE]
	at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onComplete(FluxConcatMap.java:873) ~[reactor-core-3.2.8.RELEASE.jar!/:3.2.8.RELEASE]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:252) ~[reactor-core-3.2.8.RELEASE.jar!/:3.2.8.RELEASE]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:252) ~[reactor-core-3.2.8.RELEASE.jar!/:3.2.8.RELEASE]
	at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onComplete(MonoIgnoreElements.java:81) ~[reactor-core-3.2.8.RELEASE.jar!/:3.2.8.RELEASE]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:252) ~[reactor-core-3.2.8.RELEASE.jar!/:3.2.8.RELEASE]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:252) ~[reactor-core-3.2.8.RELEASE.jar!/:3.2.8.RELEASE]
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onComplete(MonoFlatMapMany.java:248) ~[reactor-core-3.2.8.RELEASE.jar!/:3.2.8.RELEASE]
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.doComplete(FluxPublishOn.java:462) ~[reactor-core-3.2.8.RELEASE.jar!/:3.2.8.RELEASE]
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.checkTerminated(FluxPublishOn.java:501) ~[reactor-core-3.2.8.RELEASE.jar!/:3.2.8.RELEASE]
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:390) ~[reactor-core-3.2.8.RELEASE.jar!/:3.2.8.RELEASE]
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:484) ~[reactor-core-3.2.8.RELEASE.jar!/:3.2.8.RELEASE]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.2.8.RELEASE.jar!/:3.2.8.RELEASE]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.2.8.RELEASE.jar!/:3.2.8.RELEASE]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

```

## Expected Behavior
Concurrent cancel/onNext calls should be handled with proper synchronization.

## Steps to Reproduce
Issue could be reproduce with latest master. However I can reproduce issue only when running test in debug mode from IDE. Stacktrace was from actual docker container in running env.

```java
@Test
    public void shouldProcessNextForCancelledInner() {
        AssertSubscriber<Long> payloadSubscriber = AssertSubscriber.create();
        AssertSubscriber<Void> concurrentSubscriber = AssertSubscriber.create();

        EmitterProcessor<Long> payloadProcessor = EmitterProcessor.create(10_000, false);
        payloadProcessor.switchMap(event -> Flux.just(10L)).subscribe(payloadSubscriber);
        payloadProcessor.onNext(1L);

        Mono.when(
                Flux.range(0, 10_000)
                        .map(Integer::longValue)
                        .flatMap(event -> Mono.fromRunnable(() -> payloadProcessor.onNext(event)))
                        .subscribeOn(Schedulers.elastic()),
                Mono.delay(Duration.ofMillis(25))
                        .then(Mono.fromRunnable(payloadSubscriber::cancel))
        ).subscribe(concurrentSubscriber);

        concurrentSubscriber
                .await(Duration.ofMillis(1000L))
                .assertComplete();
    }
```

## Possible Solution
FluxSwitchMap should check for cancelled inner in FluxSwitchMap#onNext(207):
```java
			SwitchMapInner<R> si = inner;
			if (si != null) {
				si.deactivate();
				si.cancel();
			}
```
```java
			SwitchMapInner<R> si = inner;
			if (si != null && si != CANCELLED_INNER) {
				si.deactivate();
				si.cancel();
			}
```

## Your Environment

* Reactor version(s) used: 
`3.2.8`
* JVM version (`javar -version`):
```
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.3+7, mixed mode)

```
* OS and version (eg `uname -a`): 

`Linux legioner-work 5.3.0-24-generic #26-Ubuntu SMP Thu Nov 14 01:33:18 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by Kindrat** [comment]
@smaldini , any thoughts?

**Comment by simonbasle** [comment]
Sorry this one fell through the cracks.
There is currently some work done on #2554 which should also address this issue.
Closing this one as superseded, but feel free to reopen once #2554 is fixed if the situation is not improved.

**Comment by Kindrat** [comment]
@simonbasle just worth mention - proposed fix works well for over a year now via overridden reactor class
