### ISSUE TITLE
Exception thrown from Stream.yield causes DuplicateOnSubscribeException

### ISSUE THREAD

**Issue by nebhale** [reactor/reactor-core#20]
Currently, allowing an exception to escape from `Stream.yield` (i.e. not `catch`ing `Throwable`) causes a `DuplicateOnSubscribeException` to be thrown, masking the original exception.  The solution to this is to properly implement `Stream.yield` so that it doesn't allow exceptions to escape, but Reactor should behave slightly better in the face of a poor implementation.

```
cloud-foundry-3 cloudfoundry-client.request     POST   /v2/apps
cloud-foundry-3 stream.upload                    onSubscribe(reactor.core.publisher.MonoNext$NextSubscriber@1fd2007b)
cloud-foundry-3 stream.upload                    request(unbounded)
cloud-foundry-2 reactor.core.publisher.SchedulerGroup Unrouted exception
reactor.core.util.Exceptions$DuplicateOnSubscribeException: Spec. Rule 2.12 - Subscriber.onSubscribe MUST NOT be called more than once (based on object equality)
    at reactor.core.util.Exceptions.duplicateOnSubscribeException(Exceptions.java:133) ~[reactor-core-2.5.0.BUILD-20160209.140333-334.jar:na]
    at reactor.core.util.BackpressureUtils.reportSubscriptionSet(BackpressureUtils.java:440) ~[reactor-core-2.5.0.BUILD-20160209.140333-334.jar:na]
    at reactor.core.util.DeferredSubscription.set(DeferredSubscription.java:62) ~[reactor-core-2.5.0.BUILD-20160209.140333-334.jar:na]
    at reactor.core.publisher.FluxPublishOn$PublishOnPipeline.onSubscribe(FluxPublishOn.java:131) ~[reactor-core-2.5.0.BUILD-20160209.140333-334.jar:na]
    at reactor.core.util.EmptySubscription.error(EmptySubscription.java:34) ~[reactor-core-2.5.0.BUILD-20160209.140333-334.jar:na]
    at reactor.core.publisher.FluxYieldingEmitter.subscribe(FluxYieldingEmitter.java:51) ~[reactor-core-2.5.0.BUILD-20160209.140333-334.jar:na]
    at reactor.rx.StreamSource.subscribe(StreamSource.java:69) ~[reactor-stream-2.5.0.BUILD-20160209.172643-328.jar:na]
    at reactor.core.util.ScalarSubscription.trySubscribeScalarMap(ScalarSubscription.java:93) ~[reactor-core-2.5.0.BUILD-20160209.140333-334.jar:na]
    at reactor.core.publisher.FluxFlatMap.subscribe(FluxFlatMap.java:93) ~[reactor-core-2.5.0.BUILD-20160209.140333-334.jar:na]
    at reactor.rx.StreamSource.subscribe(StreamSource.java:69) ~[reactor-stream-2.5.0.BUILD-20160209.172643-328.jar:na]
    at reactor.core.publisher.FluxPublishOn$SourceSubscribeTask.run(FluxPublishOn.java:318) ~[reactor-core-2.5.0.BUILD-20160209.140333-334.jar:na]
    at reactor.core.publisher.SchedulerGroup$TaskSubscriber.onNext(SchedulerGroup.java:1072) [reactor-core-2.5.0.BUILD-20160209.140333-334.jar:na]
    at reactor.core.publisher.SchedulerGroup$TaskSubscriber.onNext(SchedulerGroup.java:1054) [reactor-core-2.5.0.BUILD-20160209.140333-334.jar:na]
    at reactor.core.publisher.WorkQueueProcessor$QueueSubscriberLoop.run(WorkQueueProcessor.java:849) [reactor-core-2.5.0.BUILD-20160209.140333-334.jar:na]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_73]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_73]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_73]
```

**Comment by smaldini** [comment]
Fixed alongside https://github.com/reactor/reactor-core/commit/9655cd1737138dd53f14e659c5f8b82357f15ae8
