### ISSUE TITLE
"FluxSwitchOnFirst has already been cancelled" CancellationException with Spring RSocket responder

### ISSUE THREAD

**Issue by rstoyanchev** [reactor/reactor-core#2080]
Spring Security tests had been running on Dysprosium snapshots and started experiencing this issue, likely as a result of #2076.

In an RSocket channel interaction, a Spring server responder fails to find a matching route and in that scenarios the exception occurs. 

Here is a [repro](https://github.com/eleftherias/rsocket-reactive-exception). The stacktrace is:

```
reactor.core.Exceptions$ErrorCallbackNotImplemented: java.util.concurrent.CancellationException: FluxSwitchOnFirst has already been cancelled
Caused by: java.util.concurrent.CancellationException: FluxSwitchOnFirst has already been cancelled
	at reactor.core.publisher.FluxSwitchOnFirst$SwitchOnFirstMain.subscribe(FluxSwitchOnFirst.java:348) ~[reactor-core-3.3.4.BUILD-SNAPSHOT.jar:3.3.4.BUILD-SNAPSHOT]
	at reactor.core.publisher.Flux.subscribe(Flux.java:8260) ~[reactor-core-3.3.4.BUILD-SNAPSHOT.jar:3.3.4.BUILD-SNAPSHOT]
	at reactor.core.publisher.Flux.subscribeWith(Flux.java:8424) ~[reactor-core-3.3.4.BUILD-SNAPSHOT.jar:3.3.4.BUILD-SNAPSHOT]
	at reactor.core.publisher.Flux.subscribe(Flux.java:8231) ~[reactor-core-3.3.4.BUILD-SNAPSHOT.jar:3.3.4.BUILD-SNAPSHOT]
	at reactor.core.publisher.Flux.subscribe(Flux.java:8158) ~[reactor-core-3.3.4.BUILD-SNAPSHOT.jar:3.3.4.BUILD-SNAPSHOT]
	at reactor.core.publisher.Flux.subscribe(Flux.java:8101) ~[reactor-core-3.3.4.BUILD-SNAPSHOT.jar:3.3.4.BUILD-SNAPSHOT]
	at org.springframework.messaging.rsocket.annotation.support.MessagingRSocket.lambda$handleAndReply$5(MessagingRSocket.java:177) ~[spring-messaging-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.runFinally(FluxDoFinally.java:156) ~[reactor-core-3.3.4.BUILD-SNAPSHOT.jar:3.3.4.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onError(FluxDoFinally.java:132) ~[reactor-core-3.3.4.BUILD-SNAPSHOT.jar:3.3.4.BUILD-SNAPSHOT]
	at reactor.core.publisher.Operators.error(Operators.java:185) ~[reactor-core-3.3.4.BUILD-SNAPSHOT.jar:3.3.4.BUILD-SNAPSHOT]
	at reactor.core.publisher.MonoError.subscribe(MonoError.java:52) ~[reactor-core-3.3.4.BUILD-SNAPSHOT.jar:3.3.4.BUILD-SNAPSHOT]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.3.4.BUILD-SNAPSHOT.jar:3.3.4.BUILD-SNAPSHOT]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4207) ~[reactor-core-3.3.4.BUILD-SNAPSHOT.jar:3.3.4.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onComplete(FluxConcatArray.java:207) ~[reactor-core-3.3.4.BUILD-SNAPSHOT.jar:3.3.4.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxConcatArray.subscribe(FluxConcatArray.java:80) ~[reactor-core-3.3.4.BUILD-SNAPSHOT.jar:3.3.4.BUILD-SNAPSHOT]
	at reactor.core.publisher.Flux.subscribe(Flux.java:8260) ~[reactor-core-3.3.4.BUILD-SNAPSHOT.jar:3.3.4.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxSwitchOnFirst$AbstractSwitchOnFirstMain.onNext(FluxSwitchOnFirst.java:154) ~[reactor-core-3.3.4.BUILD-SNAPSHOT.jar:3.3.4.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123) ~[reactor-core-3.3.4.BUILD-SNAPSHOT.jar:3.3.4.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:203) ~[reactor-core-3.3.4.BUILD-SNAPSHOT.jar:3.3.4.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:203) ~[reactor-core-3.3.4.BUILD-SNAPSHOT.jar:3.3.4.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:203) ~[reactor-core-3.3.4.BUILD-SNAPSHOT.jar:3.3.4.BUILD-SNAPSHOT]
	at reactor.core.publisher.UnicastProcessor.drainRegular(UnicastProcessor.java:240) ~[reactor-core-3.3.4.BUILD-SNAPSHOT.jar:3.3.4.BUILD-SNAPSHOT]
	at reactor.core.publisher.UnicastProcessor.drain(UnicastProcessor.java:312) ~[reactor-core-3.3.4.BUILD-SNAPSHOT.jar:3.3.4.BUILD-SNAPSHOT]
	at reactor.core.publisher.UnicastProcessor.subscribe(UnicastProcessor.java:427) ~[reactor-core-3.3.4.BUILD-SNAPSHOT.jar:3.3.4.BUILD-SNAPSHOT]
	at reactor.core.publisher.Flux.subscribe(Flux.java:8260) ~[reactor-core-3.3.4.BUILD-SNAPSHOT.jar:3.3.4.BUILD-SNAPSHOT]
	at io.rsocket.internal.RateLimitableRequestPublisher.subscribe(RateLimitableRequestPublisher.java:74) ~[rsocket-core-1.0.0-RC6.jar:na]
	at io.rsocket.RSocketResponder.handleStream(RSocketResponder.java:446) ~[rsocket-core-1.0.0-RC6.jar:na]
	at io.rsocket.RSocketResponder.handleChannel(RSocketResponder.java:502) ~[rsocket-core-1.0.0-RC6.jar:na]
	at io.rsocket.RSocketResponder.handleFrame(RSocketResponder.java:315) ~[rsocket-core-1.0.0-RC6.jar:na]
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160) ~[reactor-core-3.3.4.BUILD-SNAPSHOT.jar:3.3.4.BUILD-SNAPSHOT]
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:242) ~[reactor-core-3.3.4.BUILD-SNAPSHOT.jar:3.3.4.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxGroupBy$UnicastGroupedFlux.drainRegular(FluxGroupBy.java:554) ~[reactor-core-3.3.4.BUILD-SNAPSHOT.jar:3.3.4.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxGroupBy$UnicastGroupedFlux.drain(FluxGroupBy.java:630) ~[reactor-core-3.3.4.BUILD-SNAPSHOT.jar:3.3.4.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxGroupBy$UnicastGroupedFlux.subscribe(FluxGroupBy.java:696) ~[reactor-core-3.3.4.BUILD-SNAPSHOT.jar:3.3.4.BUILD-SNAPSHOT]
	at reactor.core.publisher.Flux.subscribe(Flux.java:8260) ~[reactor-core-3.3.4.BUILD-SNAPSHOT.jar:3.3.4.BUILD-SNAPSHOT]
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:188) ~[reactor-core-3.3.4.BUILD-SNAPSHOT.jar:3.3.4.BUILD-SNAPSHOT]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1712) ~[reactor-core-3.3.4.BUILD-SNAPSHOT.jar:3.3.4.BUILD-SNAPSHOT]
	at reactor.core.publisher.MonoProcessor.onNext(MonoProcessor.java:317) ~[reactor-core-3.3.4.BUILD-SNAPSHOT.jar:3.3.4.BUILD-SNAPSHOT]
	at io.rsocket.internal.ClientServerInputMultiplexer.lambda$new$1(ClientServerInputMultiplexer.java:116) ~[rsocket-core-1.0.0-RC6.jar:na]
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160) ~[reactor-core-3.3.4.BUILD-SNAPSHOT.jar:3.3.4.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxGroupBy$GroupByMain.drainLoop(FluxGroupBy.java:380) ~[reactor-core-3.3.4.BUILD-SNAPSHOT.jar:3.3.4.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxGroupBy$GroupByMain.drain(FluxGroupBy.java:316) ~[reactor-core-3.3.4.BUILD-SNAPSHOT.jar:3.3.4.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxGroupBy$GroupByMain.onNext(FluxGroupBy.java:201) ~[reactor-core-3.3.4.BUILD-SNAPSHOT.jar:3.3.4.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114) ~[reactor-core-3.3.4.BUILD-SNAPSHOT.jar:3.3.4.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114) ~[reactor-core-3.3.4.BUILD-SNAPSHOT.jar:3.3.4.BUILD-SNAPSHOT]
	at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:218) ~[reactor-netty-0.9.6.BUILD-SNAPSHOT.jar:0.9.6.BUILD-SNAPSHOT]
	at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:351) ~[reactor-netty-0.9.6.BUILD-SNAPSHOT.jar:0.9.6.BUILD-SNAPSHOT]
	at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:352) ~[reactor-netty-0.9.6.BUILD-SNAPSHOT.jar:0.9.6.BUILD-SNAPSHOT]
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:90) ~[reactor-netty-0.9.6.BUILD-SNAPSHOT.jar:0.9.6.BUILD-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321) ~[netty-codec-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295) ~[netty-codec-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) ~[netty-transport-native-epoll-4.1.45.Final-linux-x86_64.jar:4.1.45.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[netty-transport-native-epoll-4.1.45.Final-linux-x86_64.jar:4.1.45.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-transport-native-epoll-4.1.45.Final-linux-x86_64.jar:4.1.45.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.45.Final.jar:4.1.45.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

The server [handles with switchOnFirst](https://github.com/spring-projects/spring-framework/blob/0d42a1bd7fdd44b000873edd6cbbb35697fddc4a/spring-messaging/src/main/java/org/springframework/messaging/rsocket/annotation/support/MessagingRSocket.java#L133) and in the end, if input stream wasn't subscribed to (e.g. because there was no matching handler), [it subscribes](https://github.com/spring-projects/spring-framework/blob/0d42a1bd7fdd44b000873edd6cbbb35697fddc4a/spring-messaging/src/main/java/org/springframework/messaging/rsocket/annotation/support/MessagingRSocket.java#L154) in order to release the payloads. That's when the exception is raised.

I'm not sure if this is a bug in the Spring RSocket code that was exposed by this change or something that requires a follow-up change to #2076 .

**Comment by rstoyanchev** [comment]
On closer look this appears to be an issue in Spring's RSocket support.

**Comment by simonbasle** [comment]
To give more details, Spring's `MessagingRSocket` attempts to drain and release the inner stream from `switchOnFirst` in a `doFinally`, so _after_ an error from the handler has been propagated through the chain. that later state is now correctly detected by `switchOnFirst`, which reports the main sequence as cancelled (actually due to error terminal signal).

The thing is, this subscription to the flux of buffers is not necessary, because at that point we know said stream wasn't subscribed, so there is no chance a request was sent to the RSocket. Consequently, only the first payload has been transmitted through the wire, and we can simply release that.

**Comment by rstoyanchev** [comment]
https://github.com/spring-projects/spring-framework/issues/24741
