### ISSUE TITLE
Reactor-core not correctly handle BackpressureBuffer

### ISSUE THREAD

**Issue by superleo-cn** [reactor/reactor-core#2244]
I am trying to learn how to use the `onBackpressureBuffer`, after some demos I found out some different behaviors between `reactor-core` and `RxJava`.

Actually, the `RxJava` expected what I intended.

```java

    // reactor-core 
    @Test
    public void test_onBackpressureBufferReactor() throws InterruptedException {
        Flux.interval(Duration.of(10, ChronoUnit.MILLIS))  // every 10ms to emit
                .onBackpressureBuffer(10)                              //the buffer sie is 10
                .parallel()
                .runOn(reactor.core.scheduler.Schedulers.parallel())
                .subscribe(
                        i -> {
                            System.out.println(Thread.currentThread().getName() + " " + i);
                            try {
                                // sleep 1s to slow down the velocity of processing
                                Thread.sleep(1000);
                            } catch (Exception e) {
                                System.out.println(e.getMessage());
                            }
                        },
                        System.out::println
                );
        TimeUnit.MINUTES.sleep(10);
    }

```
when I run it, it keeps running without any exception. 

```log
15:49:42.409 [main] DEBUG reactor.util.Loggers$LoggerFactory - Using Slf4j logging framework
parallel-1 0
parallel-2 1
parallel-5 4
parallel-4 3
parallel-8 7
parallel-3 2
parallel-10 9
parallel-12 11
parallel-11 10
...
```

But once I use the RxJava instead as below:

```java
    // rx
    @Test
    public void test_onBackpressureBufferRx() throws InterruptedException {
        Observable.interval(10, TimeUnit.MILLISECONDS)
                .onBackpressureBuffer(10)
                .observeOn(Schedulers.newThread())
                .subscribe(
                        i -> {
                            System.out.println(i);
                            try {
                                Thread.sleep(1000);
                            } catch (Exception e) {
                                System.out.println(e.getMessage());
                            }
                        });
        TimeUnit.MINUTES.sleep(10);
    }


```
I can get the errors from console:

```log
0
1
Exception in thread "RxNewThreadScheduler-1" java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:57)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: rx.exceptions.OnErrorNotImplementedException: Overflowed buffer
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.checkTerminated(OperatorObserveOn.java:273)
	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:216)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	... 7 more
Caused by: rx.exceptions.MissingBackpressureException: Overflowed buffer
	at rx.BackpressureOverflow$Error.mayAttemptDrop(BackpressureOverflow.java:107)
	at rx.internal.operators.OperatorOnBackpressureBuffer$BufferSubscriber.assertCapacity(OperatorOnBackpressureBuffer.java:191)
	at rx.internal.operators.OperatorOnBackpressureBuffer$BufferSubscriber.onNext(OperatorOnBackpressureBuffer.java:147)
	at rx.internal.operators.OnSubscribeTimerPeriodically$1.call(OnSubscribeTimerPeriodically.java:52)
	at rx.internal.schedulers.SchedulePeriodicHelper$1.call(SchedulePeriodicHelper.java:72)
	at rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$2.call(EventLoopsScheduler.java:189)
	... 8 more


```

Please let me know if I missed anything or something is incorrect.

* Reactor version(s) used: 3.3.4
* Other relevant libraries versions: netty 4.1.48
* JVM version (`javar -version`):  
```
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)
```
* OS and version (eg `uname -a`): Darwin bogon 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64

**Comment by simonbasle** [comment]
you're not comparing strictly equivalent codes: not using `parallel()` in RxJava, the `publishOn(Schedulers.newThread())` will still result in a single thread being used (and you're using the `Observable` class rather than the `Flowable` class).
