### ISSUE TITLE
Flux.timeout() intermittently deadlocked if timeout is 0

### ISSUE THREAD

**Issue by stepanv** [reactor/reactor-core#2260]
When setting `Flux.timeout()` with duration `0`, the flux may end up in a deadlock situation, not able to return or throw an expcetion when calling `Flux.block()`.
Note that if the duration is non-zero (e.g., `Duration.ofMillis(1)`) the problem does not manifest.

## Expected Behavior

The `Flux.block()` should return or throw an exception.

## Actual Behavior

The `Flux.block()` may intermittently never return or throw an exception

## Steps to Reproduce

```java
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import reactor.test.StepVerifier;

import java.time.Duration;
import java.util.List;

public class TestAlone {

    @Test
    void minimal() {
        // Given
        Mono<List<String>> listMono = Flux.just("test-item")
                .delayElements(Duration.ofSeconds(10))
                .timeout(
                        Duration.ofMillis(0),
                        Mono.just("TIMEOUT")
                )
                .doOnEach(resultSignal -> System.out.println("4: " + resultSignal))
                .doOnNext(it2 -> System.out.println("5: " + it2))
                .doFinally(signalType -> System.out.println("6: " + signalType))
                .collectList();
        // When
        StepVerifier.create(listMono)
                // Then
                .assertNext(Assertions::assertNotNull)
                .expectComplete()
                .verify(); // line 30
    }

    @Test
    void multiple() {
        for (int i = 0; i < 10000; i++) {
            System.out.format("iteration %04d > %n", i);
            minimal(); // line 37
            System.out.println();
        }
    }
}
```
The output may look like: 
```
...

iteration 0125 > 
4: doOnEach_onNext(TIMEOUT)
5: TIMEOUT
4: onComplete()
6: onComplete

iteration 0126 > 
4: doOnEach_onNext(TIMEOUT)
5: TIMEOUT
4: onComplete()
6: onComplete

iteration 0127 > 
4: doOnEach_onNext(TIMEOUT)
5: TIMEOUT
```
As one can see, the Flux deadlocked at iteration 127 and never returned.
```
"main" #1 prio=5 os_prio=31 cpu=4304.60ms elapsed=5.16s tid=0x00007f9c10813800 nid=0x2803 runnable  [0x0000700002613000]
   java.lang.Thread.State: RUNNABLE
	at reactor.test.DefaultStepVerifierBuilder$DefaultVerifySubscriber.pollTaskEventOrComplete(DefaultStepVerifierBuilder.java:1676)
	at reactor.test.DefaultStepVerifierBuilder$DefaultVerifySubscriber.verify(DefaultStepVerifierBuilder.java:1261)
	at reactor.test.DefaultStepVerifierBuilder$DefaultStepVerifier.verify(DefaultStepVerifierBuilder.java:825)
	at reactor.test.DefaultStepVerifierBuilder$DefaultStepVerifier.verify(DefaultStepVerifierBuilder.java:816)
	at TestAlone.minimal(TestAlone.java:30)
	at TestAlone.multiple(TestAlone.java:37)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11.0.4/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11.0.4/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.4/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@11.0.4/Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor$$Lambda$127/0x000000080011a440.apply(Unknown Source)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall$$Lambda$128/0x000000080011ac40.apply(Unknown Source)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
...
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)


```
## Your Environment

* Reactor version(s) used: `3.3.7.RELEASE`
* JVM version (`javar -version`): 
```
java version "11.0.4" 2019-07-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.4+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.4+10-LTS, mixed mode)
```

* OS and version (eg `uname -a`):
```
Darwin ... 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; ...
```

**Comment by simonbasle** [comment]
May I ask why you end up using a 0-duration timeout ? Are you expecting that this will disable the timeout? In that case, having the operator be a no-op on `Duration.ZERO` and documenting that would probably be a better alternative?

Note that it seems using the `Publisher` based version with `Mono.empty()` doesn't trigger hanging. As in:
```
Flux.just("test-item")
    .delayElements(Duration.ofSeconds(10))
    .timeout(
        Mono.empty(),
		v -> Mono.empty(),
		Mono.just("TIMEOUT"))
```

**Comment by stepanv** [comment]
@simonbasle, I guess either way; `Duration.ZERO` could be timeout disabled OR that timeout happens always. 
I hit this issue while writing a test where I wanted to "test" that I'm getting the flux from the `timeout()` handler - instead of delaying for as short as possible duration, I tried 0 and most of the cases it works. But not always.
Anyway, for `Duration.ZERO`, it should either fail or do something well defined, right?
Thanks!

**Comment by stepanv** [comment]
In the same time, if the timeout value is externalized, it's quite natural that a user could try to set a negative value or a zero. To disable the timeout with the former I guess, and to timeout always with latter.

**Comment by stepanv** [comment]
actually, I'm experiencing the deadlock even with `Duration.ofMillis(1)` but with a slightly more complicated Flux

**Comment by stepanv** [comment]
Thanks, with `3.3.9.RELEASE`, it works flawlessly!

**Comment by bsideup** [comment]
@stepanv thanks for trying! 👍
