### ISSUE TITLE
NPE: The subscriber receive a null event.value

### ISSUE THREAD

**Issue by singgel** [reactor/reactor-core#2315]
## Expected Behavior
No exception

## Actual Behavior
Throwing exception
```
Exception in thread "TopicProcessor-1" java.lang.NullPointerException: e
	at java.util.Objects.requireNonNull(Objects.java:228)
	at reactor.util.concurrent.SpscArrayQueue.offer(SpscArrayQueue.java:49)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.onNext(FluxPublishOn.java:226)
	at reactor.core.publisher.FluxOnBackpressureDrop$DropSubscriber.onNext(FluxOnBackpressureDrop.java:122)
	at reactor.core.publisher.TopicProcessor$TopicInner.run(TopicProcessor.java:489)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
org.apache.catalina.connector.ClientAbortException: java.io.IOException: Broken pipe
	at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:356)
	at org.apache.catalina.connector.OutputBuffer.flushByteBuffer(OutputBuffer.java:825)
	at org.apache.catalina.connector.OutputBuffer.append(OutputBuffer.java:730)
	at org.apache.catalina.connector.OutputBuffer.writeBytes(OutputBuffer.java:391)
	at org.apache.catalina.connector.OutputBuffer.write(OutputBuffer.java:369)
	at org.apache.catalina.connector.CoyoteOutputStream.write(CoyoteOutputStream.java:96)
        ......
```

## Steps to Reproduce
When the client actively disconnects during Tomcat response
```$java
while (nextSequence <= availableSequence) {
    event = processor.ringBuffer.get(nextSequence);

        //if bounded and out of capacity
        while (!unbounded && getAndSub(pendingRequest, 1L) ==
                        0) {
            //Todo Use WaitStrategy?
            if(!running.get() || processor.isTerminated()){
                WaitStrategy.alert();
            }
            LockSupport.parkNanos(1L);
        }

        //It's an unbounded subscriber or there is enough capacity to process the signal
        // TODO: add a check？
        subscriber.onNext(event.value);
        nextSequence++;

}
```

## Reactor Core version
3.2.8.RELEASE

## Your Environment

* Other relevant libraries versions: tomcat-embed-core-8.5.32
* JVM version : 1.8.0_45-b14
* OS : Ubuntu 4.4.0-178-generic

**Comment by simonbasle** [comment]
Can you provide more details ? The code above isn't a proper reproducer case (which needs to be a fully executable snippet with only reactor-core as a dependency). You're also using a version that is almost 1.5 years old. Have you tried with the latest 3.2 release?

**Comment by singgel** [comment]
Thank you for your reply, I will try to upgrade reactor-core dependency to the latest 3.2 release or 3.3 more, continue to observe, any follow-up progress will be restored in the comments below, thank you very much
