### ISSUE TITLE
RetryWhen with Retry.fixedDelay may fail with Spec Rule 1.3

### ISSUE THREAD

**Issue by jvalkeal** [reactor/reactor-core#2488]
This is with latest and greatest with boot 2.4.0.

In a Spring Statemachine I'm using `EmitterProcessor` via Sinks api as `Sinks.many().multicast().onBackpressureBuffer(Queues.SMALL_BUFFER_SIZE, false)`.

Javadocs mentions that I could sleep to go back to original behaviour and then I don't have an issue:
```
while (triggerSink.tryEmitNext(tqi).isFailure()) {
  LockSupport.parkNanos(10);
}
```

However this naturally gets `blockhound` to complain about blocking operation so I've been trying to find a non-blocking alternative. My idea was an attempt to try emit and then retry few times with a delay. If it magically goes through and doesn't error with serial access, good and otherwise I'd propagate with some error handling fu.

```
.flatMap(tqi -> Mono.fromRunnable(() -> {
    triggerSink.emitNext(tqi, EmitFailureHandler.FAIL_FAST);
  })
  .retryWhen(Retry.fixedDelay(10, Duration.ofNanos(10)))
  )
```

However it looks like when trying to use `retryWhen` with `Retry.fixedDelay`, reactor internally may get into same problem I'm just trying to overcome with retrying emit operation. I was able to come up a test outside of a statemachine to show this same behaviour and pushed project to https://github.com/jvalkeal/randomstuff/tree/master/reactor-retrywhen-issue:

Running a test there doesn't always fail and may actually return proper error(`RetryExhaustedException`) but when you run it many times, you should be able to see it fail with:

```
org.opentest4j.AssertionFailedError: 
Expecting:
 <java.lang.AssertionError: VerifySubscriber timed out on reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber@1cd9f0f1>
to be equal to:
 <null>
but was not.
```

Then you'd be able to find this spesific error logged by reactor itself:

```
13:40:07.880 [parallel-2] ERROR reactor.core.publisher.Operators - Operator called default onErrorDropped
reactor.core.publisher.Sinks$EmissionException: Spec. Rule 1.3 - onSubscribe, onNext, onError and onComplete signaled to a Subscriber MUST be signaled serially.
	at reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:56)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onError(FluxRetryWhen.java:191)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onError(FluxPeek.java:221)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:841)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:607)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:587)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onError(FluxFlatMap.java:450)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:415)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210)
	at reactor.core.publisher.FluxArray$ArraySubscription.slowPath(FluxArray.java:127)
	at reactor.core.publisher.FluxArray$ArraySubscription.request(FluxArray.java:100)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:144)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:370)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onSubscribe(FluxPeekFuseable.java:178)
	at reactor.core.publisher.FluxArray.subscribe(FluxArray.java:53)
	at reactor.core.publisher.FluxArray.subscribe(FluxArray.java:59)
	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.resubscribe(FluxRetryWhen.java:215)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenOtherSubscriber.onNext(FluxRetryWhen.java:268)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.innerNext(FluxConcatMap.java:281)
	at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:860)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1784)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1784)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:148)
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1784)
	at reactor.core.publisher.MonoIgnoreThen$ThenAcceptInner.onNext(MonoIgnoreThen.java:305)
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:119)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

As `Retry.fixedDelay` fails internally with `RetryWhen` I can't find a way to handle it within user code anymore. If I understood this correctly, retry feature just stops.

**Comment by bsideup** [comment]
FYI I was able to dramatically simplify the reproducer to this:
```java
AtomicInteger counter = new AtomicInteger();
Flux.just("hello")
		.doOnNext(m -> {
			if (counter.incrementAndGet() < 5) {
				throw new RuntimeException("WTF");
			}
		})
		.retryWhen(Retry.fixedDelay(10, Duration.ofNanos(1)))
		.blockFirst(Duration.ofSeconds(2));
```

now looking into the cause...

**Comment by jvalkeal** [comment]
@bsideup show off :)

**Comment by kushagraThapar** [comment]
@jvalkeal @bsideup - I am seeing the same issue with `Flux.repeatWhen` -> 

```
2021-01-26T18:26:28.4813099Z reactor.core.publisher.Sinks$EmissionException: Spec. Rule 1.3 - onSubscribe, onNext, onError and onComplete signaled to a Subscriber MUST be signaled serially.
2021-01-26T18:26:28.4814704Z 	at reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:56) ~[reactor-core-3.4.1.jar:?]
2021-01-26T18:26:28.4815763Z 	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
2021-01-26T18:26:28.4816642Z Assembly trace from producer [reactor.core.publisher.FluxCallable] :
2021-01-26T18:26:28.4817488Z 	reactor.core@3.4.1/reactor.core.publisher.Mono.flux(Mono.java:2910)
2021-01-26T18:26:28.4819012Z 	com.azure.cosmos@4.12.0-beta.1/com.azure.cosmos.implementation.directconnectivity.StoreReader.readMultipleReplicasInternalAsync(StoreReader.java:356)
2021-01-26T18:26:28.4820078Z Error has been observed at the following site(s):
2021-01-26T18:26:28.4821145Z 	|_  â‡¢ reactor.core@3.4.1/reactor.core.publisher.Mono.flux(Mono.java:2910)
2021-01-26T18:26:28.4822052Z Stack trace:
2021-01-26T18:26:28.4823290Z 		at reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:56) ~[reactor-core-3.4.1.jar:?]
2021-01-26T18:26:28.4872345Z 		at reactor.core.publisher.FluxRepeatWhen$RepeatWhenMainSubscriber.onComplete(FluxRepeatWhen.java:163) ~[reactor-core-3.4.1.jar:?]
2021-01-26T18:26:28.4875181Z 		at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:845) ~[reactor-core-3.4.1.jar:?]
2021-01-26T18:26:28.4877042Z 		at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:607) ~[reactor-core-3.4.1.jar:?]
2021-01-26T18:26:28.4878835Z 		at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:587) ~[reactor-core-3.4.1.jar:?]
2021-01-26T18:26:28.4880171Z 		at reactor.core.publisher.FluxFlatMap$FlatMapMain.onComplete(FluxFlatMap.java:464) ~[reactor-core-3.4.1.jar:?]
2021-01-26T18:26:28.4881495Z 		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1785) ~[reactor-core-3.4.1.jar:?]
2021-01-26T18:26:28.4882812Z 		at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:178) ~[reactor-core-3.4.1.jar:?]
2021-01-26T18:26:28.4884198Z 		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onComplete(FluxPeekFuseable.java:277) ~[reactor-core-3.4.1.jar:?]
2021-01-26T18:26:28.4885562Z 		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1785) ~[reactor-core-3.4.1.jar:?]
2021-01-26T18:26:28.4886844Z 		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151) ~[reactor-core-3.4.1.jar:?]
2021-01-26T18:26:28.4888146Z 		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1784) ~[reactor-core-3.4.1.jar:?]
2021-01-26T18:26:28.4889455Z 		at reactor.core.publisher.MonoSingle$SingleSubscriber.onComplete(MonoSingle.java:178) ~[reactor-core-3.4.1.jar:?]
2021-01-26T18:26:28.4890927Z 		at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:845) ~[reactor-core-3.4.1.jar:?]
2021-01-26T18:26:28.4892683Z 		at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:607) ~[reactor-core-3.4.1.jar:?]
2021-01-26T18:26:28.4894422Z 		at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:587) ~[reactor-core-3.4.1.jar:?]
2021-01-26T18:26:28.4895780Z 		at reactor.core.publisher.FluxFlatMap$FlatMapMain.onComplete(FluxFlatMap.java:464) ~[reactor-core-3.4.1.jar:?]
2021-01-26T18:26:28.4897227Z 		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:150) ~[reactor-core-3.4.1.jar:?]
2021-01-26T18:26:28.4898987Z 		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1785) ~[reactor-core-3.4.1.jar:?]
2021-01-26T18:26:28.4900453Z 		at reactor.core.publisher.FluxCallable.subscribe(FluxCallable.java:49) ~[reactor-core-3.4.1.jar:?]
2021-01-26T18:26:28.4902239Z 		at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62) ~[reactor-core-3.4.1.jar:?]
2021-01-26T18:26:28.4903587Z 		at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:54) ~[reactor-core-3.4.1.jar:?]
2021-01-26T18:26:28.4935008Z 		at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62) ~[reactor-core-3.4.1.jar:?]
2021-01-26T18:26:28.4936644Z 		at reactor.core.publisher.FluxRepeatWhen$RepeatWhenMainSubscriber.resubscribe(FluxRepeatWhen.java:183) ~[reactor-core-3.4.1.jar:?]
2021-01-26T18:26:28.4938350Z 		at reactor.core.publisher.FluxRepeatWhen$RepeatWhenOtherSubscriber.onNext(FluxRepeatWhen.java:238) ~[reactor-core-3.4.1.jar:?]
2021-01-26T18:26:28.4939757Z 		at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:711) ~[reactor-core-3.4.1.jar:?]
2021-01-26T18:26:28.4941085Z 		at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:587) ~[reactor-core-3.4.1.jar:?]
2021-01-26T18:26:28.4942404Z 		at reactor.core.publisher.FluxFlatMap$FlatMapInner.onNext(FluxFlatMap.java:993) ~[reactor-core-3.4.1.jar:?]
2021-01-26T18:26:28.4943745Z 		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1766) ~[reactor-core-3.4.1.jar:?]
2021-01-26T18:26:28.4945102Z 		at reactor.core.publisher.MonoDelayUntil$DelayUntilCoordinator.signal(MonoDelayUntil.java:261) ~[reactor-core-3.4.1.jar:?]
2021-01-26T18:26:28.4946513Z 		at reactor.core.publisher.MonoDelayUntil$DelayUntilTrigger.onComplete(MonoDelayUntil.java:341) ~[reactor-core-3.4.1.jar:?]
2021-01-26T18:26:28.4948078Z 		at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:120) [reactor-core-3.4.1.jar:?]
2021-01-26T18:26:28.4949369Z 		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) [reactor-core-3.4.1.jar:?]
2021-01-26T18:26:28.4950610Z 		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) [reactor-core-3.4.1.jar:?]
2021-01-26T18:26:28.4952029Z 		at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
2021-01-26T18:26:28.4956814Z 		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
2021-01-26T18:26:28.4957954Z 		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
2021-01-26T18:26:28.4958915Z 		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
2021-01-26T18:26:28.4959767Z 		at java.lang.Thread.run(Thread.java:834) [?:?]

```

I see your PR - https://github.com/reactor/reactor-core/pull/2499 but I am wondering, if the same code change needs to be made here : https://github.com/reactor/reactor-core/blob/master/reactor-core/src/main/java/reactor/core/publisher/FluxRepeatWhen.java#L162

Since the race condition can also happen for this operator. Please refer to above stack trace for details. Let me know if you would like me to create a new issue.

**Comment by simonbasle** [comment]
@kushagraThapar it might be the case, yes. At least it warrants some investigation. Can you open an issue referencing this one?

**Comment by kushagraThapar** [comment]
@simonbasle - created one here - https://github.com/reactor/reactor-core/issues/2579
Let's continue the conversation on the newly created issue, thanks!
