### ISSUE TITLE
Conflate stack when multiple doOnNext() or similair are used subsequently

### ISSUE THREAD

**Issue by dfeist** [reactor/reactor-core#256]
Where multiple simple `doOnNext()` operators are used in a single stream this stack is produced.  Look at conflating this to minimize stack, especially in moe complex streams where stack gets deep  very quickly.  

```
  at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:166)
    at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:166)
    at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:166)
    at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:166)
    at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:166)
    at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:166)
    at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:166)
```

```
	at reactor.core.publisher.FluxPeek.subscribe(FluxPeek.java:89)
	at reactor.core.publisher.FluxPeek.subscribe(FluxPeek.java:89)
	at reactor.core.publisher.FluxPeek.subscribe(FluxPeek.java:89)
	at reactor.core.publisher.FluxPeek.subscribe(FluxPeek.java:89)
	at reactor.core.publisher.FluxPeek.subscribe(FluxPeek.java:89)
	at reactor.core.publisher.FluxPeek.subscribe(FluxPeek.java:89)
	at reactor.core.publisher.FluxPeek.subscribe(FluxPeek.java:89)
	at reactor.core.publisher.FluxPeek.subscribe(FluxPeek.java:89)
```

**Comment by smaldini** [comment]
We will rather work at first on providing hints via debugging tools given we have in place the new introspection API in 3.1. So I'm going to close this one for now and will track tooling support in #416.
