### ISSUE TITLE
StackOverflowError on Mono + materialize + filter

### ISSUE THREAD

**Issue by robotmrv** [reactor/reactor-core#2674]
Test that passes with 3.3.15.RELEASE now throws StackOverflowError 
```
java.lang.StackOverflowError
	at reactor.core.publisher.Operators.onNextError(Operators.java:819)
	at reactor.core.publisher.FluxFilter$FilterSubscriber.onNext(FluxFilter.java:102)
	at reactor.core.publisher.MonoMaterialize$MaterializeSubscriber.drain(MonoMaterialize.java:132)
	at reactor.core.publisher.MonoMaterialize$MaterializeSubscriber.request(MonoMaterialize.java:144)
	at reactor.core.publisher.FluxFilter$FilterSubscriber.onNext(FluxFilter.java:117)
	at reactor.core.publisher.MonoMaterialize$MaterializeSubscriber.drain(MonoMaterialize.java:132)
	at reactor.core.publisher.MonoMaterialize$MaterializeSubscriber.request(MonoMaterialize.java:144)
	at reactor.core.publisher.FluxFilter$FilterSubscriber.onNext(FluxFilter.java:117)
	at reactor.core.publisher.MonoMaterialize$MaterializeSubscriber.drain(MonoMaterialize.java:132)
	at reactor.core.publisher.MonoMaterialize$MaterializeSubscriber.request(MonoMaterialize.java:144)
	at reactor.core.publisher.FluxFilter$FilterSubscriber.onNext(FluxFilter.java:117)
```
## Expected Behavior

test should pass
## Actual Behavior

test throws StackOverflowError 

## Steps to Reproduce

```java
Mono.error(new RuntimeException("boom"))
        .materialize()
        .filter(signal -> !signal.isOnError())
        .as(StepVerifier::create)
        .expectSubscription()
        .expectComplete()
        .verify();
```

## Possible Solution

--
## Your Environment

* Reactor version(s) used: 3.4.4
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`java -version`): 
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.265-b01, mixed mode)
* OS and version (eg `uname -a`): Windows 10

**Comment by simonbasle** [comment]
Bugged since 3.4.0, introduced by `MonoMaterialize` dedicated implementation from #2456.
Root cause: the `filter` subscriber (shared with the `Flux` version) drops the signal as it doesn't pass the predicate. Internally, in that case, it `request(1)` more from the materialize.

That's where trouble starts: `MonoMaterializeSubscriber` calls `onNext`+`onComplete` from inside its `request` method without checking if it has been requested once before, so that second request triggers the onNext again and again... Infinite recursion! 😱

**Comment by simonbasle** [comment]
`has-workaround`: insert `.flux().limitRequest(1)` between the `.materialize()` and the `.filter(...)`.

**Comment by simonbasle** [comment]
possible fix: null out the `signalToReplayUponFirstRequest` earlier, before `actual.onNext` rather than at [line 134](https://github.com/reactor/reactor-core/blob/765bfe8fab594a4a2a03d010e74c53a83054b6b3/reactor-core/src/main/java/reactor/core/publisher/MonoMaterialize.java#L134).

Alternatively, prevent re-entrency in `request` by checking `requested == true`.
