### ISSUE TITLE
ErrorCallbackNotImplemented with doOnError

### ISSUE THREAD

**Issue by matejsp** [reactor/reactor-core#2677]
There is an issue with doOnError. When called we are also getting no callback not implemented error.
Reactor version(s) used: 3.4.4 and 3.4.5

However it works in 3.3.16.RELEASE.

## Expected Behavior
Error is handled

## Actual Behavior
Error is handled, but with additional print "reactor.core.Exceptions$ErrorCallbackNotImplemented"

```
[2021-04-14 06:42:34.370] [admins-MBP] [main] ERROR reactor.core.publisher.Operators - Operator called default onErrorDropped
reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.IllegalArgumentException: asd
Caused by: java.lang.IllegalArgumentException: asd
	at net.iconomi.router.test.ErrorTest.lambda$onErrorTest$0(ErrorTest.java:13)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onSubscribe(FluxPeekFuseable.java:462)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4099)
	at reactor.core.publisher.Mono.subscribeWith(Mono.java:4214)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3931)
	at net.iconomi.router.test.ErrorTest.onErrorTest(ErrorTest.java:16)
```

```java
@Test
void reproCase() {

            Mono.just("XXXXX")
                .doOnSubscribe(subscription -> {
                    throw new IllegalArgumentException("asd");
                })
                .doOnError(IllegalArgumentException.class, a -> System.out.println("handled: " + a.getMessage()))
                .subscribe();

            Mono.error(IllegalArgumentException::new)
                    .doOnError(IllegalArgumentException.class, a -> System.out.println("handled: " + a.getMessage()))
                    .subscribe();

            Mono.error(IllegalArgumentException::new)
                    .doOnError(IllegalArgumentException.class, a -> System.out.println("handled: " + a.getMessage()))
                    .onErrorStop()
                    .subscribe();

}
```

**Comment by simonbasle** [comment]
`subscribe()` is a convenience, but in reality it is almost always better to provide explicit handlers at least for errors.

The behavior around `subscribe()` has slightly changed in 3.4.0 (see #2176): previously it would be stricter and throw, now it logs the `ErrorCallbackNotImplementedException`.
