### ISSUE TITLE
FluxSwitchMapStressTest flaky on CI

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#2682]
The test seems to fail from time to time, mainly on CI:

```
(ETA:   00:00:05) (Sample Rate: 37.59 M/sec) (Tests: 1 of 28) (Forks:  1 of 112) (Iterations:  1 of 672; 1 passed, 0 failed, 0 soft errs, 0 hard errs) 
(ETA:   00:03:15) (Sample Rate: 285.46 K/sec) (Tests: 8 of 28) (Forks:  8 of 112) (Iterations: 48 of 672; 48 passed, 0 failed, 0 soft errs, 0 hard errs) 
(ETA:   00:04:19) (Sample Rate: 183.30 K/sec) (Tests: 12 of 28) (Forks: 12 of 112) (Iterations: 70 of 672; 70 passed, 0 failed, 0 soft errs, 0 hard errs) 
(ETA:   00:03:56) (Sample Rate: 344.76 K/sec) (Tests: 18 of 28) (Forks: 18 of 112) (Iterations: 108 of 672; 108 passed, 0 failed, 0 soft errs, 0 hard errs) 
(ETA:   00:03:35) (Sample Rate: 463.57 K/sec) (Tests: 25 of 28) (Forks: 25 of 112) (Iterations: 147 of 672; 147 passed, 0 failed, 0 soft errs, 0 hard errs) 
(ETA:   00:03:16) (Sample Rate: 472.88 K/sec) (Tests: 27 of 28) (Forks: 32 of 112) (Iterations: 187 of 672; 187 passed, 0 failed, 0 soft errs, 0 hard errs) 
(ETA:   00:03:02) (Sample Rate: 418.13 K/sec) (Tests: 27 of 28) (Forks: 38 of 112) (Iterations: 223 of 672; 223 passed, 0 failed, 0 soft errs, 0 hard errs) 
(ETA:   00:02:51) (Sample Rate: 415.89 K/sec) (Tests: 27 of 28) (Forks: 44 of 112) (Iterations: 259 of 672; 259 passed, 0 failed, 0 soft errs, 0 hard errs) 
(ETA:   00:02:28) (Sample Rate: 481.26 K/sec) (Tests: 27 of 28) (Forks: 51 of 112) (Iterations: 304 of 672; 304 passed, 0 failed, 0 soft errs, 0 hard errs) 
(ETA:   00:02:21) (Sample Rate: 473.20 K/sec) (Tests: 28 of 28) (Forks: 56 of 112) (Iterations: 331 of 672; 331 passed, 0 failed, 0 soft errs, 0 hard errs) 

  [FAILED] reactor.core.publisher.FluxSwitchMapStressTest.RequestAndProduceStressTest1
    (fork: #1, iteration #0, JVM args: [-XX:+UnlockDiagnosticVMOptions, -XX:+WhiteBoxAPI, -XX:-RestrictContended, -Dfile.encoding=UTF-8, -Duser.country, -Duser.language=en, -Duser.variant, -Xint])
  Observed state   Occurrences   Expectation  Interpretation                                              
          200, 1         2,806    ACCEPTABLE  Should produced and remaining requested result in total r...
          220, 0             1     FORBIDDEN  No default case provided, assume FORBIDDEN                  

(ETA:   00:02:21) (Sample Rate: 458.22 K/sec) (Tests: 28 of 28) (Forks: 57 of 112) (Iterations: 337 of 672; 336 passed, 1 failed, 0 soft errs, 0 hard errs) 
(ETA:   00:02:17) (Sample Rate: 411.74 K/sec) (Tests: 28 of 28) (Forks: 61 of 112) (Iterations: 361 of 672; 360 passed, 1 failed, 0 soft errs, 0 hard errs) 
(ETA:   00:02:07) (Sample Rate: 381.17 K/sec) (Tests: 28 of 28) (Forks: 65 of 112) (Iterations: 388 of 672; 387 passed, 1 failed, 0 soft errs, 0 hard errs) 
(ETA:   00:02:01) (Sample Rate: 356.36 K/sec) (Tests: 28 of 28) (Forks: 69 of 112) (Iterations: 409 of 672; 408 passed, 1 failed, 0 soft errs, 0 hard errs) 
(ETA:   00:01:53) (Sample Rate: 330.22 K/sec) (Tests: 28 of 28) (Forks: 73 of 112) (Iterations: 433 of 672; 432 passed, 1 failed, 0 soft errs, 0 hard errs) 
(ETA:   00:01:44) (Sample Rate: 309.09 K/sec) (Tests: 28 of 28) (Forks: 77 of 112) (Iterations: 457 of 672; 456 passed, 1 failed, 0 soft errs, 0 hard errs) 
(ETA:   00:01:34) (Sample Rate: 290.45 K/sec) (Tests: 28 of 28) (Forks: 81 of 112) (Iterations: 481 of 672; 480 passed, 1 failed, 0 soft errs, 0 hard errs) 
(ETA:   00:01:15) (Sample Rate: 283.08 K/sec) (Tests: 28 of 28) (Forks: 87 of 112) (Iterations: 517 of 672; 516 passed, 1 failed, 0 soft errs, 0 hard errs) 
(ETA:   00:00:59) (Sample Rate: 275.15 K/sec) (Tests: 28 of 28) (Forks: 92 of 112) (Iterations: 550 of 672; 549 passed, 1 failed, 0 soft errs, 0 hard errs) 
(ETA:   00:00:39) (Sample Rate: 285.24 K/sec) (Tests: 28 of 28) (Forks: 99 of 112) (Iterations: 589 of 672; 588 passed, 1 failed, 0 soft errs, 0 hard errs) 
(ETA:   00:00:21) (Sample Rate: 294.48 K/sec) (Tests: 28 of 28) (Forks: 105 of 112) (Iterations: 627 of 672; 626 passed, 1 failed, 0 soft errs, 0 hard errs) 
(ETA:   00:00:02) (Sample Rate: 318.29 K/sec) (Tests: 28 of 28) (Forks: 111 of 112) (Iterations: 666 of 672; 665 passed, 1 failed, 0 soft errs, 0 hard errs) 


RUN COMPLETE.

Exception in thread "main" java.lang.AssertionError: TEST FAILURES: 
RUN RESULTS:
reactor.core.publisher.FluxSwitchMapStressTest.RequestAndProduceStressTest1 [-XX:+UnlockDiagnosticVMOptions, -XX:+WhiteBoxAPI, -XX:-RestrictContended, -Dfile.encoding=UTF-8, -Duser.country, -Duser.language=en, -Duser.variant, -Xint]: Observed forbidden state: 220, 0 (No default case provided, assume FORBIDDEN)

	at org.openjdk.jcstress.infra.grading.ExceptionReportPrinter.work(ExceptionReportPrinter.java:63)
	at org.openjdk.jcstress.JCStress.parseResults(JCStress.java:109)
	at org.openjdk.jcstress.JCStress.run(JCStress.java:94)
	at org.openjdk.jcstress.Main.main(Main.java:60)
------------------------------------------------------------------------------------------------------------------------

*** INTERESTING tests
  Some interesting behaviors observed. This is for the plain curiosity.

  0 matching test results. 

*** FAILED tests
  Strong asserts were violated. Correct implementations should have no assert failures here.

  1 matching test results. 
  [FAILED] reactor.core.publisher.FluxSwitchMapStressTest.RequestAndProduceStressTest1
    (JVM args: [-XX:+UnlockDiagnosticVMOptions, -XX:+WhiteBoxAPI, -XX:-RestrictContended, -Dfile.encoding=UTF-8, -Duser.country, -Duser.language=en, -Duser.variant, -Xint])
  Observed state   Occurrences   Expectation  Interpretation                                              
          200, 1         3,516    ACCEPTABLE  Should produced and remaining requested result in total r...
          220, 0             1     FORBIDDEN  No default case provided, assume FORBIDDEN                  


*** ERROR tests
  Tests break for some reason, other than failing the assert. Correct implementations should have none.

  0 matching test results. 

*** All remaining tests
  Tests that do not fall into any of the previous categories.

  111 matching test results.  Use -v to print them.
```

IIRC the failures only occurred in runs over the master branch so far, but not 100% sure.

**Comment by OlegDokuka** [comment]
@simonbasle after the investigation it seems that the bug is on `ColdTestPublisher` side which does not propagate onComplete signal
