### ISSUE TITLE
Discard hook errors on a cancelled flux

### ISSUE THREAD

**Issue by Cavallium** [reactor/reactor-core#2714]
Sometimes I see an error about the discard hook if I cancel a flux

## Expected Behavior
No errors

## Actual Behavior
Sometimes a lot of identical errors appear on the console

<details>
  <summary>NoSuchElementException: Cannot further apply discard hook while discarding and clearing a queue
</summary>

```
2021-06-02 14:00:56.231  WARN 30897 Operators            : Cannot further apply discard hook while discarding and clearing a queue
java.util.NoSuchElementException
        at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1586)
        at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1607)
        at reactor.core.publisher.FluxIterable$IterableSubscription.poll(FluxIterable.java:422)
        at reactor.core.publisher.Operators.onDiscardQueueWithClear(Operators.java:479)
        at reactor.core.publisher.FluxFlatMap$FlatMapInner.cancel(FluxFlatMap.java:1023)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.unsubscribeEntry(FluxFlatMap.java:340)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.unsubscribeEntry(FluxFlatMap.java:219)
        at reactor.core.publisher.FlatMapTracker.unsubscribe(FluxFlatMap.java:1083)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.cancel(FluxFlatMap.java:360)
        at reactor.core.publisher.FluxPeek$PeekSubscriber.cancel(FluxPeek.java:152)
        at reactor.core.publisher.Operators.terminate(Operators.java:1239)
        at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.cancel(MonoFlatMapMany.java:131)
        at reactor.core.publisher.FluxMap$MapSubscriber.cancel(FluxMap.java:167)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.cancel(FluxFlatMap.java:359)
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.cancel(FluxFlatMap.java:359)
        at reactor.core.publisher.FluxFilter$FilterSubscriber.cancel(FluxFilter.java:191)
        at reactor.core.publisher.FluxPeek$PeekSubscriber.cancel(FluxPeek.java:152)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drainLoop(Operators.java:2251)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drain(Operators.java:2219)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.cancel(Operators.java:2031)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drainLoop(Operators.java:2251)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drain(Operators.java:2219)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.cancel(Operators.java:2031)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drainLoop(Operators.java:2251)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.drain(Operators.java:2219)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.cancel(Operators.java:2031)
        at reactor.core.publisher.FluxLimitRequest$FluxLimitRequestSubscriber.cancel(FluxLimitRequest.java:158)
        at reactor.core.publisher.MonoSingle$SingleSubscriber.doOnCancel(MonoSingle.java:108)
        at reactor.core.publisher.Operators$MonoInnerProducerBase.cancel(Operators.java:2783)
        at reactor.core.publisher.FluxPeek$PeekSubscriber.cancel(FluxPeek.java:152)
        at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.cancel(MonoFlatMapMany.java:130)
        at reactor.core.publisher.FluxMergeSequential$MergeSequentialMain.cancel(FluxMergeSequential.java:268)
        at reactor.core.publisher.Operators$DeferredSubscription.cancel(Operators.java:1632)
        at reactor.core.publisher.FluxFirstWithValue$RaceValuesCoordinator.tryWin(FluxFirstWithValue.java:280)
        at reactor.core.publisher.FluxFirstWithValue$FirstValuesEmittingSubscriber.onNext(FluxFirstWithValue.java:333)
        at reactor.core.publisher.FluxMergeSequential$MergeSequentialMain.drain(FluxMergeSequential.java:432)
        at reactor.core.publisher.FluxMergeSequential$MergeSequentialMain.innerNext(FluxMergeSequential.java:304)
        at reactor.core.publisher.FluxMergeSequential$MergeSequentialInner.onNext(FluxMergeSequential.java:571)
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.complete(MonoIgnoreThen.java:284)
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onNext(MonoIgnoreThen.java:187)
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:232)
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203)
        at reactor.core.publisher.FluxMergeSequential$MergeSequentialMain.drain(FluxMergeSequential.java:367)
        at reactor.core.publisher.FluxMergeSequential$MergeSequentialMain.innerComplete(FluxMergeSequential.java:328)
        at reactor.core.publisher.FluxMergeSequential$MergeSequentialInner.onComplete(FluxMergeSequential.java:584)
        at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onComplete(MonoIgnoreElements.java:88)
        at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onComplete(MonoIgnoreElements.java:88)
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:209)
        at reactor.core.publisher.MonoUsing$MonoUsingSubscriber.onComplete(MonoUsing.java:283)
        at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onComplete(MonoPeekTerminal.java:299)
        at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.onComplete(MonoSubscribeOn.java:162)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2057)
        at reactor.core.publisher.Operators$MonoSubscriber.onComplete(Operators.java:1857)
        at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:58)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4150)
        at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:126)
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
```
</details>

## Steps to Reproduce
Can't reproduce, it happens rarely, without any useful information in the stacktrace about the origin of the problematic code.

## Possible Solution
It seems to be related to iterable fluxes, but I'm not sure since I can't find where is the problem in the source code.

## Your Environment

* Reactor version(s) used: `3.4.6`
* JVM version:
```
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-16.0.1+9 (build 16.0.1+9, mixed mode, sharing)
```

* OS and version:
```
Linux 5.11.12-051112-generic #202104071432 SMP Wed Apr 7 14:50:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by simonbasle** [comment]
@Cavallium are you setting any `onDiscard` hook yourself ? it seems you're converting a HashMap to a `Flux` and while it attempts to terminate iterating over it for discarding purposes, it throws this exception. Maybe because the map is externally `clear()`ed ?

**Comment by Cavallium** [comment]
I temporarily wrapped all my maps into unmodifiable copies before calling .fromIterable(map.entrySet()) and it worked.
Somewhere a map was being modified by my code, it's not a bug in reactor-core.
Thanks
