### ISSUE TITLE
Subscribe call, there is a certain probability that an interrupt exception occured

### ISSUE THREAD

**Issue by fywyd** [reactor/reactor-core#2724]
## Expected Behavior
Correct execution without interrupt exception
## Actual Behavior
An interrupt exception occurred
## Steps to Reproduce

```java
// controller class
    @PostMapping("/convert/{type}")
    public ResponseEntity<Mono<ResponseFile>> convert(@RequestBody FileWarp fileWarp, @PathVariable String type) {
        final String typePdf = "pdf";
        Mono<ResponseFile> result = commonService.pdf(fileWarp)
                .map(tmtStorageService::publish);
        return ResponseEntity.ok(result);
    }

// commonservice class
    public Mono<ResponseFile> pdf(@Nonnull FileWarp originFile, String... size) {
        FileTypes type = FileTypes.of(originFile.getName());
        TransientFile transientFile = new TransientFile(originFile, transformStoreService);
        originFile.setPath(transientFile.getFile().getAbsolutePath());
         return pictureCommand.pdf(transientFile)
                  .flatMap(pdf -> pictureCommand.thumbnail(transientFile)
                          .map(thumbnail -> getResponseFile(originFile, pdf, thumbnail))
              );
    }

// TransientFile class
TransientFile (@Nonnull FileWarp file, @Nonnull TransformStoreService transformStoreService){
  // TempUtils a utils to create tempdir
  TempUtils.forceMakeTempDirectory(this.md5) // create tempDir
        .onErrorResume(throwable -> {
            return Mono.just(Files.createTempDir().toPath());
        })
        .onErrorReturn(new File(System.getProperty("java.io.tmpdir")).toPath())
        .doOnSuccess(tempPath -> {
            try {
                File tempFile = new File(tempPath.toString(), origin + this.type.getSuffix());
                Instant startWrite = Instant.now();
                // download file from minio
                InputStream inputStream = transformStoreService.open(this.protocol, this.corpId);
                if (inputStream == null) {
                    throw new ExecuteOperationFailureException("XXX");
                }

                // save to tempFile
                this.copy(inputStream, tempFile, count);
                
                long t = Duration.between(startWrite, Instant.now()).toMillis();
                setDownloadTime(t);

            } catch (IOException | StorageException e) {
                log.error("Download remote file break down, file id: {}, file name: {}.", this.id, this.name, e);
                throw new ExecuteOperationFailureException("download file failed.", e);
            } catch (RuntimeException throwable) {
                log.error("error ,file id：{},file name：{}: ", file.getId(), file.getName(), throwable);
                throw throwable;
            }
        })
        .subscribe();
}
```

## Your Environment

reactor-core-3.3.3.RELEASE
spring-webflux-5.2.4.RELEASE
reactor-netty-0.9.5.RELEASE
netty-transport-4.1.45.Final
okhttp-4.8.1
okio-2.7.0.
minio-8.0.3

## loginfo
```log
xxx.xxxx.cloud.storage.client.core.exception.StorageException: 【TCS Client Exception】：【2058/202105/30100/5BEB276C5C47CC4B538F5D285D9E812D/archives/2CE01B1C37F44959A4AB1883B619AFC7_file.jpg】.
	at xxx.xxxx.cloud.storage.client.minio.client.MinioClient.getObject(MinioClient.java:200) ~[storage-client-minio-3.0.0.jar!/:3.0.0]
	at xxx.xxxx.cloud.storage.client.minio.MinioStroageImpl.getInputStream(MinioStroageImpl.java:159) ~[storage-client-minio-3.0.0.jar!/:3.0.0]
	at xxx.xxxx.cloud.storage.client.core.store.StorageServiceImpl.getInputStream(StorageServiceImpl.java:265) ~[storage-client-core-3.0.0.jar!/:3.0.0]
	at xxx.xxxx.xxx.xxx.service.TransformStoreService.open(TransformStoreService.java:206) ~[classes!/:2.2.6-SNAPSHOT]
	at xxx.xxxx.xxx.xxx.service.TransientFile.lambda$new$1(TransientFile.java:90) ~[classes!/:2.2.6-SNAPSHOT]
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:164) ~[reactor-core-3.3.3.RELEASE.jar!/:3.3.3.RELEASE]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73) ~[reactor-core-3.3.3.RELEASE.jar!/:3.3.3.RELEASE]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73) ~[reactor-core-3.3.3.RELEASE.jar!/:3.3.3.RELEASE]
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2267) ~[reactor-core-3.3.3.RELEASE.jar!/:3.3.3.RELEASE]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2075) ~[reactor-core-3.3.3.RELEASE.jar!/:3.3.3.RELEASE]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onSubscribe(FluxOnErrorResume.java:68) ~[reactor-core-3.3.3.RELEASE.jar!/:3.3.3.RELEASE]
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54) ~[reactor-core-3.3.3.RELEASE.jar!/:3.3.3.RELEASE]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4110) ~[reactor-core-3.3.3.RELEASE.jar!/:3.3.3.RELEASE]
	at reactor.core.publisher.Mono.subscribeWith(Mono.java:4216) ~[reactor-core-3.3.3.RELEASE.jar!/:3.3.3.RELEASE]
	at reactor.core.publisher.Mono.subscribe(Mono.java:3942) ~[reactor-core-3.3.3.RELEASE.jar!/:3.3.3.RELEASE]
	at xxx.xxxx.xxx.xxx.service.TransientFile.<init>(TransientFile.java:131) ~[classes!/:2.2.6-SNAPSHOT]
	at xxx.xxxx.xxx.xxx.service.CommonService.pdf(CommonService.java:105) ~[classes!/:2.2.6-SNAPSHOT]
	at xxx.xxxx.xxx.xxx.controller.RouterController.convert(RouterController.java:41) ~[classes!/:2.2.6-SNAPSHOT]
	at sun.reflect.GeneratedMethodAccessor80.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_291]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_291]
	at org.springframework.web.reactive.result.method.InvocableHandlerMethod.lambda$invoke$0(InvocableHandlerMethod.java:147) ~[spring-webflux-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118) ~[reactor-core-3.3.3.RELEASE.jar!/:3.3.3.RELEASE]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1705) ~[reactor-core-3.3.3.RELEASE.jar!/:3.3.3.RELEASE]
	at reactor.core.publisher.MonoZip$ZipCoordinator.signal(MonoZip.java:247) ~[reactor-core-3.3.3.RELEASE.jar!/:3.3.3.RELEASE]
	at reactor.core.publisher.MonoZip$ZipInner.onNext(MonoZip.java:329) ~[reactor-core-3.3.3.RELEASE.jar!/:3.3.3.RELEASE]
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:173) ~[reactor-core-3.3.3.RELEASE.jar!/:3.3.3.RELEASE]
	at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onNext(FluxDefaultIfEmpty.java:92) ~[reactor-core-3.3.3.RELEASE.jar!/:3.3.3.RELEASE]
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67) ~[reactor-core-3.3.3.RELEASE.jar!/:3.3.3.RELEASE]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73) ~[reactor-core-3.3.3.RELEASE.jar!/:3.3.3.RELEASE]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1705) ~[reactor-core-3.3.3.RELEASE.jar!/:3.3.3.RELEASE]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:144) ~[reactor-core-3.3.3.RELEASE.jar!/:3.3.3.RELEASE]
	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:103) ~[reactor-core-3.3.3.RELEASE.jar!/:3.3.3.RELEASE]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:287) ~[reactor-core-3.3.3.RELEASE.jar!/:3.3.3.RELEASE]
	at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onNext(FluxFilterFuseable.java:330) ~[reactor-core-3.3.3.RELEASE.jar!/:3.3.3.RELEASE]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1705) ~[reactor-core-3.3.3.RELEASE.jar!/:3.3.3.RELEASE]
	at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:160) ~[reactor-core-3.3.3.RELEASE.jar!/:3.3.3.RELEASE]
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136) ~[reactor-core-3.3.3.RELEASE.jar!/:3.3.3.RELEASE]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:252) ~[reactor-core-3.3.3.RELEASE.jar!/:3.3.3.RELEASE]
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136) ~[reactor-core-3.3.3.RELEASE.jar!/:3.3.3.RELEASE]
	at reactor.netty.channel.FluxReceive.terminateReceiver(FluxReceive.java:419) ~[reactor-netty-0.9.5.RELEASE.jar!/:0.9.5.RELEASE]
	at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:209) ~[reactor-netty-0.9.5.RELEASE.jar!/:0.9.5.RELEASE]
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:367) ~[reactor-netty-0.9.5.RELEASE.jar!/:0.9.5.RELEASE]
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:363) ~[reactor-netty-0.9.5.RELEASE.jar!/:0.9.5.RELEASE]
	at reactor.netty.http.server.HttpServerOperations.onInboundNext(HttpServerOperations.java:489) ~[reactor-netty-0.9.5.RELEASE.jar!/:0.9.5.RELEASE]
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:90) ~[reactor-netty-0.9.5.RELEASE.jar!/:0.9.5.RELEASE]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
	at reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java:214) ~[reactor-netty-0.9.5.RELEASE.jar!/:0.9.5.RELEASE]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321) ~[netty-codec-4.1.45.Final.jar!/:4.1.45.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295) ~[netty-codec-4.1.45.Final.jar!/:4.1.45.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.45.Final.jar!/:4.1.45.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) ~[netty-transport-native-epoll-4.1.45.Final-linux-x86_64.jar!/:4.1.45.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[netty-transport-native-epoll-4.1.45.Final-linux-x86_64.jar!/:4.1.45.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-transport-native-epoll-4.1.45.Final-linux-x86_64.jar!/:4.1.45.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.45.Final.jar!/:4.1.45.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.45.Final.jar!/:4.1.45.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.45.Final.jar!/:4.1.45.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_291]
Caused by: java.io.InterruptedIOException: interrupted
	at okio.Timeout.throwIfReached(Timeout.kt:98) ~[okio-2.7.0.jar!/:na]
	at okio.OutputStreamSink.write(JvmOkio.kt:50) ~[okio-2.7.0.jar!/:na]
	at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:103) ~[okio-2.7.0.jar!/:na]
	at okio.RealBufferedSink.flush(RealBufferedSink.kt:247) ~[okio-2.7.0.jar!/:na]
	at okhttp3.internal.http1.Http1ExchangeCodec.finishRequest(Http1ExchangeCodec.kt:155) ~[okhttp-4.8.1.jar!/:na]
	at okhttp3.internal.connection.Exchange.finishRequest(Exchange.kt:91) ~[okhttp-4.8.1.jar!/:na]
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:76) ~[okhttp-4.8.1.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.8.1.jar!/:na]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34) ~[okhttp-4.8.1.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.8.1.jar!/:na]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) ~[okhttp-4.8.1.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.8.1.jar!/:na]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) ~[okhttp-4.8.1.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.8.1.jar!/:na]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) ~[okhttp-4.8.1.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.8.1.jar!/:na]
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) ~[okhttp-4.8.1.jar!/:na]
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154) ~[okhttp-4.8.1.jar!/:na]
	at io.minio.MinioClient.execute(MinioClient.java:647) ~[minio-8.0.3.jar!/:8.0.3]
	at io.minio.MinioClient.execute(MinioClient.java:563) ~[minio-8.0.3.jar!/:8.0.3]
	at io.minio.MinioClient.executeGet(MinioClient.java:830) ~[minio-8.0.3.jar!/:8.0.3]
	at io.minio.MinioClient.getObject(MinioClient.java:1009) ~[minio-8.0.3.jar!/:8.0.3]
	at xxx.xxxx.cloud.storage.client.minio.client.MinioClient.getObject(MinioClient.java:196) ~[storage-client-minio-3.0.0.jar!/:3.0.0]
	... 70 common frames omitted
```

* Reactor version(s) used: 3.3.3.RELEASE
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`java -version`): 1.8.x
* OS and version (eg `uname -a`):  k8s

**Comment by simonbasle** [comment]
This is an `InterruptedIoException` that is thrown (ultimately) by `minio` and the underlying `okhttp` because of a timeout... I don't see what it has to do with reactor, and what you'd expect reactor can do to improve the situation...

On a side note, 3.3.3.RELEASE is outdated by 15 versions (a solid 1 year and 4 month old): latest 3.3.x is `3.3.18.RELEASE`

**Comment by fywyd** [comment]
According to the time information in the log file, the interrupt exception occurs within 1 second, and not reach the timeout of okio.  and, okio.Timeout class show that the thread interrupt is detected, which interrupts the program processing, not the interrupt exception caused by timeout.

[reactor issues.txt](https://github.com/reactor/reactor-core/files/6707797/reactor.issues.txt)

**Comment by simonbasle** [comment]
Ok. I'm still not sure where the interruption comes from, but from that log one thing is obvious: the minio processing, which is using an `InputStream` and thus is blocking, runs on a netty thread (epoll), which should not be blocked.

I just noticed that when constructing the `TransientFile` you block, rather than returning the `Mono` and using composition on it in upper layers, which is a reactive code smell.

You could start by trying to avoid blocking the netty thread by using `.subscribeOn(Schedulers.elastic())` right before that (not ideal) `.subscribe()` and see if the issue still occurs?

**Comment by fywyd** [comment]
OK, I'll try. Thank you。

**Comment by fywyd** [comment]
This code will report an error. When the subsequent code is executed, this code has not been executed.
.subscribeOn(Schedulers.elastic());

And  the following code, the program can run normally, but after running for a period of time , about one day,  it still reports an  interrupt exception.

.publishOn(Schedulers.elastic())
.subscribe();

**Comment by simonbasle** [comment]
Using a library that seems to have a inherently blocking API (`InputStream`) and doing file-related work (which is also blocking in nature when dealing with local filesystem), perhaps WebFlux and Reactive Programming are not such a good fit.

I mean, there is still a lot to unpack and improve in your snippet (subscribing to the mono instead of returning it and composing on it, blocking processing in a `doOnNext` which here ultimately boils down to blocking the controller and the underlying netty thread, eager processing in a service that is supposed to return a Mono, etc...) but have you simply considered plain old Spring MVC would be a better fit for this particular job ?

there are very few `Thread#interrupt()` calls in reactor itself, none of which are obviously used in your snippet. there are 0 use of `InterruptedIOException` in reactor.
however, there is a lot your snippet doesn't show, but again the most likely culprit would be minio/okhttp for the interrupt exception.

**Comment by fywyd** [comment]
OK, I'll try Spring MVC. Thank you。
