### ISSUE TITLE
Exception is always treated as eager in SwitchIfEmpty

### ISSUE THREAD

**Issue by sebasm** [reactor/reactor-core#2748]
When a mono.error is triggered in a SwithIfEmpty, is always executed, even inside a differ.

## Expected Behavior
Exception shouldn't appear on the logs

## Actual Behavior
Exception is always shown on the logs.

## Steps to Reproduce

I tried several different approaches

### First:

```kotlin
logger.info("Processing operation $operation")
return operationPort
            .findOperationById(operation!!.id!!)
            .switchIfEmpty {
                Mono.error(PlumaException(ErrorsEnum.OPERATION_NOT_FOUND.message, ErrorsEnum.OPERATION_NOT_FOUND.id.toString()))
            }
```

When testing that code with .block() it shows the exception twice:

```
2021-07-27 12:48:55.022  INFO 62703 --- [           main] pluma.logic.BackofficeDepositCommand     : Processing operation BaseDto(...)
pluma.exception.PlumaException: Operation not found.
	at pluma.logic.BackofficeDepositCommand$execute$1.invoke(BackofficeDepositCommand.kt:34)
	at pluma.logic.BackofficeDepositCommand$execute$1.invoke(BackofficeDepositCommand.kt:15)
	at reactor.kotlin.core.publisher.MonoExtensionsKt$switchIfEmpty$1.get(MonoExtensions.kt:138)
2021-07-27 12:48:55.077 ERROR 62703 --- [actor-tcp-nio-1] pluma.logic.BackofficeDepositCommand     : Error processing operation: BaseDto(...)

reactor.core.Exceptions$ReactiveException: pluma.exception.PlumaException: Operation not found.

	at reactor.core.Exceptions.propagate(Exceptions.java:392)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:97)
	at reactor.core.publisher.Mono.block(Mono.java:1703)

```

### Second:

In this case returning a defer inside the SwitchIfEmpty

```kotlin
logger.info("Processing operation $operation")
return operationPort
            .findOperationById(operation!!.id!!)
            .switchIfEmpty {
                   Mono.defer{Mono.error(PlumaException(ErrorsEnum.OPERATION_NOT_FOUND.message, ErrorsEnum.OPERATION_NOT_FOUND.id.toString()))}

            }
```

And also testing it with block()

```
    depositCommand.execute().block()
```

Still getting it twice in the logs:

```

2021-07-27 12:57:12.527  INFO 62754 --- [           main] pluma.logic.BackofficeDepositCommand     : Processing operation BaseDto(...)
pluma.exception.PlumaException: Operation not found.
	at pluma.logic.BackofficeDepositCommand$execute$1$1.get(BackofficeDepositCommand.kt:31)
	at pluma.logic.BackofficeDepositCommand$execute$1$1.get(BackofficeDepositCommand.kt:15)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4150)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:81)
        ....
	at java.lang.Thread.run(Thread.java:748)
2021-07-27 12:57:12.561 ERROR 62754 --- [actor-tcp-nio-1] pluma.logic.BackofficeDepositCommand     : Error processing operation: BaseDto(...)

reactor.core.Exceptions$ReactiveException: pluma.exception.PlumaException: Operation not found.

	at reactor.core.Exceptions.propagate(Exceptions.java:392)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:97)
	at reactor.core.publisher.Mono.block(Mono.java:1703)
```
	
### Third:

Tried to call a function inside the differ instead of just the exception. In this case I had to cast it because it was expecting a Mono<Operation>, even if I knew that that mono was an error one.

```kotlin
logger.info("Processing operation $operation")
return operationPort
            .findOperationById(operation!!.id!!)
            .switchIfEmpty {
                   Mono.defer{buildError(ErrorsEnum.OPERATION_NOT_FOUND)} as Mono<Operation>
            }

private fun buildError(exception: ErrorsEnum): Mono<Any>? {
        return Mono.error(PlumaException(exception.message, exception.id.toString()))
    }
```

Testing it with block()

```kotlin
      depositCommand.execute().block()
```

In the logs appears twice:

```

2021-07-27 13:05:23.117  INFO 62827 --- [           main] pluma.logic.BackofficeDepositCommand     : Processing operation BaseDto(...)
pluma.exception.PlumaException: Operation not found.
	at pluma.logic.BackofficeDepositCommand.buildError(BackofficeDepositCommand.kt:93)
	at pluma.logic.BackofficeDepositCommand.access$buildError(BackofficeDepositCommand.kt:15)
	at pluma.logic.BackofficeDepositCommand$execute$1$1.get(BackofficeDepositCommand.kt:33)
	at pluma.logic.BackofficeDepositCommand$execute$1$1.get(BackofficeDepositCommand.kt:15)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4150)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:81)
        ......
	at java.lang.Thread.run(Thread.java:748)
2021-07-27 13:05:23.175 ERROR 62827 --- [actor-tcp-nio-1] pluma.logic.BackofficeDepositCommand     : Error processing operation: BaseDto(...)

reactor.core.Exceptions$ReactiveException: pluma.exception.PlumaException: Operation not found.

	at reactor.core.Exceptions.propagate(Exceptions.java:392)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:97)
	at reactor.core.publisher.Mono.block(Mono.java:1703)
	at pluma.logic.BackofficeDepositCommandTests.testCommandOperationNotFound(BackofficeDepositCommandTests.kt:210)
```

And testing it with StepVerifier and expecting the error, test passes ok, the second time is not printed in the logs, because is expected by the step verifier but it still appear when SwitchIfEmpty is evaluated

```kotlin
          StepVerifier
            .create(depositCommand.execute())
            .expectErrorMessage("Operation not found.")
            .verify()
```

```
2021-07-27 13:09:29.236  INFO 62856 --- [           main] pluma.logic.BackofficeDepositCommand     : Processing operation BaseDto(...)
pluma.exception.PlumaException: Operation not found.
	at pluma.logic.BackofficeDepositCommand.buildError(BackofficeDepositCommand.kt:93)
	at pluma.logic.BackofficeDepositCommand.access$buildError(BackofficeDepositCommand.kt:15)
	at pluma.logic.BackofficeDepositCommand$execute$1$1.get(BackofficeDepositCommand.kt:33)
	at pluma.logic.BackofficeDepositCommand$execute$1$1.get(BackofficeDepositCommand.kt:15)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4150)
        .....
	at java.lang.Thread.run(Thread.java:748)
2021-07-27 13:09:29.288 ERROR 62856 --- [actor-tcp-nio-1] pluma.logic.BackofficeDepositCommand     : Error processing operation: BaseDto(...)
```

## Your Environment

* Reactor version(s) used: core 3.4.5
* Other relevant libraries versions (eg. `netty`, ...): Kotlin-extensions 1.1.3
* JVM version (`java -version`): java version "1.8.0_291"
* OS and version (eg. `uname -a`): Darwin 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64

**Comment by sebasm** [comment]
Sorry team, don't waste time on this. It was a huge error in my code. 

At the end of the stream, I had a doOnError{} like this:

```kotlin

logger.info("Processing operation $operation")
return operationPort
            .findOperationById(operation!!.id!!)
            .switchIfEmpty {
                   Mono.defer{buildError(ErrorsEnum.OPERATION_NOT_FOUND)} as Mono<Operation>
            }

private fun buildError(exception: ErrorsEnum): Mono<Any>? {
        return Mono.error(PlumaException(exception.message, exception.id.toString()))
    }
.doOnError {
                logger.error("Error processing operation: $operation",  **it.printStackTrace()**)
            }

```

Instead of passing to the log method just **it** I was passing **it.printStackTrace()** that is the reason why I was seeing it twice in the logs.
In my defense, I'm still really new with Reactor and I was looking for the error in the wrong place.
Will close this one.

**Comment by sebasm** [comment]
Explained in the last comment. No bug or work to do here.
