### ISSUE TITLE
Traceback / OnAssemblyException: tune toString for better rendering

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#2786]
Currently, when an `OnAssemblyException` is appended to an exception (via suppression) and that exception is printed, it looks like this (`---->` added for highlight):

```
java.lang.ArithmeticException: / by zero
	at reactor.guide.GuideDebuggingExtraTests.lambda$test$1(GuideDebuggingExtraTests.java:63)
---->
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
<----
Assembly trace from producer [reactor.core.publisher.FluxMapFuseable], described as [watch this] :
	reactor.core.publisher.Flux.checkpoint(Flux.java:3264)
	reactor.guide.GuideDebuggingExtraTests.test(GuideDebuggingExtraTests.java:64)
Error has been observed at the following site(s):
```

The classname of the `OnAssemblyException` in the `Suppressed:` line isn't ideal and could be changed to let users know information below it has been added by Reactor:
```
java.lang.ArithmeticException: / by zero
	at reactor.guide.GuideDebuggingExtraTests.lambda$test$1(GuideDebuggingExtraTests.java:63)
---->
	Suppressed: The stacktrace has been enhanced by Reactor, refer to additional information below.
<----
Assembly trace from producer [reactor.core.publisher.FluxMapFuseable], described as [watch this] :
	reactor.core.publisher.Flux.checkpoint(Flux.java:3264)
	reactor.guide.GuideDebuggingExtraTests.test(GuideDebuggingExtraTests.java:64)
Error has been observed at the following site(s):
```

Additionally, the `Stack Trace` section header could be renamed to `Original Stack Trace` instead.

**Comment by dominikbrandon** [comment]
I'm looking into that :) Hope to push the PR today
