### ISSUE TITLE
retryWhen use problem

### ISSUE THREAD

**Issue by XiaoWeiKIN** [reactor/reactor-core#2792]
hi，when I was using **retryWhen**, I expected to be able to retry 3 times, but in fact I only retried 2 times and did not execute the third time. Why is **retry(3)** three times?

```
        Flux.interval(Duration.ofMillis(250))
                .map(input -> {
                    if (input < 3) return "tick " + input;
                    throw new RuntimeException("boom");
                })
                .doOnError(e -> log.error("on error", e))
                .retryWhen(Retry.from(companion ->
                        companion.doOnNext(retrySignal -> log.info("retry times {} ", retrySignal.totalRetries())).
                                take(3)))
                .retry(3)
                .elapsed()
                .subscribe(res -> log.info(res.toString()), e -> log.error("error", e));
        Thread.sleep(50000);
```

```
20:07:05.580 [parallel-1] INFO wangxw.operator.ErrorHandleOperatorTest - [274,tick 0]
20:07:05.830 [parallel-1] INFO wangxw.operator.ErrorHandleOperatorTest - [250,tick 1]
20:07:06.080 [parallel-1] INFO wangxw.operator.ErrorHandleOperatorTest - [250,tick 2]
20:07:06.359 [parallel-1] ERROR wangxw.operator.ErrorHandleOperatorTest - on error
java.lang.RuntimeException: boom
	at wangxw.operator.ErrorHandleOperatorTest.lambda$restryWhen$18(ErrorHandleOperatorTest.java:123)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106)
	at reactor.core.publisher.FluxInterval$IntervalRunnable.run(FluxInterval.java:125)
	at reactor.core.scheduler.PeriodicWorkerTask.call(PeriodicWorkerTask.java:59)
	at reactor.core.scheduler.PeriodicWorkerTask.run(PeriodicWorkerTask.java:73)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
20:07:06.374 [parallel-1] INFO wangxw.operator.ErrorHandleOperatorTest - retry times 0 
20:07:06.628 [parallel-2] INFO wangxw.operator.ErrorHandleOperatorTest - [548,tick 0]
20:07:06.878 [parallel-2] INFO wangxw.operator.ErrorHandleOperatorTest - [250,tick 1]
20:07:07.127 [parallel-2] INFO wangxw.operator.ErrorHandleOperatorTest - [249,tick 2]
20:07:07.378 [parallel-2] ERROR wangxw.operator.ErrorHandleOperatorTest - on error
java.lang.RuntimeException: boom
	at wangxw.operator.ErrorHandleOperatorTest.lambda$restryWhen$18(ErrorHandleOperatorTest.java:123)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106)
	at reactor.core.publisher.FluxInterval$IntervalRunnable.run(FluxInterval.java:125)
	at reactor.core.scheduler.PeriodicWorkerTask.call(PeriodicWorkerTask.java:59)
	at reactor.core.scheduler.PeriodicWorkerTask.run(PeriodicWorkerTask.java:73)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
20:07:07.378 [parallel-2] INFO wangxw.operator.ErrorHandleOperatorTest - retry times 1 
20:07:07.628 [parallel-3] INFO wangxw.operator.ErrorHandleOperatorTest - [501,tick 0]
20:07:07.880 [parallel-3] INFO wangxw.operator.ErrorHandleOperatorTest - [252,tick 1]
20:07:08.129 [parallel-3] INFO wangxw.operator.ErrorHandleOperatorTest - [249,tick 2]
20:07:08.380 [parallel-3] ERROR wangxw.operator.ErrorHandleOperatorTest - on error
java.lang.RuntimeException: boom
	at wangxw.operator.ErrorHandleOperatorTest.lambda$restryWhen$18(ErrorHandleOperatorTest.java:123)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106)
	at reactor.core.publisher.FluxInterval$IntervalRunnable.run(FluxInterval.java:125)
	at reactor.core.scheduler.PeriodicWorkerTask.call(PeriodicWorkerTask.java:59)
	at reactor.core.scheduler.PeriodicWorkerTask.run(PeriodicWorkerTask.java:73)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
20:07:08.380 [parallel-3] INFO wangxw.operator.ErrorHandleOperatorTest - retry times 2 
```

**Comment by simonbasle** [comment]
I'm not sure what you were expecting exactly vs what you got, but I suspect you expected a `error  RuntimeException: boom` message in the logs from the `subscribe` line?

If so, the reason you don't get that is that this chain of operators _cannot_ terminate with `onError`, because the `retryWhen` companion always finishes with an `onComplete`, rather than an `onError`.

To emulate `retry(3)` with `retryWhen`, have a look at the FAQ [entry](https://projectreactor.io/docs/core/release/reference/#faq.retryWhen) about that exact topic.
