### ISSUE TITLE
reactor-tools 3.4.11: java.lang.UnsupportedOperationException: Records requires ASM8

### ISSUE THREAD

**Issue by jkreileder** [reactor/reactor-core#2821]
When using records, e.g.,

```java
@RestController
@EnableConfigurationProperties(Clz.Config.class)
public class Clz 
{
    Clz(Config config) {...}

    @ConstructorBinding
    @ConfigurationProperties("clz")
    record Config(String someUrl) {}
}
```

with reactor-tools 3.4.11, you'll get 

```
java.lang.UnsupportedOperationException: Records requires ASM8
	at reactor.tools.shaded.net.bytebuddy.jar.asm.ClassVisitor.visit(ClassVisitor.java:112)
	at reactor.tools.agent.ReactorDebugClassVisitor.visit(ReactorDebugClassVisitor.java:47)
	at reactor.tools.shaded.net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:569)
	at reactor.tools.shaded.net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:424)
	at reactor.tools.agent.ReactorDebugAgent$1.transform(ReactorDebugAgent.java:104)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:244)
...
```

because of this [change](https://gitlab.ow2.org/asm/asm/-/commit/b8a362d4d1e1b94726cefdb3387d1813ab7ada66#61ee953ce37023604070377d2962073bd93d63f0) which has been fetched by bumping bytebuddy to 1.11.16.  (ReactorDebugClassVisitor sets api to ASM7.)

**Comment by raphw** [comment]
Not sure what `ReactorDebugClassVisitor` does, but until it would rely on new methods added to support methods (visitRecordComponent), simply bumping the number should be fine. The lock is meant to avoid that you overlook things.
