### ISSUE TITLE
Further improve BoundedElasticScheduler array-based busy pick

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#2927]
Follow up to #2909 

 - [ ] Improve the iteration to find the least busy worker when picking.

This can be done in several ways:
 - random choice instead of iterating?
 - limit the iteration?
 - chose a strategy when the array is bigger than a threshold?

> @OlegDokuka [said](https://github.com/reactor/reactor-core/pull/2909#discussion_r805562948):
> 
> As I mentioned before, can we do random choices here instead of iterating? Alternatively - can we just iterate a constant times or less if the array is smaller?
>
> @OlegDokuka [said](https://github.com/reactor/reactor-core/pull/2909#discussion_r805579526):
> 
> that is what we do in rsocket weighted loadbalancer -> [https://github.com/rsocket/rsocket-java/blob/master/rsocket-core/src/main/java/io/rsocket/loadbalance/WeightedLoadbalanceStrategy.java#L91](https://github.com/rsocket/rsocket-java/blob/master/rsocket-core/src/main/java/io/rsocket/loadbalance/WeightedLoadbalanceStrategy.java?rgh-link-date=2022-02-14T07%3A26%3A59Z#L91)

 - [ ] Add a stress test and/or improve the JMH bench

**Comment by ssalamov** [comment]
Hello,

Could you please check if this block operation is related to this ticket or something new?

```
java.lang.Error: jdk.internal.misc.Unsafe#park
	at com.ocado.lineitems.config.util.internal.LineitemsBlockHoundIntegration.lambda$applyTo$0(LineitemsBlockHoundIntegration.java:14)
	at reactor.blockhound.BlockHound$Builder.lambda$install$8(BlockHound.java:427)
	at reactor.blockhound.BlockHoundRuntime.checkBlocking(BlockHoundRuntime.java:89)
	at java.base/jdk.internal.misc.Unsafe.park(Unknown Source)
	at java.base/java.util.concurrent.locks.LockSupport.park(Unknown Source)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(Unknown Source)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(Unknown Source)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(Unknown Source)
	at java.base/java.util.concurrent.locks.ReentrantLock.lock(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.size(Unknown Source)
	at reactor.core.scheduler.BoundedElasticScheduler$BoundedScheduledExecutorService.ensureQueueCapacity(BoundedElasticScheduler.java:642)
	at reactor.core.scheduler.BoundedElasticScheduler$BoundedScheduledExecutorService.submit(BoundedElasticScheduler.java:744)
	at reactor.core.scheduler.Schedulers.workerSchedule(Schedulers.java:1344)
	at reactor.core.scheduler.ExecutorServiceWorker.schedule(ExecutorServiceWorker.java:50)
	at reactor.core.publisher.MonoSubscribeOn.subscribeOrReturn(MonoSubscribeOn.java:55)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:236)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203)

```

Regards,
Samir Salamov

**Comment by simonbasle** [comment]
I've started experimenting with different strategies, and running a benchmark which doesn't show a huge improvement between the strategies:
 - current prod (iterate whole array)
 - pick 8 random slots in the array
 - divide the array into buckets of size 1000, choose 1 bucket randomly and iterate it

The benchmark uses tasks that sleep, cycling through different amount of sleep (hiccups):
```java

	static int[] HICCUPS = new int[] { 0, 1, 2, 3, 4, 5, 10, 20, 30, 40, 50, 100, 150, 200 };

	private static Runnable task(CountDownLatch latch, int iteration) {
		final int hiccup = HICCUPS[iteration % HICCUPS.length];
		if (hiccup == 0)
			return latch::countDown;
		return () -> {
			try {
				Thread.sleep(hiccup);
			}
			catch (InterruptedException e) { }
			finally {
				latch.countDown();
			}
		};
	}
```
A typical bench looks like:
```java
	@Benchmark
	@OutputTimeUnit(TimeUnit.MILLISECONDS)
	@Warmup(iterations = 10, time = 1)
	@Measurement(iterations = 100, time = 1)
	@Threads(10)
	@BenchmarkMode({Mode.AverageTime})
	public void withArray(Blackhole bh) throws InterruptedException {
		int runs = 1000;
		CountDownLatch latch = new CountDownLatch(runs);
		for (int i = 0; i < runs; i++) {
			currentBoundedElasticScheduler.schedule(task(latch, i));
		}
		bh.consume(latch.await(100, TimeUnit.MILLISECONDS));
	}
```

And the results:
```
Benchmark                                                   Mode  Cnt    Score   Error  Units
BoundedElasticBusyStructureBenchmark.withArray              avgt  500  108.228 ± 1.482  ms/op
BoundedElasticBusyStructureBenchmark.withArrayRandomBucket  avgt  500  109.108 ± 2.692  ms/op
BoundedElasticBusyStructureBenchmark.withArrayRandomPick8   avgt  500  110.605 ± 8.945  ms/op
BoundedElasticBusyStructureBenchmark.withPriorityQueue      avgt  500  115.013 ± 1.515  ms/op
```
With smaller number of iterations (10):
```
Benchmark                                                   Mode  Cnt    Score   Error  Units
BoundedElasticBusyStructureBenchmark.withArray              avgt   50  105.675 ± 1.690  ms/op
BoundedElasticBusyStructureBenchmark.withArrayRandomBucket  avgt   50  106.163 ± 1.788  ms/op
BoundedElasticBusyStructureBenchmark.withArrayRandomPick8   avgt   50  107.479 ± 2.235  ms/op
BoundedElasticBusyStructureBenchmark.withPriorityQueue      avgt   50  113.969 ± 0.680  ms/op
```
Interestingly with 10 iterations and no hiccup (direct latch countdown in tasks), the random pick 8 strategy detaches itself:
```
Benchmark                                                   Mode  Cnt   Score   Error  Units
BoundedElasticBusyStructureBenchmark.withArray              avgt   50  23.257 ± 4.553  ms/op
BoundedElasticBusyStructureBenchmark.withArrayRandomBucket  avgt   50  33.494 ± 5.312  ms/op
BoundedElasticBusyStructureBenchmark.withArrayRandomPick8   avgt   50  13.149 ± 0.595  ms/op
BoundedElasticBusyStructureBenchmark.withPriorityQueue      avgt   50  37.161 ± 1.278  ms/op
```
That said, I don't think instant task is the most interesting and representative case for the bounded elastic scheduler, which is tailored for blocking tasks (and thus running for a few milliseconds at least).
```

**Comment by simonbasle** [comment]
<details>
<summary>for reference, implementation snippet of the strategies for choosing a `BoundedService` below</summary>

```java

		BoundedState chooseRandomly(BoundedState[] arr, int randomPicks) {
			BoundedState choice = arr[0];
			int leastBusy = Integer.MAX_VALUE;
			for (int i = 0; i < randomPicks; i++) {
				int slot = ThreadLocalRandom.current().nextInt(arr.length);
				BoundedState state = arr[slot];
				int busy = state.markCount;
				if (busy < leastBusy) {
					leastBusy = busy;
					choice = state;
				}
			}
			return choice;
		}

		BoundedState chooseBucketAndIterate(BoundedState[] arr, int bucketSize) {
			BoundedState choice = arr[0];
			if (arr.length <= bucketSize) {
				return chooseIterate(arr);
			}

			float flBucketSize = (float) bucketSize;
			int bucketCount = (int) Math.ceil(arr.length / flBucketSize);

			Random rng = new Random();
			int bucketStart = bucketSize * rng.nextInt(bucketCount);
			return chooseIterate(arr, bucketStart, bucketSize);
		}

		BoundedState chooseIterate(BoundedState[] arr, int start, int iterationSize) {
			BoundedState choice = arr[start];
			int leastBusy = Integer.MAX_VALUE;

			for (int i = start; i < iterationSize; i++) {
				BoundedState state = arr[i];
				int busy = state.markCount;
				if (busy < leastBusy) {
					leastBusy = busy;
					choice = state;
				}
			}
			return choice;
		}

		BoundedState chooseIterate(BoundedState[] arr) {
			return chooseIterate(arr, 0, arr.length);
		}

		@Nullable
		private BoundedState choseOneBusy() {
			BoundedState[] arr = busyArray;
			int len = arr.length;
			if (len == 0) {
				return null; //implicit retry in the pick() loop
			}
			if (len == 1) {
				return arr[0];
			}

			switch (this.strategy) {
				case 0:
					return chooseIterate(arr);
				case 1:
					return chooseBucketAndIterate(arr, 1000); //TODO adapt bucketSize
				default:
					return chooseRandomly(arr, this.strategy);
			}
		}
```

</details>
