### ISSUE TITLE
Unexpected Nullpointerexception

### ISSUE THREAD

**Issue by cavallium** [reactor/reactor-core#2960]
After some hours of intensive load in a Flux (~120k items/s), the BoundedElastic scheduler thrown an exception and the rate dropped from 120k items/s to 2k items/s

## Expected Behavior
Nothing crashes

## Actual Behavior
After two hours this exception is thrown and everything slows down:
``` 
2022-03-12 04:03:53.162 ERROR 138293 Schedulers           : Scheduler worker in group org.yotsuba.Main failed with an uncaught exception                                            
java.lang.NullPointerException: Cannot invoke "java.util.concurrent.atomic.AtomicReferenceArray.get(int)" because "b" is null                                                               at 
reactor.util.concurrent.SpscLinkedArrayQueue.poll(SpscLinkedArrayQueue.java:159)                                                                                                 
at reactor.util.concurrent.SpscLinkedArrayQueue.clear(SpscLinkedArrayQueue.java:212)                                                                                                
at reactor.core.publisher.FluxGroupBy$UnicastGroupedFlux.clear(FluxGroupBy.java:799)                                                                                                
at reactor.core.publisher.FluxPublishOn$PublishOnConditionalSubscriber.checkTerminated(FluxPublishOn.java:1112)                                                                     
at reactor.core.publisher.FluxPublishOn$PublishOnConditionalSubscriber.runAsync(FluxPublishOn.java:984)                                                                             
at reactor.core.publisher.FluxPublishOn$PublishOnConditionalSubscriber.run(FluxPublishOn.java:1067)                                                                                 
at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)                                                                                                                       
at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)                                                                                                                       
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)                                                                                                               
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)                                                         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)                                                                                        
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)                                                                                        at java.base/java.lang.Thread.run(Thread.java:833)
```

Then, some minutes lates,  another exception is thrown:
```
2022-03-12 04:16:36.410 ERROR 138293 Operators            : Operator called default onErrorDropped                                                                                  
java.lang.NullPointerException: Cannot invoke "java.util.concurrent.atomic.AtomicReferenceArray.get(int)" because "b" is null                                                               at 
reactor.util.concurrent.SpscLinkedArrayQueue.poll(SpscLinkedArrayQueue.java:159)                                                                                                 
at reactor.core.publisher.FluxGroupBy$UnicastGroupedFlux.poll(FluxGroupBy.java:753)                                                                                                 
at reactor.core.publisher.FluxPublishOn$PublishOnConditionalSubscriber.runAsync(FluxPublishOn.java:971)                                                                             
at reactor.core.publisher.FluxPublishOn$PublishOnConditionalSubscriber.run(FluxPublishOn.java:1067)                                                                                 
at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)                                                                                                                       
at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)                                                                                                                       
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)                                                                                                               
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)                                                         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)                                                                                        
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)                                                                                        at java.base/java.lang.Thread.run(Thread.java:833)
```

## Steps to Reproduce
Cannot reproduce currently, it seems to happen randomly after some hours of runtime.

## Your Environment
- openjdk version "17" 2021-09-14
OpenJDK Runtime Environment Temurin-17+35 (build 17+35)
  OpenJDK 64-Bit Server VM Temurin-17+35 (build 17+35, mixed mode, sharing)
- Shenandoah GC
- Linux 5.13.0-28-generic 31-Ubuntu SMP Thu Jan 13 17:41:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- The latest version of reactor

**Comment by OlegDokuka** [comment]
This issue happens because of concurrent cleanup of `SpscLinkedArrayQueue`  inside `reactor.core.publisher.FluxGroupBy$UnicastGroupedFlux`

**Comment by OlegDokuka** [comment]
related issue https://github.com/reactor/reactor-core/issues/2636

**Comment by LivingLikeKrillin** [comment]
Hi @OlegDokuka — I'm interested in helping with this issue if no one
  else is currently working on it. Before proposing anything, I read
  through your comments here and the references to #2636 / #2626.

  You described the root cause as a concurrent `clear` / `poll` race on
  `SpscLinkedArrayQueue` in `FluxGroupBy$UnicastGroupedFlux`, and pointed
  to #2636 and #2626 as related context.

  Would either of these be useful to you as a starting point?

  - A deterministic reproducer (stress test, possibly jcstress) for the
    race you described.
  - A localized guard around `UnicastGroupedFlux`'s queue access — only
    if you think it can be done without conflicting with the broader
    fusion-contract work referenced in #2636 / #2626.

  Or would you prefer this to stay as-is for now? Happy to follow whichever
  direction you suggest.
