### ISSUE TITLE
avoid false positive test of reactor-core-micrometer observation listener

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#3214]
Seen during separate test run:
```
16:54:23.581 [Test worker] INFO  i.m.tracing.test.SampleTestRunner - In memory tracing used. All spans should have trace id <d715ff64614b1691>
16:54:23.583 [test-2] ERROR reactor.core.scheduler.Schedulers - Scheduler worker in group main failed with an uncaught exception
org.opentest4j.AssertionFailedError: [no leftover span in delay thread] 
expected: null
 but was: LazySpan(d715ff64614b1691/d715ff64614b1691)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at reactor.core.observability.micrometer.MicrometerObservationIntegrationTest.lambda$null$3(MicrometerObservationIntegrationTest.java:117)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

First order of fixing is that this doesn't trip the JUnit test, as the exception is propagated to a separate thread's uncaughExceptionHandler. This is likely to hide an actual issue...

**Comment by simonbasle** [comment]
After I amended the test to make sure it fails if that exception is thrown, @marcingrzejszczak and I investigated a bit to understand why there was apparent pollution when running with Brave. It seems there's no fault of Reactor's implementation, but Brave by default uses `InheritableThreadLocal`s.  Each new Thread inherits the root span, and that's what gets restored at the end.

Since we don't use `Scope`s there shouldn't be any possibility of polluting `ThreadLocal` spans, so technically we _could_ remove that part of the test.

However the `SampleTestRunner` will probably switch to simple non-inheritable `ThreadLocal` (same default as in Spring Boot), which should also resolve the issue.

This issue is now focusing on changing the test so that the test fails if the assertion fails.
