### ISSUE TITLE
IllegalStateException using StepVerifier on a Flux with TakeUntilOther

### ISSUE THREAD

**Issue by conniey** [reactor/reactor-core#3268]
On upgrading to reactor-core 3.4.24, we noticed that a test is failing.  This test passed using reactor-core 3.4.23. 

## Expected Behavior
`IllegalStateException` is not thrown. The program ends normally.  

## Actual Behavior

```
Exception in thread "main" java.lang.IllegalStateException: VerifySubscriber has not been subscribed
	at reactor.test.MessageFormatter.error(MessageFormatter.java:141)
	at reactor.test.DefaultStepVerifierBuilder$DefaultVerifySubscriber.validate(DefaultStepVerifierBuilder.java:1827)
	at reactor.test.DefaultStepVerifierBuilder$DefaultVerifySubscriber.verify(DefaultStepVerifierBuilder.java:1304)
	at reactor.test.DefaultStepVerifierBuilder$DefaultStepVerifier.verify(DefaultStepVerifierBuilder.java:832)
	at reactor.test.DefaultStepVerifierBuilder$DefaultStepVerifier.verify(DefaultStepVerifierBuilder.java:823)
	at org.example.Program.main(Program.java:39)

Process finished with exit code 1
```

## Steps to Reproduce

```java
public class Program {
    private final Sinks.Empty<Integer> terminateEndpointStates = Sinks.empty();
    private final Sinks.Many<Integer> statesSink = Sinks.many().replay().latestOrDefault(-1);

    Flux<Integer> getEndpointStates() {
        return statesSink.asFlux()
                .takeUntilOther(this.terminateEndpointStates.asMono());
    }

    void terminate() {
        this.terminateEndpointStates.emitEmpty(Sinks.EmitFailureHandler.FAIL_FAST);
    }

    public static void main(String[] args) {
        final Program program = new Program();

        program.terminate();

        StepVerifier.create(program.getEndpointStates())
                .expectComplete()
                .verify();
    }
}
```

## Your Environment

* Reactor version(s) used:
  - reactor-core 3.4.24
  - reactor-test 3.4.24

* JVM version (`java -version`): 11
* OS and version (eg `uname -a`): Windows 11

**Comment by simonbasle** [comment]
Thanks for the report. This appears to be a regression from #3219 when the _`other`_ subscriber is pre-completed.

**Comment by simonbasle** [comment]
a simplified version of the test:
```java
@Test
void whenOtherAlreadyCompleted() {
	StepVerifier.create(Flux.just(1, 2, 3).takeUntilOther(Flux.empty()))
		.verifyComplete();
}
```

note also that tests like `FluxTakeUntilOther#takeNone()` would have raised a red flag if they were actually asserting `assertSubscribed()`.
