### ISSUE TITLE
Sinks.One<Void>.tryEmitValue no longer accepts null in 3.5.0

### ISSUE THREAD

**Issue by programmatix** [reactor/reactor-core#3284]
Calling `tryEmitValue(null)` on a `Sinks.One<Void>` worked without issue in 3.4.24, but in 3.5.0, we can see a NPE:

```
java.lang.NullPointerException: e
               at java.base/java.util.Objects.requireNonNull(Objects.java:233)
               at reactor.util.concurrent.SpscArrayQueue.offer(SpscArrayQueue.java:51)
               at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.onNext(FluxPublishOn.java:230)
               at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
               at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onNext(FluxTimeout.java:180)
               at reactor.core.publisher.FluxFlatMap$FlatMapMain.tryEmit(FluxFlatMap.java:543)
               at reactor.core.publisher.FluxFlatMap$FlatMapInner.onNext(FluxFlatMap.java:984)
               at reactor.core.publisher.Operators$MonoInnerProducerBase.complete(Operators.java:2744)
               at reactor.core.publisher.SinkOneMulticast.tryEmitValue(SinkOneMulticast.java:63)
               at reactor.core.publisher.SinkOneSerialized.tryEmitValue(SinkOneSerialized.java:38)
               at com.couchbase.client.core.transaction.util.ReactiveWaitGroup.lambda$done$1(ReactiveWaitGroup.java:99)
```

The Javadocs for tryEmitValue still indicate that null is a legitimate value:

```
Params:
value – the value to emit and complete with, or null to only trigger an onComplete

EmitResult tryEmitValue(@Nullable T value);
```

The important change may have been in SinkOneMulticast.tryEmitValue.  in 3.4.24 this has special handling for null:

```
		if (value == null) {
			for (Inner<O> as : array) {
				as.complete();
			}
		}
```

while in 3.5.0 it doesn't, it just passes the null through:

```
		for (Inner<O> as : prevSubscribers) {
			as.complete(value);
		}
```

I can't find any mention of this change in the release notes, and it's a breaking one for us.  Can you please confirm if this is intentional or a bug, e.g. do I need to patch our code?

**Comment by mikereiche** [comment]
This was working in 3.5.0-RC1 but is broken in 3.5.0.  The change is[ 849be9a207958b111ee7a06f4b21596b0122972f.](https://github.com/reactor/reactor-core/commit/849be9a207958b111ee7a06f4b21596b0122972f) 
Previously, if value was null, as.complete() was called with no argument.


![Screen Shot 2022-11-16 at 11 59 47 AM](https://user-images.githubusercontent.com/48999328/202282027-2642ca9e-3c10-49ce-8136-9887fd138359.png)

**Comment by simonbasle** [comment]
this is actually a regression introduced in the `3.4.x` branch (even though 3.4.25 was exceptionally released _after_ 3.5.0).
re-targeting this for 3.4.26, which will be forward-merged to 3.5.1 as well

**Comment by simonbasle** [comment]
Regression introduced in #3260

**Comment by simonbasle** [comment]
simplest workaround:
```java
T value;
EmitResult er = (value == null) ? sink.tryEmitComplete() : sink.tryEmitValue(value);
```

**Comment by dnault** [comment]
Thank you for jumping on this so quickly, @simonbasle
