### ISSUE TITLE
Documentation on Mono#usingWhen should explain exception wrapping.

### ISSUE THREAD

**Issue by alopukhov** [reactor/reactor-core#3302]
Javadoc on Mono#usingWhen should explain exception wrapping for various cases.

## Documentation Issue
[Mono#usingWhen](https://projectreactor.io/docs/core/3.4.25/api/reactor/core/publisher/Mono.html#usingWhen-org.reactivestreams.Publisher-java.util.function.Function-java.util.function.Function-) states:

> valued Mono, asyncCleanup ends with onError(t): downstream receives onError(t), value is discarded

It should explain that downstream receives wrapped exception in such case.

## Improvement Suggestion
It would be great if Javadoc would mention exception wrapping for all cases.

## Additional context

With current documentation I've expected to receive original exception from asyncCleanup downstream.
Downstream actually receives error from asyncCleanup wrapped in generic RuntimeException (not a dedicated subclass).
This exception may not be unwrapped using reactor.core.Exceptions#unwrap.

Simplest example to get hands on exception (valid for reactor-core 3.4.25 and 3.5.0):
```java
CompletableFuture<Throwable> registeredException = new CompletableFuture<>();
Mono.usingWhen(Mono.just(new Object()),
                obj -> Mono.just(obj.hashCode()),
                obj -> Mono.error(new IOException("mycleanup")))
        .subscribe(null, registeredException::complete);
Throwable exception = registeredException.join();
exception.printStackTrace();
assert exception.getClass().equals(RuntimeException.class);
assert exception.getCause().getClass().equals(IOException.class);
assert exception.getCause().getMessage().equals("mycleanup");
```
And it's stacktrace:
```
java.lang.RuntimeException: Async resource cleanup failed after onComplete
	at reactor.core.publisher.FluxUsingWhen$CommitInner.onError(FluxUsingWhen.java:520)
        ...reactor stacktrace removed...
Caused by: java.io.IOException: cleanup
	at com.acme.ReactorTest.lambda$main$1(ReactorTest.java:14)
	at reactor.core.publisher.FluxUsingWhen$UsingWhenSubscriber.onComplete(FluxUsingWhen.java:374)
	... 12 more
```

**Comment by OlegDokuka** [comment]
@alopukhov thanks for reporting. Feel free to contribute and improve javadocs!

**Comment by untaljohanperez** [comment]
For folks wondering then what to do:
```
process()
    .retryWhen(Retry.backoff(maxAttempts, minBackoff).filter(e -> e instanceof MySuperCustomeException))
    .onErrorMap(Exceptions::isRetryExhausted, Throwable::getCause);
```
https://github.com/reactor/reactor-core/issues/2052

**Comment by chemicL** [comment]
This issue was raised in 2022; a meaningful workaround has been posted over a year ago and since nobody was interested in contributing a javadoc improvement, I'm closing the issue. Feel free to reopen in case someone wants to contribute.
