### ISSUE TITLE
enableAutomaticContextPropagation - UnsupportedOperationException: Instances shouldn't be used/exposed as Queue outside of Reactor operators.

### ISSUE THREAD

**Issue by kressi** [reactor/reactor-core#3363]
## Expected Behavior
R2DBC can be used to query data.

## Actual Behavior
```text
java.lang.UnsupportedOperationException: Although QueueSubscription extends Queue it is purely internal and only guarantees support for poll/clear/size/isEmpty. Instances shouldn't be used/exposed as Queue outside of Reactor operators.
        at reactor.core.publisher.ContextPropagation$ContextQueue.peek(ContextPropagation.java:376)
        at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.onNext(ReactorNettyClient.java:811)
        at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.onNext(ReactorNettyClient.java:719)
        at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:128)
        at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854)
        at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:224)
        at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:224)
        at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:294)
        at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:403)
        at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:411)
        at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:113)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

## Steps to Reproduce

```java
Hooks.enableAutomaticContextPropagation();
```

## Your Environment

* io.projectreactor:reactor-core:3.5.3
* io.projectreactor.netty:reactor-netty-core:1.1.3
* org.springframework.boot:spring-boot:3.0.3
* org.postgresql:r2dbc-postgresql:1.0.1.RELEASE
* JVM version (`java -version`): 17

**Comment by chemicL** [comment]
Thank you for the report. That is indeed an error on our end.

The immediate cause for it is the new queue-wrapping hook we register. The wrapper throws in the [`peek()` method](https://github.com/reactor/reactor-core/blob/main/reactor-core/src/main/java/reactor/core/publisher/ContextPropagation.java#L376).

That, combined with a fact that r2dbc uses `Queues` in a way probably not anticipated when the queue wrapping mechanism was introduced, blows up in its [custom operator implementation](https://github.com/pgjdbc/r2dbc-postgresql/blob/main/src/main/java/io/r2dbc/postgresql/client/ReactorNettyClient.java#L811).

A quick fix would be to delegate to the original queue instead of throwing.

However, we need to think a bit more on the consequences of the current situation.

Our implementation assumes the `Queues` class to be used for implementing operators, that interact with the wrapped `Queue` instances in `QueueSubscription` scenarios in case of operator fusion. As the import of [`reactor.core.Fuseable.QueueSubscription.NOT_SUPPORTED_MESSAGE`](https://github.com/reactor/reactor-core/blob/main/reactor-core/src/main/java/reactor/core/publisher/ContextPropagation.java#L42) tells.

We'll discuss it and come up with something, this has high priority.

**Comment by chemicL** [comment]
I submitted a PR to fix the current situation. To better handle the concern introduced by the wrapper we are using, I created another issue which describes what we intend to change: #3369

**Comment by kressi** [comment]
> @kressi please try the latest snapshot (3.5.4-SNAPSHOT) and let us know if you encounter any more problems. Thanks in advance.

@chemicL Thank you! Verified, Ii works as expected now.
