### ISSUE TITLE
Enhance blockhound integration to allow blocking calls in `FutureTask.handlePossibleCancellationInterrupt`

### ISSUE THREAD

**Issue by OlegDokuka** [reactor/reactor-core#3512]
# Problem

The `shouldNotReportWorkerScheduledFutureTask` test is failing randomly with the following cause: 

```
13:02:12.060 [foo-768] ERROR reactor.core.scheduler.Schedulers - Scheduler worker in group main failed with an uncaught exception
reactor.blockhound.BlockingOperationError: Blocking call! java.lang.Thread.yield
	at java.lang.Thread.yield(Thread.java)
	at java.util.concurrent.FutureTask.handlePossibleCancellationInterrupt(FutureTask.java:336)
	at java.util.concurrent.FutureTask.run(FutureTask.java:284)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
13:02:12.173 [foo-1003] ERROR reactor.core.scheduler.Schedulers - Scheduler worker in group main failed with an uncaught exception
reactor.blockhound.BlockingOperationError: Blocking call! java.lang.Thread.yield
	at java.lang.Thread.yield(Thread.java)
	at java.util.concurrent.FutureTask.handlePossibleCancellationInterrupt(FutureTask.java:336)
	at java.util.concurrent.FutureTask.run(FutureTask.java:284)
13:02:12.992 [foo-2386] ERROR reactor.core.scheduler.Schedulers - Scheduler worker in group main failed with an uncaught exception
reactor.blockhound.BlockingOperationError: Blocking call! java.lang.Thread.yield
	at java.lang.Thread.yield(Thread.java)
	at java.util.concurrent.FutureTask.handlePossibleCancellationInterrupt(FutureTask.java:336)
	at java.util.concurrent.FutureTask.run(FutureTask.java:284)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```
 
# Solution

Edit `ReactorBlockHoundIntegrationTest` and allow blocking call for `java.util.concurrent.FutureTask.handlePossibleCancellationInterrupt`

**Comment by tejavenkatlanka** [comment]
Hi @OlegDokuka , added blocking call for the java.util.concurrent.FutureTask.handlePossibleCancellationInterrupt
please review and let me know if any update is need

**Comment by chemicL** [comment]
On my machine each run of the test is above 700ms. Perhaps on slower machines it can be a multiple of that. I will comment on the PR with a suggestion to increase the timeout. The implementation looks correct from my point of view.
