### ISSUE TITLE
flaky test  `TimedSchedulerTest > schedulePeriodicallyTimesOneRunInActiveAndAllRunsInCompleted`

### ISSUE THREAD

**Issue by OlegDokuka** [reactor/reactor-core#3604]
```
TimedSchedulerTest > schedulePeriodicallyTimesOneRunInActiveAndAllRunsInCompleted() FAILED
    org.opentest4j.AssertionFailedError: [#completed] 
    expected: 3L
     but was: 2L
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at reactor.core.observability.micrometer.TimedSchedulerTest.schedulePeriodicallyTimesOneRunInActiveAndAllRunsInCompleted(TimedSchedulerTest.java:213)
```

also 

```
TimedSchedulerTest > schedulePeriodicallyIsCorrectlyMetered() FAILED
    org.opentest4j.AssertionFailedError: [completed counter tracks all iterations] 
    expected: 5L
     but was: 4L
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at reactor.core.observability.micrometer.TimedSchedulerTest.schedulePeriodicallyIsCorrectlyMetered(TimedSchedulerTest.java:259)
```

**Comment by Nicolas125841** [comment]
Hello, 

I poked around, and it seems like the issue is caused by how `parent.completedTasks.wrap(this.task)` wraps the task in `TimedRunnable`:

```java
@Override
public void record(Runnable f) {
    final long s = clock.monotonicTime();
    try {
        f.run();
    }
    finally {
        final long e = clock.monotonicTime();
        record(e - s, TimeUnit.NANOSECONDS);
    }
}
```

Since the completion recording takes place after latch.countDown is called, latch.await could return before record is called.

I'm not 100% if this is right, but tracking the wrapped runnable execution (includes the recording) with a hook seems to work:

```java
//...setup

CountDownLatch latch = new CountDownLatch(3);

Schedulers.onScheduleHook("test", task -> () -> {
  try {
    task.run();
  }
  finally {
    latch.countDown();
  }
});

Disposable d = test.schedulePeriodically(() -> virtualClock.add(Duration.ofMillis(500)), 100, 100, TimeUnit.MILLISECONDS);

latch.await(1, TimeUnit.SECONDS);
d.dispose();

//assertions & cleanup...
```

Does this look reasonable? (the other test appears to fail the same way)

**Comment by chemicL** [comment]
@Nicolas125841 That sounds like a neat improvement for this test class. Are you interested in opening a PR?

**Comment by Nicolas125841** [comment]
@chemicL Sounds good. I'll get a PR started later tonight.

**Comment by chemicL** [comment]
@Nicolas125841 please do. 3.5.x would be a good choice.
