### ISSUE TITLE
BoundedElasticThreadPerTaskSchedulerTest > ensuresTasksScheduling() FAILED

### ISSUE THREAD

**Issue by chemicL** [reactor/reactor-core#3772]
```
BoundedElasticThreadPerTaskSchedulerTest > ensuresTasksScheduling() FAILED
    org.opentest4j.AssertionFailedError: 
    Expecting value to be true but was false
        at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
        at reactor.core.scheduler.BoundedElasticThreadPerTaskSchedulerTest.ensuresTasksScheduling(BoundedElasticThreadPerTaskSchedulerTest.java:78)
```

* Reactor version(s) used: 3.6.4
* JVM version (`java -version`): Java_Temurin-Hotspot_jdk/21.0.2-13/x64
* OS and version (eg `uname -a`): Ubuntu 22.0 LTS

**Comment by injae-kim** [comment]
```java
	@Test
	public void ensuresTasksScheduling() throws InterruptedException {
		CountDownLatch latch = new CountDownLatch(1);

		Disposable disposable = scheduler.schedule(latch::countDown);

		Assertions.assertThat(latch.await(5, TimeUnit.SECONDS)).isTrue();

                // AS-IS
		Assertions.assertThat(disposable.isDisposed()).isTrue();
                // TO-BE
		await().untilAsserted(() -> disposable.isDisposed()).isTrue());
	}
```
Hmm how about using `await().untilAsserted(..)` to check `disposable.isDisposed()).isTrue()`?

Cause `disposable.dispose()` is not finished yet right after latch reaches zero!

**Comment by chemicL** [comment]
That sounds correct. Are you interested in a contribution?

**Comment by injae-kim** [comment]
https://github.com/reactor/reactor-core/pull/3779 my friend who really loves opensource create fix PR! PTAL 🙇
