### ISSUE TITLE
FluxBufferWhenTest > timedOutBuffersDontLeak() FAILED

### ISSUE THREAD

**Issue by chemicL** [reactor/reactor-core#3782]
This test failed on CI on 3.4.x branch:

```
Test class reactor.core.publisher.FluxReplayTest

FluxBufferWhenTest > timedOutBuffersDontLeak() FAILED
    org.opentest4j.AssertionFailedError: [final GC collects all] 
    expected: 400L
     but was: 321L
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at reactor.core.publisher.FluxBufferWhenTest.timedOutBuffersDontLeak(FluxBufferWhenTest.java:167)
```

**Comment by chemicL** [comment]
3.4.x is going out of OSS support soon. Let's re-create should this happen in supported versions.
