### ISSUE TITLE
Failing while building reactor-core version 3.4.18 using ./gradlew build (io.projectreactor:reactor-core:3.4.18)

### ISSUE THREAD

**Issue by shivsrivastava** [reactor/reactor-core#3803]
Package artifact id:io.projectreactor

source code url: https://github.com/reactor/reactor-core/tree/v3.4.18

Issue Description: Failing while building reactor-core version 3.4.18 using ./gradlew build (io.projectreactor:reactor-core:3.4.18)

JDK Version: 1.8

Build CMD: ./gradlew build

MVN Version: NA

gradle version - NA

Error Log: 

Throwable that failed the check:

    java.lang.AssertionError:
    Expecting actual:
      "foo"
    and actual:
      ThisIsNotAQueue
    to refer to the same object
        at reactor.core.QueueSubscriptionTest.lambda$assertJShouldProperlyFormatQueueSubscription$0(QueueSubscriptionTest.java:80)
        at reactor.core.QueueSubscriptionTest.assertJShouldProperlyFormatQueueSubscription(QueueSubscriptionTest.java:79)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
        at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
        at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(Time

attachement: build log attached (jdk 1.8)
[Failed_jdk_8.txt](https://github.com/reactor/reactor-core/files/15158403/Failed_jdk_8.txt)

OS: windows 10

**Comment by chemicL** [comment]
Is there any particular reason you are building 3.4.18? The latest 3.4.x release is 3.4.37. I'm not sure what happened in your build but 3.4.18 was released 2 years ago and we can't do much to it at this point in time. What is your end goal?

**Comment by chemicL** [comment]
Actually, I’ll close this issue as it seems invalid. Please reopen in case this happens in the up-to-date build with no code changes.

**Comment by shivsrivastava** [comment]
> Is there any particular reason you are building 3.4.18? The latest 3.4.x release is 3.4.37. I'm not sure what happened in your build but 3.4.18 was released 2 years ago and we can't do much to it at this point in time. What is your end goal?

It is our project requirement and can not go for latest version. Please help

**Comment by chemicL** [comment]
@shivsrivastava I really don't know how I could help.
