### ISSUE TITLE
dispatchOn raises exception when prefetch=1

### ISSUE THREAD

**Issue by evacchi** [reactor/reactor-core#44]
Problem not occurring in RxJava (see also https://gist.github.com/evacchi/ae362310dec8aacfdef4)

```java
package rxplayground;

import reactor.core.publisher.Flux;
import reactor.core.publisher.SchedulerGroup;

import java.util.Iterator;
import java.util.function.Function;

public class ReactorPublish {
    static class Iter implements Iterator<Long> {
        long count = 0;
        @Override public boolean hasNext() { return true; }
        @Override public Long next() { return count++; }
    };
    final Flux<Long> doubleFlux = Flux.fromIterable(Iter::new).as(Shared());

    void stream() {

        doubleFlux.as(DropOld()).map(this::fastComputation).consume(i -> System.out.println("1) " + i));
        doubleFlux.as(DropOld()).map(this::slowComputation).consume(i -> System.err.println("2) " + i));
    }

    public static <T> Function<Flux<T>, Flux<T>> DropOld() {
        return (flux) -> flux.onBackpressureLatest().dispatchOn(SchedulerGroup.single(), 1);
    }

    public static <T> Function<Flux<T>, Flux<T>> Shared() {
        return (flux) -> flux.publishOn(SchedulerGroup.single()).publish().refCount();
    }


    <T> T fastComputation(T in) {
        try {
            Thread.sleep(200);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        return in;
    }

    <T> T slowComputation(T in) {
        try {
            Thread.sleep(500);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        return in;
    }

    public static void main(String[] args) throws InterruptedException {
        new ReactorPublish().stream();
        Thread.currentThread().join();
    }
}
```

```java
2016-03-16 12:01:30 ERROR r.c.p.SchedulerGroup:477 - Unrouted exception
reactor.core.util.Exceptions$UpstreamException: java.lang.IllegalStateException: Queue is full?!
    at reactor.core.util.Exceptions.failUpstream(Exceptions.java:106)
    at reactor.core.util.Exceptions.onErrorDropped(Exceptions.java:153)
    at reactor.core.subscriber.ConsumerSubscriber.doError(ConsumerSubscriber.java:141)
    at reactor.core.subscriber.ConsumerSubscriber.onError(ConsumerSubscriber.java:128)
    at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:137)
    at reactor.core.publisher.FluxDispatchOn$DispatchOnSubscriber.checkTerminated(FluxDispatchOn.java:493)
    at reactor.core.publisher.FluxDispatchOn$DispatchOnSubscriber.runAsync(FluxDispatchOn.java:417)
    at reactor.core.publisher.FluxDispatchOn$DispatchOnSubscriber.run(FluxDispatchOn.java:476)
    at reactor.core.publisher.SchedulerGroup$TaskSubscriber.onNext(SchedulerGroup.java:1081)
    at reactor.core.publisher.SchedulerGroup$TaskSubscriber.onNext(SchedulerGroup.java:1063)
    at reactor.core.publisher.TopicProcessor$TopicSubscriberLoop.run(TopicProcessor.java:877)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Queue is full?!
    at reactor.core.publisher.FluxDispatchOn$DispatchOnSubscriber.onNext(FluxDispatchOn.java:259)
    at reactor.core.publisher.FluxLatest$LatestSubscriber.drain(FluxLatest.java:177)
    at reactor.core.publisher.FluxLatest$LatestSubscriber.request(FluxLatest.java:97)
    at reactor.core.publisher.FluxDispatchOn$DispatchOnSubscriber.runAsync(FluxDispatchOn.java:432)
    ... 7 more
```

**Comment by akarnokd** [comment]
The bug is in `onBackpressureLatest` not decrementing the known requested amount properly and overwhelms the receiver.

Fixed via https://github.com/reactor/reactor-core/commit/e5a23a210351f46542c7832083298db84004c64c

**Comment by evacchi** [comment]
has this been published to https://repo.spring.io/libs-snapshot ? I can't seem to be able to download an updated jar, all I get is `reactor-core-2.5.0.BUILD-20160311.231742-482.jar`

**Comment by akarnokd** [comment]
Doesn't seem so. @sdeleuze any ideas?

**Comment by sdeleuze** [comment]
@akarnokd I seems the build failed due to [a broken test](https://build.spring.io/browse/REACTOR-RNEXT-838) but tests are green locally with master on my laptop. I will try a new build asap, and will keep you informed.

**Comment by sdeleuze** [comment]
@evacchi The build is green now, could you please test again with the snapshot?

**Comment by smaldini** [comment]
ping

**Comment by smaldini** [comment]
Closing for now - please re-open @evacchi if it didn't solve it in the end :+1:
