### ISSUE TITLE
Http post in flux question

### ISSUE THREAD

**Issue by skoulouris** [reactor/reactor-core#500]
Hi guys,

Is the following code correct for what I'm trying to achieve? I contact service A to get a flux of dossiers, each dossier gets mapped to a service B dossier and a http post is to be executed. 

```java
        WebClient client = WebClient.create();
        client
                .get()
                .uri("xxx/rest/dossiers")
                .accept(MediaType.APPLICATION_JSON)
                .exchange()
                .flatMap(response -> response.bodyToFlux(Dossier.class))
                .filter(dossier -> "someBrand".equals(dossier.getBrandId()))
                .map(dossier -> new OtherServiceDossier())
                .flatMap(otherDossier -> client.post()
                        .uri("yyy/rest/dossiers")
                        .contentType(MediaType.APPLICATION_JSON)
                        .exchange(BodyInserters.fromObject(otherDossier)))
                .subscribe(clientResponse -> {
                    try {
                        if (HttpStatus.CREATED == clientResponse.statusCode()) {
                            LOGGER.info("created dossier");
                        } else {
                            LOGGER.error("failed creating dossier");
                        }
                    } catch (Exception e) {
                        LOGGER.error("", e);
                    }
                }, error -> LOGGER.error("failed creating dossier", error));`
```

What I see when i run the code is the following: Most requests are executed successfully but some throw the following exception when requesting the statusCode from the clientResponse clientResponse.statusCode(). 

```
2017-03-22 12:20:00.335 ERROR 10568 --- [ctor-http-nio-3] n.p.application.scripts.Application      : created dossier
2017-03-22 12:20:00.336 ERROR 10568 --- [ctor-http-nio-3] n.p.application.scripts.Application      :  created dossier
2017-03-22 12:20:00.344 ERROR 10568 --- [ctor-http-nio-3] n.p.application.scripts.Application      : 

java.lang.NullPointerException: null
	at org.springframework.http.client.reactive.ReactorClientHttpResponse.getStatusCode(ReactorClientHttpResponse.java:73) ~[spring-web-5.0.0.BUILD-SNAPSHOT.jar:5.0.0.BUILD-SNAPSHOT]
	at org.springframework.web.reactive.function.client.DefaultClientResponse.statusCode(DefaultClientResponse.java:66) ~[spring-webflux-5.0.0.BUILD-SNAPSHOT.jar:5.0.0.BUILD-SNAPSHOT]
	at net.persgroep.application.scripts.Application.lambda$commandLineRunner$4(Application.java:46) ~[main/:na]
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:139) ~[reactor-core-3.0.5.RELEASE.jar:3.0.5.RELEASE]
	at reactor.core.publisher.FluxRetry$RetrySubscriber.onNext(FluxRetry.java:64) ~[reactor-core-3.0.5.RELEASE.jar:3.0.5.RELEASE]
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.innerNext(FluxFlatMap.java:749) ~[reactor-core-3.0.5.RELEASE.jar:3.0.5.RELEASE]
	at reactor.core.publisher.FluxFlatMap$FlatMapInner.onNext(FluxFlatMap.java:945) ~[reactor-core-3.0.5.RELEASE.jar:3.0.5.RELEASE]
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114) ~[reactor-core-3.0.5.RELEASE.jar:3.0.5.RELEASE]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:165) ~[reactor-core-3.0.5.RELEASE.jar:3.0.5.RELEASE]
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114) ~[reactor-core-3.0.5.RELEASE.jar:3.0.5.RELEASE]
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114) ~[reactor-core-3.0.5.RELEASE.jar:3.0.5.RELEASE]
	at reactor.core.publisher.FluxRetryPredicate$RetryPredicateSubscriber.onNext(FluxRetryPredicate.java:78) ~[reactor-core-3.0.5.RELEASE.jar:3.0.5.RELEASE]
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:99) ~[reactor-core-3.0.5.RELEASE.jar:3.0.5.RELEASE]
	at reactor.ipc.netty.channel.PooledClientContextHandler.fireContextActive(PooledClientContextHandler.java:84) ~[reactor-netty-0.6.1.RELEASE.jar:0.6.1.RELEASE]
	at reactor.ipc.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:191) ~[reactor-netty-0.6.1.RELEASE.jar:0.6.1.RELEASE]
	at reactor.ipc.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:357) ~[reactor-netty-0.6.1.RELEASE.jar:0.6.1.RELEASE]
	at reactor.ipc.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:366) ~[reactor-netty-0.6.1.RELEASE.jar:0.6.1.RELEASE]
	at reactor.ipc.netty.channel.ChannelOperations.onHandlerTerminate(ChannelOperations.java:442) ~[reactor-netty-0.6.1.RELEASE.jar:0.6.1.RELEASE]
	at reactor.ipc.netty.channel.ChannelOperationsHandler.channelInactive(ChannelOperationsHandler.java:101) ~[reactor-netty-0.6.1.RELEASE.jar:0.6.1.RELEASE]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246) ~[netty-all-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:232) ~[netty-all-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:225) ~[netty-all-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:360) ~[netty-all-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:325) ~[netty-all-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246) ~[netty-all-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:232) ~[netty-all-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:225) ~[netty-all-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1329) ~[netty-all-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246) ~[netty-all-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:232) ~[netty-all-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:908) ~[netty-all-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:744) ~[netty-all-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-all-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) ~[netty-all-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445) ~[netty-all-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[netty-all-4.1.8.Final.jar:4.1.8.Final]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_74]
2017-03-22 12:20:00.348 ERROR 10568 --- [ctor-http-nio-3] n.p.application.scripts.Application      : created `dossier`
```

**Comment by simonbasle** [comment]
Hi @skoulouris, this is more of a `Spring Framework` issue/question, can you reach out to them by opening a similar ticket on [Spring's JIRA](https://jira.spring.io/browse/SPR/) instead?
