### ISSUE TITLE
InterruptedException after receiving final value from Flux subscription

### ISSUE THREAD

**Issue by blake-bauman** [reactor/reactor-core#507]
When subscribing to a Publisher via Flux, and the Publisher calls onComplete(), it seems that the thread gets a Thread.interrupt() call.  So, when the consumer receiving the final value makes any calls that check the interrupt status (i.e. Thread.interrupted()), an InterruptedException is thrown.

One such method that checks the interrupted status is CountdownLatch.await() which is used by many frameworks, including reactor-core.  An easy way to reproduce this is with making a Mono.block() call from the consumer that receives values from a Flux subscription.

Subscription:
```java
    Flux.from(myPublisher)
           .subscribeOn(Schedulers.newSingle("foo"))
           .subscribe(element -> receive(element), e -> onError(e), () -> finish());
```

Receive:
```java
    void receive(Object element) {
        final String string = Mono.from((Publisher<String>)subscriber -> {
            subscriber.onSubscribe(new Subscription() {

                @Override
                public void request(long n) {
                    subscriber.onNext(“”);
                }

                @Override
                public void cancel() {
                    // do something
                }

            });
        }).subscribeOn(myScheduler).doOnSuccess(element -> {
            LOGGER.debug(“Complete!”);
        }).doOnError(e -> {
            LOGGER.error(“Failure!”, e);
        }).block();
    }
```

The exception received is:
```java
reactor.core.Exceptions$ReactiveException: java.lang.InterruptedException
	at reactor.core.Exceptions.propagate(Exceptions.java:219) ~[reactor-core-3.0.6.BUILD-SNAPSHOT.jar:3.0.6.BUILD-SNAPSHOT]
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:79) ~[reactor-core-3.0.6.BUILD-SNAPSHOT.jar:3.0.6.BUILD-SNAPSHOT]
	at reactor.core.publisher.Mono.block(Mono.java:1303) ~[reactor-core-3.0.6.BUILD-SNAPSHOT.jar:3.0.6.BUILD-SNAPSHOT]
	at MySubscriber.receive(MySubscriber.java:133) [classes/:na]
	at MySubscriber.lambda$0(MySubscriber.java:99) [classes/:na]
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:132) ~[reactor-core-3.0.6.BUILD-SNAPSHOT.jar:3.0.6.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:390) ~[reactor-core-3.0.6.BUILD-SNAPSHOT.jar:3.0.6.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:478) ~[reactor-core-3.0.6.BUILD-SNAPSHOT.jar:3.0.6.BUILD-SNAPSHOT]
	at reactor.core.scheduler.ImmediateScheduler$ImmediateSchedulerWorker.schedule(ImmediateScheduler.java:72) ~[reactor-core-3.0.6.BUILD-SNAPSHOT.jar:3.0.6.BUILD-SNAPSHOT]
	at reactor.core.scheduler.ImmediateScheduler$ImmediateSchedulerWorker.schedule(ImmediateScheduler.java:63) ~[reactor-core-3.0.6.BUILD-SNAPSHOT.jar:3.0.6.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.trySchedule(FluxPublishOn.java:290) ~[reactor-core-3.0.6.BUILD-SNAPSHOT.jar:3.0.6.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.onNext(FluxPublishOn.java:231) ~[reactor-core-3.0.6.BUILD-SNAPSHOT.jar:3.0.6.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.onNext(FluxSubscribeOn.java:129) ~[reactor-core-3.0.6.BUILD-SNAPSHOT.jar:3.0.6.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:173) ~[reactor-core-3.0.6.BUILD-SNAPSHOT.jar:3.0.6.BUILD-SNAPSHOT]
	at MyPublisher$MySubscription.request(MyPublisher.java:318) ~[classes/:na]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:122) ~[reactor-core-3.0.6.BUILD-SNAPSHOT.jar:3.0.6.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.requestUpstream(FluxSubscribeOn.java:117) ~[reactor-core-3.0.6.BUILD-SNAPSHOT.jar:3.0.6.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.onSubscribe(FluxSubscribeOn.java:110) ~[reactor-core-3.0.6.BUILD-SNAPSHOT.jar:3.0.6.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onSubscribe(FluxPeek.java:153) ~[reactor-core-3.0.6.BUILD-SNAPSHOT.jar:3.0.6.BUILD-SNAPSHOT]
	at MySQLPublisher.subscribe(MyPublisher.java:140) ~[classes/:na]
	at reactor.core.publisher.FluxSource.subscribe(FluxSource.java:65) ~[reactor-core-3.0.6.BUILD-SNAPSHOT.jar:3.0.6.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxLog.subscribe(FluxLog.java:50) ~[reactor-core-3.0.6.BUILD-SNAPSHOT.jar:3.0.6.BUILD-SNAPSHOT]
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:174) ~[reactor-core-3.0.6.BUILD-SNAPSHOT.jar:3.0.6.BUILD-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121]
Caused by: java.lang.InterruptedException: null
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1302) ~[na:1.8.0_121]
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231) ~[na:1.8.0_121]
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:75) ~[reactor-core-3.0.6.BUILD-SNAPSHOT.jar:3.0.6.BUILD-SNAPSHOT]
	... 30 common frames omitted
```

If I add a publishOn() call to the Flux subscription, using a third Scheduler, we can get around the problem for now.

###### (Not a Contribution)

**Comment by simonbasle** [comment]
I can see a number of problems with your code:

1. First off, what are `myPublisher`? Have you written your own `Publisher`? That is a code smell in Reactor, you shouldn't have to implement a `Publisher`, but rather rely in order of preference on: combining operators, using Flux/Mono's `create`/`generate`, using a `Processor`...

2. The `Publisher` and `Subscription` in `receive` don't really make sense to me either... See item 1) first. The subscription completely discards the original value, `onComplete` is never called, etc...

3. You `block()` inside an `onNext()` call, which is a huge code smell. You probably want to `flatMap` before the `subscribe` if you need to further act on your elements...

Trying a few alternatives with the scheduler and using a Reactor publisher as source, I was unable to reproduce your issue, which makes me think that this is probably either originating in your custom source `Publisher`, the weird `receive` method or a combination of the two...

**Comment by blake-bauman** [comment]
Keep in mind that this (obviously) isn't the full code, just a sample I whittled down to demonstrate the problem.  There's a lot more to the actual code, but I can recreate the problem very easily this way.

1.  Yes, I wrote a Publisher implementation.  Of all the available options, it seemed the best for my use case.  If no one's supposed to use it, then maybe deprecate it?  Or document something?  It looked like just one of many viable options, and it fit what I was trying to do, so I went with it.

2.  It's not supposed to make sense.  It's just something I threw together that was very simple and could demonstrate the problem.  The real code is doing something different, but has the same result.  Even using Mono.fromCallable() I still got the same exception.  The point was, the actual code never even gets called because the exception is immediately thrown in the block().

3. Again, the block() was just an example because it happens to demonstrate the issue.  It's not the actual code.  The point was I'm trying to make a call that happens to call Thread.isInterrupted() underneath.

What I've noticed in reactor-core (through using my debugger) is that all around the Scheduler cleanup code, I see calls to Future.cancel() which does an interrupt() if you pass true as the parameter.  Previously (3.0.3 and prior), false was being passed.  This seems to happen when the Subscription calls Subscriber.onComplete() and not all of the values have been received yet.  My code is not calling interrupt().  I've also noticed that simply adding publishOn() to my subscription gets around the problem because it forces receive() to be using a different thread which has not been interrupted by onComplete().  I'll work on a complete sample that can demonstrate the problem.

**Comment by simonbasle** [comment]
Yeah, `Publisher` is the reactive-streams interface, which aims at interoperability between reactive libraries, so it cannot be removed or hidden. But implementing the interface isn't sufficient as there is a lot of rules and behavior defined in the spec that you MUST conform to. That is why we generally don't recommend to write a `Publisher`, as it is non-trivial to get right (at best).

I understand point 2 and 3, that these where just silly examples that allowed you to reproduce the issue. Thing is, the reproduction case isn't runnable as is. I had to make adjustments, and then it wouldn't demonstrate the issue anymore.

The `Future.cancel()` changes are supposed to occur only if task submission is rejected, so when a `Scheduler` has been `dispose()` (which shouldn't be the case here).

**Comment by blake-bauman** [comment]
I can certainly accept that I didn't get the Publisher part right.  I'll be looking at alternative solutions in that area.  For now, I'll try to come up with a basic, runnable example that shows the InterruptedException.

**Comment by blake-bauman** [comment]
This is an example I can get to fail every time.  Adding a publishOn() call to the Flux causes this to succeed.  Removing the limitRate() causes this to succeed.

```java
package foo;

import org.reactivestreams.Publisher;
import org.reactivestreams.Subscription;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import reactor.core.scheduler.Schedulers;

public class SimpleExample {
    private static final Logger LOGGER = LoggerFactory.getLogger(SimpleExample.class);

    public static void main(final String... args) {
        new SimpleExample().run();
    }

    public SimpleExample() {
    }

    public void run() {
        Flux.from((Publisher<String>)subscriber -> {
            subscriber.onSubscribe(new Subscription() {
                private int totalCount;

                @Override
                public void request(long n) {
                    for (int i = 0; i < n; i++) {
                        if (totalCount++ < 317) {
                            subscriber.onNext(String.valueOf(totalCount));
                        }
                        else {
                            subscriber.onComplete();
                        }
                    }
                }

                @Override
                public void cancel() {
                    // do nothing
                }
            });
        }).log().subscribeOn(Schedulers.newSingle("subscribe"))
//            .publishOn(Schedulers.newParallel("publish"))   // Uncomment this and it works.
            .limitRate(10)   // Comment this out and it works.
            .subscribe(value -> receive(value), e -> LOGGER.error("Subscription Failed!", e), () -> LOGGER.info("Subscription Complete!"));
    }

    private void receive(final String value) {
        LOGGER.info("Subscription Received '{}'", value);
        final String downstreamValue = Mono.fromCallable(() -> {
            return "Foo";
        }).log().subscribeOn(Schedulers.newParallel("receive")).doOnSuccess(element -> {
            LOGGER.info("Downstream Complete!");
        }).doOnError(e -> {
            LOGGER.error("Downstream Failed!", e);
        }).block();

        LOGGER.info("Downstream value '{}'", downstreamValue);
    }
}
```

Here's the log snippet I get at the end when it fails:
```java
12:03:34.440 [subscribe-1] INFO reactor.Flux.Source.1 - request(8)
12:03:34.440 [subscribe-1] INFO reactor.Flux.Source.1 - onNext(313)
12:03:34.440 [subscribe-1] INFO reactor.Flux.Source.1 - onNext(314)
12:03:34.440 [subscribe-1] INFO reactor.Flux.Source.1 - onNext(315)
12:03:34.440 [subscribe-1] INFO reactor.Flux.Source.1 - onNext(316)
12:03:34.440 [subscribe-1] INFO reactor.Flux.Source.1 - onNext(317)
12:03:34.440 [subscribe-1] INFO reactor.Flux.Source.1 - onComplete()
12:03:34.440 [subscribe-1] INFO foo.SimpleExample - Subscription Received '313'
12:03:34.440 [receive-7] INFO reactor.Mono.Callable.314 - | onSubscribe([Fuseable] Operators.MonoSubscriber)
12:03:34.440 [subscribe-1] INFO reactor.Mono.Callable.314 - | cancel()
12:03:34.442 [subscribe-1] INFO reactor.Flux.Source.1 - cancel()
12:03:34.444 [subscribe-1] ERROR foo.SimpleExample - Subscription Failed!
reactor.core.Exceptions$ReactiveException: java.lang.InterruptedException
	at reactor.core.Exceptions.propagate(Exceptions.java:219)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:79)
	at reactor.core.publisher.Mono.block(Mono.java:1303)
	at foo.SimpleExample.receive(SimpleExample.java:75)
	at foo.SimpleExample.lambda$1(SimpleExample.java:64)
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:132)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:390)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:478)
	at reactor.core.scheduler.ImmediateScheduler$ImmediateSchedulerWorker.schedule(ImmediateScheduler.java:72)
	at reactor.core.scheduler.ImmediateScheduler$ImmediateSchedulerWorker.schedule(ImmediateScheduler.java:63)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.trySchedule(FluxPublishOn.java:290)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.onNext(FluxPublishOn.java:231)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.onNext(FluxSubscribeOn.java:129)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:173)
	at foo.SimpleExample$1.request(SimpleExample.java:49)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:122)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.requestUpstream(FluxSubscribeOn.java:117)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.onSubscribe(FluxSubscribeOn.java:110)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onSubscribe(FluxPeek.java:153)
	at foo.SimpleExample.lambda$0(SimpleExample.java:42)
	at reactor.core.publisher.FluxSource.subscribe(FluxSource.java:65)
	at reactor.core.publisher.FluxLog.subscribe(FluxLog.java:50)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:174)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.InterruptedException: null
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1302)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:75)
	... 28 common frames omitted
```

**Comment by smaldini** [comment]
Hey @blake-bauman , there a re a few things to details the issue here, thanks for the report 👍 
- You are right we fully switched by default interruption for all schedulers
- The intent of interruption is specifically to unblock any blocking code using our schedulers on "cancel" especially.
- the Publisher test here is not respecting RS, you can refer to https://github.com/reactive-streams/reactive-streams-jvm/tree/master/tck if you want to implement a Publisher. It is a protocol so its easy to miss some behaviors. In your case you are missing reentrance limitation (and others checks). 
- the action of blocking inside any of the Java 8 callbacks used by our api (Function/Consumer/Supplier...) is at your very risk and we just discourage it. We expect non blocking callbacks or you need to apply more checks/controls. This applies to subscribe(Consumer). Usually only isolating in a thread via the publishOn/subscribeOn and any sequence splitting (flatMap/concatMap, parallel, zip, window, groupBy) allows for subsequent blocking in the immediate next or previous operator. 
- we use Work stealing so threads will propagate in the flow naturally if no other thread jump is explicitely set by the user.

It could be worth evaluating if we clear the interrupt flag on new scheduler worker assignment but it seems you see the problem in a same flow. In this test scenario i'm not sure we would be able to anticipate you are going to trigger a flow that blocks (therefore use await() which can be interrupted). We could provide blockUninterrupted or similar to clear the flag if any for the purpose. Alternatively you could isolate the block as suggested in the explanation before, add a publishOn just before your subscribe and isolate the blocking code in something like Schedulers.elastic() (designed for the purpose of variable blocking wait).

**Comment by blake-bauman** [comment]
Thanks for the feedback.  I'll use that compliance tool to verify my real Publisher and start researching alternatives that are more inline with recommendations.  I'm happy to make my code more bullet proof.  For the sample, though, yeah I didn't put much effort into making it perfect.  I was trying to simulate a Publisher that sends out "more than a handful" of items, but still a finite number of items.  My big concern was that this works just fine when there's no limitRate(), but fails when there is a limitRate().

For the blocking in a callback, we're not intending to deliberately block in our real code.  For the purposes of the sample, I didn't want to involve any 3rd-party dependencies, so I used something for demonstration purposes.  In the real code, it's making a call into 3rd-party code which I found (after a lot of digging) was making the Latch.await() call.

**Comment by blake-bauman** [comment]
I was able to recreate this problem using Flux.generate() (in 3.0.7).  I don't yet have a simple example to recreate the problem, but I'm using it with MongoDB to publish Document objects on a Flux from a tailable cursor.  My state object contains a reference to the MongoCursor and I'm calling close() in the stateConsumer to clean up the resources.
```java
Flux.generate(() -> initStream(),    // opens cursor
              (state, sink) -> processRequest(state, sink),
              state -> finish(state))   // closes cursor
    .subscribeOn(Schedulers.newSingle("foo"))
    .publishOn(Schedulers.newSingle("foo"));
```

This is throwing an InterruptedException when closing the cursor to release resources:
```java
com.mongodb.MongoInterruptedException: Interrupted acquiring a permit to retrieve an item from the pool 
	at com.mongodb.internal.connection.ConcurrentPool.acquirePermit(ConcurrentPool.java:186) ~[mongo-java-driver-3.4.2.jar:na]
	at com.mongodb.internal.connection.ConcurrentPool.get(ConcurrentPool.java:126) ~[mongo-java-driver-3.4.2.jar:na]
	at com.mongodb.connection.DefaultConnectionPool.getPooledConnection(DefaultConnectionPool.java:258) ~[mongo-java-driver-3.4.2.jar:na]
	at com.mongodb.connection.DefaultConnectionPool.get(DefaultConnectionPool.java:99) ~[mongo-java-driver-3.4.2.jar:na]
	at com.mongodb.connection.DefaultConnectionPool.get(DefaultConnectionPool.java:88) ~[mongo-java-driver-3.4.2.jar:na]
	at com.mongodb.connection.DefaultServer.getConnection(DefaultServer.java:86) ~[mongo-java-driver-3.4.2.jar:na]
	at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.getConnection(ClusterBinding.java:86) ~[mongo-java-driver-3.4.2.jar:na]
	at com.mongodb.operation.QueryBatchCursor.killCursor(QueryBatchCursor.java:261) ~[mongo-java-driver-3.4.2.jar:na]
	at com.mongodb.operation.QueryBatchCursor.close(QueryBatchCursor.java:147) ~[mongo-java-driver-3.4.2.jar:na]
	at com.mongodb.MongoBatchCursorAdapter.close(MongoBatchCursorAdapter.java:41) ~[mongo-java-driver-3.4.2.jar:na]
	at MyGenerator.finish(MyGenerator.java:47) ~[classes/:na]
	at MyGenerator.lambda$createStream$2(MyGenerator.java:32) [classes/:na]
	at reactor.core.publisher.FluxGenerate$GenerateSubscription.cleanup(FluxGenerate.java:304) ~[reactor-core-3.0.7.RELEASE.jar:3.0.7.RELEASE]
	at reactor.core.publisher.FluxGenerate$GenerateSubscription.slowPath(FluxGenerate.java:262) ~[reactor-core-3.0.7.RELEASE.jar:3.0.7.RELEASE]
	at reactor.core.publisher.FluxGenerate$GenerateSubscription.request(FluxGenerate.java:196) ~[reactor-core-3.0.7.RELEASE.jar:3.0.7.RELEASE]
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:131) ~[reactor-core-3.0.7.RELEASE.jar:3.0.7.RELEASE]
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.requestUpstream(FluxSubscribeOn.java:117) ~[reactor-core-3.0.7.RELEASE.jar:3.0.7.RELEASE]
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.onSubscribe(FluxSubscribeOn.java:110) ~[reactor-core-3.0.7.RELEASE.jar:3.0.7.RELEASE]
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onSubscribe(FluxPeekFuseable.java:164) ~[reactor-core-3.0.7.RELEASE.jar:3.0.7.RELEASE]
	at reactor.core.publisher.FluxGenerate.subscribe(FluxGenerate.java:82) ~[reactor-core-3.0.7.RELEASE.jar:3.0.7.RELEASE]
	at reactor.core.publisher.FluxLogFuseable.subscribe(FluxLogFuseable.java:53) ~[reactor-core-3.0.7.RELEASE.jar:3.0.7.RELEASE]
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:174) ~[reactor-core-3.0.7.RELEASE.jar:3.0.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121]
Caused by: java.lang.InterruptedException: null
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1326) ~[na:1.8.0_121]
	at java.util.concurrent.Semaphore.tryAcquire(Semaphore.java:409) ~[na:1.8.0_121]
	at com.mongodb.internal.connection.ConcurrentPool.acquirePermit(ConcurrentPool.java:180) ~[mongo-java-driver-3.4.2.jar:na]
	... 30 common frames omitted
```

It only seems to happen with tailable MongoCursors (cursorType(CursorType.TailableAwait)), so it's not easy to recreate.

Of course, calling Thread.interrupted() before MongoCursor.close(), it clears the interrupted state and there's no exception.

**Comment by simonbasle** [comment]
this seems to be a matter of when the cleanup happens: just before the `onComplete` vs just after (current behavior). It should be possible to swap the cleanup invocation to execute just before onComplete, I'll look into that.
