### ISSUE TITLE
ArrayStoreException when chaining then(Mono<V>) calls in 3.1.0.M2

### ISSUE THREAD

**Issue by jhaeyaert** [reactor/reactor-core#661]
Hi,

I currently use the 3.1.0.M2 reactor version and i discovered a strange exception when chaining 2 "then" calls. I couldn't find any issue talking about this behaviour so i decided to submit a new one (i hope this is not a duplicate).

<pre>
Exception in thread "main" java.lang.ArrayStoreException
	at java.lang.System.arraycopy(Native Method)
	at reactor.core.publisher.MonoThenIgnore.shift(MonoThenIgnore.java:69)
	at reactor.core.publisher.Mono.then(Mono.java:3002)
	...
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
</pre>

Below, you will find a reproductible case  :

```java
Flux.just("Good Morning", "Hello").then(Mono.just("Good Afternoon")).then(Mono.just("Bye")).subscribe(s -> System.out.println(s));
```

**Note** : it only happens when starting from Flux. 
**Second note** : if you include a map(s -> s) between the 2 then calls, the exception disappears :

```java
Flux.just("Good Morning", "Hello").then(Mono.just("Good Afternoon")).map(s -> s).then(Mono.just("Bye")).subscribe(s -> System.out.println(s));
```

Hope this will help.

**Comment by simonbasle** [comment]
thanks for reporting this, this definitely helps and is indeed a bug :(
It should only happen if you chain several `then` calls in a row, **starting from a `Flux`**.

As an alternative workaround, chaining a `.hide()` just before the first `then()` should work.
