### ISSUE TITLE
NPE: The mapper returned a null Publisher

### ISSUE THREAD

**Issue by asarkar** [reactor/reactor-core#741]
I've a Kotlin Boot `CommandLineRunner` application that looks like the following. It works fine when ran by `bootRun` but from an integration test, I keep getting a NPE.

```
Flux.fromIterable(groups.entries)
    .flatMap // omitted
    .filter // omitted
    .parallel()
    .runOn(Schedulers.parallel())
     // omitted
    .sequential()
    .sort(compareBy({ it.first }, { it.second.valid }, { it.second.url }))
    .collectMultimap(Pair<String, License>::first, Pair<String, License>::second)
    .map // omitted
    .doOnNext { eventPublisher.publishEvent(it) }
    .block(Duration.ofMinutes(applicationProperties.timeoutMinutes))
```

**Stacktrace**:

```
Caused by: java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:792)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:773)
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:760)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:328)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:138)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:117)
	... 23 more
Caused by: java.lang.NullPointerException: The mapper returned a null Publisher
	at java.util.Objects.requireNonNull(Objects.java:228)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:357)
	at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:174)
	at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:144)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:341)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:89)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:54)
	at reactor.core.publisher.FluxFlatMap.subscribe(FluxFlatMap.java:95)
	at reactor.core.publisher.FluxFilter.subscribe(FluxFilter.java:51)
	at reactor.core.publisher.ParallelSource.subscribe(ParallelSource.java:84)
	at reactor.core.publisher.ParallelRunOn.subscribe(ParallelRunOn.java:82)
	at reactor.core.publisher.ParallelFlatMap.subscribe(ParallelFlatMap.java:97)
	at reactor.core.publisher.ParallelFilter.subscribe(ParallelFilter.java:61)
	at reactor.core.publisher.ParallelFlatMap.subscribe(ParallelFlatMap.java:97)
	at reactor.core.publisher.ParallelFlatMap.subscribe(ParallelFlatMap.java:97)
	at reactor.core.publisher.ParallelMergeSequential.subscribe(ParallelMergeSequential.java:64)
	at reactor.core.publisher.MonoCollectList.subscribe(MonoCollectList.java:57)
	at reactor.core.publisher.MonoMapFuseable.subscribe(MonoMapFuseable.java:59)
	at reactor.core.publisher.FluxFlattenIterable.subscribe(FluxFlattenIterable.java:104)
	at reactor.core.publisher.MonoCollect.subscribe(MonoCollect.java:64)
	at reactor.core.publisher.MonoMapFuseable.subscribe(MonoMapFuseable.java:59)
	at reactor.core.publisher.MonoPeekFuseable.subscribe(MonoPeekFuseable.java:77)
	at reactor.core.publisher.Mono.block(Mono.java:1311)
	at org.abhijitsarkar.Application.run(Application.kt:68)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:789)
	... 29 more
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:120)
		at reactor.core.publisher.Mono.block(Mono.java:1312)
		... 31 more
```

**Comment by asarkar** [comment]
I tracked this down to a `flatMap` operation that was returning null. I understand that null is not allowed in a stream, but the error message sent me down a rabbit hole for couple of hours. The problem was **not** with `block` at all, which is what I was lead to believe by the stacktrace. I'm keeping this ticket open for that reason.

**Comment by akarnokd** [comment]
Unless you enable assembly tracking, we can't do much about such errors because the lambda/interface implementation of `Function` provided to `map` simply doesn't hold reasonable information about where its implementation is. If you have inner classes, the `toString()` of a function reference pointing to `ParentClass$12` may help you under IntelliJ but not in other IDEs. For lambdas, you'd probably get a random number without any hint about its parent class or location.

**Comment by asarkar** [comment]
@akarnokd If you say so, feel free to close the ticket. For a user POV, I was hoping that there was a way to provide more, or at least not misleading, information regarding the source of the error.
BTW, what is "assembly tracking" - can you point me to some documentation for that?

**Comment by smaldini** [comment]
@asarkar http://next.projectreactor.io/docs/core/release/reference/docs/index.html#_debugging_reactor
