### ISSUE TITLE
FluxTimeout race between next event and timeout signal

### ISSUE THREAD

**Issue by osi** [reactor/reactor-core#744]
I encountered the following stack trace:

```
        at reactor.core.Exceptions.failWithCancel(Exceptions.java:148)
        at reactor.core.publisher.Operators.onNextDropped(Operators.java:279)
        at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onNext(FluxTimeout.java:135)
        at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:109)
        at reactor.core.publisher.FluxFilter$FilterSubscriber.onNext(FluxFilter.java:97)
        at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:77)
        at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replayNormal(FluxReplay.java:787)
        at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.replay(FluxReplay.java:871)
        at reactor.core.publisher.ReplayProcessor$ReplayInner.request(ReplayProcessor.java:561)
        at reactor.core.publisher.MonoNext$NextSubscriber.request(MonoNext.java:103)
        at reactor.core.publisher.FluxFilter$FilterSubscriber.request(FluxFilter.java:161)
        at reactor.core.publisher.FluxMap$MapSubscriber.request(FluxMap.java:150)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:1300)
        at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onSubscribe(FluxTimeout.java:119)
        at reactor.core.publisher.FluxMap$MapSubscriber.onSubscribe(FluxMap.java:87)
        at reactor.core.publisher.FluxFilter$FilterSubscriber.onSubscribe(FluxFilter.java:76)
        at reactor.core.publisher.MonoNext$NextSubscriber.onSubscribe(MonoNext.java:65)
        at reactor.core.publisher.ReplayProcessor.subscribe(ReplayProcessor.java:313)
        at reactor.core.publisher.MonoNext.subscribe(MonoNext.java:41)
        at reactor.core.publisher.MonoFilter.subscribe(MonoFilter.java:46)
        at reactor.core.publisher.MonoMap.subscribe(MonoMap.java:55)
        at reactor.core.publisher.MonoTimeout.subscribe(MonoTimeout.java:77)
```

With code that's similar to:

```
replayProcessorInstance
    .next()
    .filter()
    .map()
    .timeout(duration, replacement, scheduler)
```

I don't think I have anything wrong. In reading the code of `FluxTimeout` it is unclear how it protects against a race between the timeout firing and the cancellation of the main subscription.

specifically, https://github.com/reactor/reactor-core/blob/master/reactor-core/src/main/java/reactor/core/publisher/FluxTimeout.java#L134 isn't checking to see if the timeout has fired and cancelled and the onNext is a valid event that can occur prior to cancellation (since it is async).

is my analysis correct?

**Comment by smaldini** [comment]
It does seem to be slightly aggressive indeed, its using the flag value to achieve something similar to 
if(cancelled) -> drop. We could be able to let a single comparison runs (the one after), even this seems to be more aggressive compared to FlowableTimeout, wdyt @akarnokd ?

**Comment by smaldini** [comment]
Definitively ways to improve it after re-review, but I'll postpone that to RC1

**Comment by smaldini** [comment]
Definitively ways to improve the operator, adding for RC1

**Comment by akarnokd** [comment]
The operator looks too convoluted, I would write it differently these days.

**Comment by simonbasle** [comment]
@osi could you write a simple `StepVerifier`-based unit test to make sure we're on the same page as to what you expect?

**Comment by osi** [comment]
sure, i'll give it a whirl

**Comment by osi** [comment]
I don't care if the result is cat or dog. This test fails with a `CancelException` though
```
        StepVerifier.withVirtualTime(
            () -> Flux.just("cat")
                      .delaySubscription(Duration.ofMillis(3))
                      // We cancel on another scheduler that won't do anything to force it to act like
                      // the event is already in flight
                      .cancelOn(VirtualTimeScheduler.create())
                      .timeout(Duration.ofMillis(2), Flux.just("dog").delayElements(Duration.ofMillis(5)))
        )
                    .thenAwait(Duration.ofMillis(6))
                    .expectNext("cat")
                    .expectComplete()
                    .verify(Duration.ofMillis(10));
```

**Comment by simonbasle** [comment]
shouldn't the `thenAwait` at least wait for 7ms (timeout duration + fallback delay)?

this could be impacted by the proposed change in https://github.com/reactor/reactor-core/pull/814#issuecomment-325398454

**Comment by osi** [comment]
Yeah, the await could maybe be longer in order to allow the fallback to succeed. It wasn't clear to me if the fallback had published yet in my original stack trace, just that the main source might have. 

not having the `CancelException` was the point of the issue - but i think it'd be good hygiene to not have the core library trigger "safe drops".

**Comment by simonbasle** [comment]
having `onNextDropped` not fail anymore (#823) allow for better tracking of values that don't make it downstream, and we think this is legit in the case of a timeout concurrent to an onNext.

I'll just add your test (with a slight modification) to the master branch to track this case. I'll also open a separate issue to isolate the case with a fallback in the operator.
