### ISSUE TITLE
Getting UnsupportedOperationException in publishOn

### ISSUE THREAD

**Issue by Stepuk** [reactor/reactor-core#767]
Hi Reactor Team,

Consider the following code. The motivation is to enrich each value from Publisher `a` with a single value from Publisher `b` (it's known that `b` emits exactly one value) to make a pair.

```
public class Main {

    public static void main(String... args) {
        Publisher<String> a = Flux.just("a");
        Publisher<String> b = Mono.just("b");

        Flux<Tuple2<String, String>> result =
                Flux.from(a)
                        .flatMap(value -> Mono.just(value).and(Mono.from(b)))
                        .publishOn(Schedulers.single());

        result.subscribe();
    }
}
```

This crashes with following exception:

```
Exception in thread "main" java.lang.UnsupportedOperationException: Operators should not use this method!
	at reactor.core.Fuseable$QueueSubscription.offer(Fuseable.java:117)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.onNext(FluxPublishOn.java:225)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:947)
	at reactor.core.publisher.MonoWhen$WhenCoordinator.signal(MonoWhen.java:249)
	at reactor.core.publisher.MonoWhen$WhenInner.onNext(MonoWhen.java:308)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:1668)
	at reactor.core.publisher.MonoWhen$WhenInner.onSubscribe(MonoWhen.java:298)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
	at reactor.core.publisher.MonoWhen$WhenCoordinator.subscribe(MonoWhen.java:178)
	at reactor.core.publisher.MonoWhen.subscribe(MonoWhen.java:124)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:168)
	at reactor.core.publisher.FluxFlatMap.subscribe(FluxFlatMap.java:91)
	at reactor.core.publisher.FluxPublishOn.subscribe(FluxPublishOn.java:94)
	at reactor.core.publisher.Flux.subscribe(Flux.java:6575)
	at reactor.core.publisher.Flux.subscribe(Flux.java:6542)
	at reactor.core.publisher.Flux.subscribe(Flux.java:6431)
	at ru.stepuk.bergamo.Main.main(Main.java:20)

```

If I put more values in Publisher `a` i.e. `Publisher<String> a = Flux.just("a", "x");` the error disappears.

It also disappears if I put empty `doOnNext` (`.doOnNext(x->{})`) before `publishOn`.

I guess it's some kind of assembly-time optimization bug? Reproducing in 3.0.7.RELEASE and in 3.1.0.M3. Please let me know if any additional information is required from me.

**Comment by simonbasle** [comment]
(tracked down to commit 5254299a using git bisect)
