### ISSUE TITLE
Introduce version of reduceWhen() operator that allows async accumulation.

### ISSUE THREAD

**Issue by dfeist** [reactor/reactor-core#810]
`Flux.reduce()` requires that the accumulation function be synchronous, but in some use case the result of accumulation that should be made available when processing the event in the stream is available asynchronously and a `block()` is required to use `reduce` in this case.

An alternative is to use a `Mono` seed and thus return `Mono` in the accumulator as below, and while this works, it not ideally from a usability perspective because it's more complex and needs to be followed by  `concatMap(Function.identidy())`, but primarily based on my observation is had a major impact on stack depth, because stack grows linearly for every event in the stream until, if there the stream is big enough, a `StackOverflowException` is produced.

The solution in my mind is for there to be an async version of `reduce()` (and potentially also `scan()`) that allows for asynchronous accumulation e.g.

```
<A> Mono<A> reduceWhen(A initial, BiFunction<A, ? super T, Mono<A>> accumulator)
```

**Comment by simonbasle** [comment]
@dfeist with the upcoming introduction of the `expand` operator, a better workaround would be to use `expand` to create the whole hierarchy of `Mono`s and emit their values and then classical `reduce` to reduce them live, as they become available. Looks like it doesn't suffer from the shortcomings of the mono seed + concatMap strategy. Something like this:

```java
Flux.just(1)
    .expand(i -> (i == 1_00_000) ?
		    Mono.empty() :
		    Mono.just(i + 1))
    .reduce((a, b) -> a + b)
    .subscribe(System.out::println, Throwable::printStackTrace);
```

The example above runs in milliseconds. Terminating the expand with an error rather than empty  after 1M elements yields the following stack, which is not so deep:

```
java.lang.IllegalStateException: boom
	at reactor.core.publisher.FluxExpandTest.lambda$useAsScanWhen$25(FluxExpandTest.java:547)
	at reactor.core.publisher.FluxExpand$ExpandBreathSubscriber.onNext(FluxExpand.java:111)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:1625)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:1439)
	at reactor.core.publisher.FluxExpand$ExpandBreathSubscriber.onSubscribe(FluxExpand.java:101)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
	at reactor.core.publisher.Mono.subscribe(Mono.java:2911)
	at reactor.core.publisher.FluxExpand$ExpandBreathSubscriber.drainQueue(FluxExpand.java:164)
	at reactor.core.publisher.FluxExpand.subscribe(FluxExpand.java:68)
	at reactor.core.publisher.FluxTake.subscribe(FluxTake.java:56)
	at reactor.core.publisher.MonoReduce.subscribe(MonoReduce.java:46)
	at reactor.core.publisher.Mono.subscribe(Mono.java:2911)
	at reactor.core.publisher.Mono.subscribeWith(Mono.java:3032)
	at reactor.core.publisher.Mono.subscribe(Mono.java:2905)
	at reactor.core.publisher.Mono.subscribe(Mono.java:2872)
	at reactor.core.publisher.Mono.subscribe(Mono.java:2844)
	at reactor.core.publisher.FluxExpandTest.useAsScanWhen(FluxExpandTest.java:552)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

Process finished with exit code 0
```

do you feel it would be a good workaround? The limitation with that is that the type cannot be changed.

Another version built on top of expand that could allow type changes would use `Tuple` internally, something like that:
```java
@Test
	public void useAsScanWhenWithTuple() {
		StepVerifier.create(
		Flux.just(1)
		    .transform(expandAsScan("", i -> i + 1, (previousState, currentStep) -> {
			    if (currentStep > 5) return Mono.empty();
			    return Mono.just(previousState + currentStep); //this would be externally provided
		    }))
		)
		            .expectNext("1", "12", "123", "1234", "12345")
		            .verifyComplete();
	}

	private <T,V> Function<Flux<T>, Publisher<V>> expandAsScan(
			V initialState,
			Function<T, T> stepFunction,
			BiFunction<V, T, Mono<V>> stepToValueAsync) {
		return f ->
				f.flatMap(i -> stepToValueAsync.apply(initialState, i)
				                               .map(s -> Tuples.of(s, i)))
				 .expand(ti -> {
					 T nextStep = stepFunction.apply(ti.getT2());
					 return stepToValueAsync.apply(ti.getT1(), nextStep)
					                        .map(state -> Tuples.of(state, nextStep));
				 })
				 .map(Tuple2::getT1);
	}
```

**Comment by smaldini** [comment]
Seems good enough for now, feel free to re open
