### ISSUE TITLE
Exception happens even with onErrorReturn

### ISSUE THREAD

**Issue by hillmanli-seekers** [reactor/reactor-core#851]
### Expected behavior
Print the value inside onErrorReturn and exits without exception.

### Actual behavior
Sometimes the expected behavior is observed, but very often following exception happens. Same thing happens with onErrorResume as well.

Exception in thread "main" reactor.core.Exceptions$CancelException: The subscriber has denied dispatching
	at reactor.core.Exceptions.failWithCancel(Exceptions.java:148)
	at reactor.core.publisher.Operators.onNextDropped(Operators.java:282)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onNext(FluxTimeout.java:141)
	at reactor.core.publisher.FluxGenerate$GenerateSubscription.next(FluxGenerate.java:164)
	at hillman.reactive.simple.SimpleTest.lambda$print$1(SimpleTest.java:34)
	at reactor.core.publisher.FluxGenerate.lambda$new$1(FluxGenerate.java:56)
	at reactor.core.publisher.FluxGenerate$GenerateSubscription.fastPath(FluxGenerate.java:218)
	at reactor.core.publisher.FluxGenerate$GenerateSubscription.request(FluxGenerate.java:197)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:1381)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onSubscribe(FluxTimeout.java:120)
	at reactor.core.publisher.FluxGenerate.subscribe(FluxGenerate.java:83)
	at reactor.core.publisher.FluxTimeout.subscribe(FluxTimeout.java:82)
	at reactor.core.publisher.FluxPeek.subscribe(FluxPeek.java:83)
	at reactor.core.publisher.FluxOnErrorResume.subscribe(FluxOnErrorResume.java:46)
	at reactor.core.publisher.Flux.subscribe(Flux.java:6292)
	at reactor.core.publisher.Flux.subscribeWith(Flux.java:6360)
	at reactor.core.publisher.Flux.subscribe(Flux.java:6285)
	at reactor.core.publisher.Flux.subscribe(Flux.java:6249)
	at reactor.core.publisher.Flux.subscribe(Flux.java:6192)
	at hillman.reactive.simple.SimpleTest.print(SimpleTest.java:38)
	at hillman.reactive.simple.SimpleTest.main(SimpleTest.java:22)

### Steps to reproduce
I tried with following simple code. The timeout of 3ms is arbitrary to make TimeoutException happens.
`
        Flux.generate(sink -> sink.next(0))
            .timeout(Duration.ofMillis(3L))
            .doOnTerminate(() -> log.info("doOnTerminate"))
            .onErrorReturn(-1)
            .subscribe(v -> log.info("{}", v));
`
### Reactor Core version
3.1.0M3

### JVM version (e.g. `java -version`)
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

### OS version (e.g. `uname -a`)
4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by osi** [comment]
This looks similar to #744

**Comment by smaldini** [comment]
This should be fixed in 3.1.0.RC1 now please update us

**Comment by hillmanli-seekers** [comment]
Great. It does not happen any more in 3.1.0.RC1. Thanks!
