### ISSUE TITLE
Logger blew up under load

### ISSUE THREAD

**Issue by dsyer** [reactor/reactor-core#93]
I'm not sure if this is a Reactor problem or something to do with the environment, or the Spring Boot logging system or what. But the stack trace looks clean and points at reactor:

```
2016-05-27 11:54:25.898  INFO 3750 --- [   parallel-2-1] reactor.core.publisher.FluxLog           :  onNext(7)
[WARNING] 
2016-05-27 11:54:28.450  INFO 3750 --- [   parallel-2-1] reactor.core.publisher.FluxLog           :  request(1)
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:421)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at ch.qos.logback.classic.spi.ThrowableProxyUtil.subjoinPackagingData(ThrowableProxyUtil.java:123)
	at ch.qos.logback.classic.pattern.ExtendedThrowableProxyConverter.extraData(ExtendedThrowableProxyConverter.java:24)
	at ch.qos.logback.classic.pattern.ThrowableProxyConverter.printStackLine(ThrowableProxyConverter.java:222)
	at ch.qos.logback.classic.pattern.ThrowableProxyConverter.subjoinSTEPArray(ThrowableProxyConverter.java:199)
	at ch.qos.logback.classic.pattern.ThrowableProxyConverter.recursiveAppend(ThrowableProxyConverter.java:161)
	at ch.qos.logback.classic.pattern.ThrowableProxyConverter.recursiveAppend(ThrowableProxyConverter.java:168)
	at ch.qos.logback.classic.pattern.ThrowableProxyConverter.throwableProxyToString(ThrowableProxyConverter.java:151)
	at org.springframework.boot.logging.logback.ExtendedWhitespaceThrowableProxyConverter.throwableProxyToString(ExtendedWhitespaceThrowableProxyConverter.java:35)
	at ch.qos.logback.classic.pattern.ThrowableProxyConverter.convert(ThrowableProxyConverter.java:145)
	at ch.qos.logback.classic.pattern.ThrowableProxyConverter.convert(ThrowableProxyConverter.java:1)
	at ch.qos.logback.core.pattern.FormattingConverter.write(FormattingConverter.java:36)
	at ch.qos.logback.core.pattern.PatternLayoutBase.writeLoopOnConverters(PatternLayoutBase.java:114)
	at ch.qos.logback.classic.PatternLayout.doLayout(PatternLayout.java:141)
	at ch.qos.logback.classic.PatternLayout.doLayout(PatternLayout.java:1)
	at ch.qos.logback.core.encoder.LayoutWrappingEncoder.doEncode(LayoutWrappingEncoder.java:130)
	at ch.qos.logback.core.OutputStreamAppender.writeOut(OutputStreamAppender.java:187)
	at ch.qos.logback.core.OutputStreamAppender.subAppend(OutputStreamAppender.java:212)
	at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:100)
	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:48)
	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
	at ch.qos.logback.classic.Logger.error(Logger.java:538)
	at reactor.core.util.Logger$Slf4JLogger.error(Logger.java:477)
	at reactor.core.publisher.Computations$ProcessorWorker.routeError(Computations.java:951)
```

This happened in a Tomcat app under load, but as you can see it's from a thread created by `Computations`.

**Comment by dsyer** [comment]
UPDATE: 

I can see about 10^6 threads called "parallel-1-1" so I guess I'm missing an optimization here and
`Computations.parallel()` can be considered harmful.

**Comment by akarnokd** [comment]
I guess `Computations.parallel()` creates a new, independent scheduler whenever it is called; unlike RxJava where `Schedulers.computation()` returns the same instance. This is a library design decision in both RxJava and Reactor-Core.

**Comment by dsyer** [comment]
Yeah, that was my conclusion too, but I haven't found a great way to fix it. If I share a scheduler across all parallel requests it freezes up (no idea why yet). If I share it only within the same method I need to call `shutdown()` in a `doOnSuccess()` otherwise performance degrades over time (600-1200 requests).

You can see the degradation here (notice the long tail, which is a sign that next time you run the test it will gum up - this is how I saw the exception above):

https://github.com/dsyer/reactive-notes/blob/ff38e57cdca396d3c78a3982176605517a1b9afc/io.adoc

compared to when you shutdown on each request (no long tail and I can run the same test multiple times):

https://github.com/dsyer/reactive-notes/blob/b95398a28105c972ba5957304aca87136b94ea11/io.adoc

**Comment by smaldini** [comment]
Should we consider this done ? @dsyer
